### ISSUE TITLE
[R-Forge #2636] Improve cbind.data.table speed

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#578] opened 2014-06-08 13:16 UTC
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2636&group_id=240&atid=978)

As raised here :

http://r.789695.n4.nabble.com/data-table-and-cbind-tp4662258.html

even though := and set() are designed to add columns by reference,  might as well do the best we can with cbind too.

**Comment by MichaelChirico** [comment] 2018-04-02 01:37
I guess subsumed by #2576

**Comment by jangorecki** [comment] 2019-06-03 12:09
The link from first post does not work. Closing as a duplicate of #2576 then

**Closed by jangorecki** 2019-06-03 12:09 UTC
Labels: feature request
