### ISSUE TITLE
[Request] Strip commas from columns declared numeric in fread

### ISSUE THREAD

**Issue by Stevo15025** [Rdatatable/data.table#1723] opened 2016-05-26 14:36 UTC
A common problem when moving data from excel to R is that excel leaves commas in numbers if the user is not careful. Would it be possible to, as the data is being read through in fread, if the past X rows were numeric and the newest row has a comma, strip the comma and continue with the column being numeric?

I was thinking something similar to this stackoverflow [answer](http://stackoverflow.com/a/3611619/2269255)

``` r
setAs("character", "num.with.commas", 
        function(from) as.numeric(gsub(",", "", from) ) )
```

The user could have an option `commaNumeric = TRUE` such that when true fread will rip commas out of columns it has already declared numeric after the first 30 rows or so.

P.S. thanks for the package, it's really wonderful!

**Comment by arunsrinivasan** [comment] 2016-05-26 14:52
Thanks. Many `fread` enhancements are planned for next release.

**Comment by jaapwalhout** [comment] 2016-05-30 10:14
Would be nice, but could this interfere with European style decimal separator (which is a comma)?

**Comment by MichaelChirico** [comment] 2016-06-01 15:25
@jaapwalhout something to keep an eye out for, but I think interacting this with the already-implemented `dec` argument should be sufficient.

**Comment by jangorecki** [comment] 2016-06-02 21:31
this seems to be duplicate of #1636

**Closed** 2017-07-04 08:03 UTC
Labels: duplicate, Enhancement, fread
