### ISSUE TITLE
Expected sep (',') but new line or EOF ends field

### ISSUE THREAD

**Issue by skanskan** [Rdatatable/data.table#1856] opened 2016-09-26 10:47 UTC
Hello.

I'm trying to Error in fread("name.csv" : 
  Expected sep (',') but new line or EOF ends field 1 on line 224324 when reading data: 
In addition: There were 50 or more warnings (use warnings() to see the first 50).

What should I modify on the file to solve the problem?

**Comment by franknarf1** [comment] 2016-09-26 10:50
I'd examine line 224324  and count if it has as many commas as the others. If not, one solution might be to add in commas so that the row makes sense again.

**Comment by skanskan** [comment] 2016-09-26 11:07
If I use fread to read the whole file it works well.
But if I use it to read chunks of 10000 lines

my <- fread("unzip -c short.zip", skip=1+(iter*chunk), nrows=chunk, na.strings=c("", "NA")) 

it works well on every chunk except on the last one.

**Comment by skanskan** [comment] 2016-09-26 11:58
May it have anything to do with the max size of the file in Windows 7?

**Comment by MichaelChirico** [comment] 2016-09-26 12:05
are you using the development version? try the new fill argument

**Comment by skanskan** [comment] 2016-09-26 12:10
Where cvan I find more information on the fill argument?

**Comment by MichaelChirico** [comment] 2016-09-26 12:30
go to the wiki page and look for the instructions to install version 1.9.7.
I would link but I'm on mobile

On Sep 26, 2016 8:10 AM, "skanskan" <notifications@github.com> wrote:

Where cvan I find more information on the fill argument?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Rdatatable/data.table/issues/1856#issuecomment-249552496>,
or mute the thread

**Comment by jangorecki** [comment] 2016-09-26 13:16
@skanskan [recent `fread` manual](https://jangorecki.gitlab.io/data.table/library/data.table/html/fread.html), installation of 1.9.7 is described in [installation wiki](https://github.com/Rdatatable/data.table/wiki/Installation).
When filling issue, be sure to provide reproducible example, as generally there is nothing we can do without it.

**Comment by skanskan** [comment] 2016-09-27 18:03
The problem was that the file ended with a an empty line.
But this line was created by fwrite when saving previous results.

**Comment by Nicholas-Mitchell** [comment] 2017-06-28 14:21
I have also just faced this same issue.

It seems to be easy to reproduce for me. Simply take an Excel file, save it as CSV (from Excel).
This file will produce the error mentioned above.
Opening the said CSV file with something like Notepad or gedit, you will see there is an empty line at the end of the file. Deleting this by hand and resaving the file (as metioned by @skanskan) then allows the edited CSV to be loaded by `fread`.

I did try using the `nrows` argument (-1L is default, so I tried -2L), but this doesn't make any difference, leading me to think it is an issue with the method used for opening a connection to the file.

Another side note, in Rstudio, using the built-in tools, just clicking on the original CSV file in the File Viewer, seems to work just fine. This uses the `readr` package and all the default function arguments.

**Comment by st-pasha** [comment] 2017-07-06 20:37
@Nicholas-Mitchell Could you attach an example CSV file that exhibits such behavior? I do not have a copy of Excel available :(

**Comment by Nicholas-Mitchell** [comment] 2017-07-06 21:05
@st-pasha  I also don't have access to Excel right now. I saved a CSV from Open Office, and that could be read with `fread()` with default arguments. I then added an empty line at the end of the file, just using a text editor... `fread()` was still able to load that. I saved the file into Excel format, opened that up in Open Office and exported it to a CSV, but looking at the output in a text editor shows me that there is no empty line. Open Office seems to export to CSV more cleanly than Excel.

Result 1: I cannot reproduce it without Excel itself
Result 2: It seems to be more than a simple empty line at the end of the file that is causing the problem.

Perhaps there is one of the magnificent _[hidden characters](https://www.liquidweb.com/kb/dos2unix-removing-hidden-windows-characters-from-files/)_ that is at the end of the file after exporting from Excel.

**Comment by st-pasha** [comment] 2017-07-07 00:45
Could it be related to #1612 then?

**Comment by mattdowle** [comment] 2018-03-03 11:01
Great, looks like @st-pasha fixed this.
News item from dev 1.10.5 is : 
> Detects and ignores trailing ^Z end-of-file control character sometimes created on MS DOS/Windows, #1612. Thanks to Gergely Daróczi for reporting and providing a file.

If the problem is not fixed by dev, please open a new issue with an example file please.

**Closed by mattdowle** 2018-03-03 11:01 UTC
Labels: fread, not reproducible
