### ISSUE TITLE
error with set() or := NULL to a list column item

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#5526] opened 2022-11-14 02:17 UTC
```R
DT = data.table(A=1:3, B=list())
DT
      A      B
   <int> <list>
1:     1       
2:     2       
3:     3       
DT[2, B:=letters]     # ok
DT
       A               B
   <int>          <list>
1:     1                
2:     2 a,b,c,d,e,f,...      # ok
3:     3                
DT[2, B:=NULL]
Error in `[.data.table`(DT, 2, `:=`(B, NULL)) : 
  When deleting columns, i should not be provided
set(DT, 2L, "B", NULL)
Error in set(DT, 2L, "B", NULL) : 
  When deleting columns, i should not be provided

# Expected result: NULL in that list column item
DT
      A      B
   <int> <list>
1:     1       
2:     2          
3:     3       
```

When fixed can simplify `tables()` dd2134e9aad6fd9d432b1cc0a35ca9c33fcd5dca #5524

**Comment by ben-schwen** [comment] 2022-11-14 13:09
Actually, I think it does not work for all column types

``` r
DT = data.table(a=1:3, b=4:6)
DT
#>        a     b
#>    <int> <int>
#> 1:     1     4
#> 2:     2     5
#> 3:     3     6
DT[2, b:=NULL]
#> Error in `[.data.table`(DT, 2, `:=`(b, NULL)): When deleting columns, i should not be provided
```

**Comment by Nj221102** [comment] 2024-03-08 10:09
Hi @MichaelChirico I came across this Bug while browsing through the issue's section and wanted to work on it , but while reproducing this bug i came across some differences in output from the one mentioned in the issue.

```
DT = data.table(A=1:3, B=list())
> DT
       A      B
   <int> <list>
1:     1 [NULL].     <-- *** default for the list is not empty anymore , it prints null instead***
2:     2 [NULL]
3:     3 [NULL]
> DT[2, B:=letters]     
> DT
       A               B
   <int>          <list>
1:     1          [NULL]
2:     2 a,b,c,d,e,f,...
3:     3          [NULL]
> DT[2, B:=NULL]
Error in `[.data.table`(DT, 2, `:=`(B, NULL)) : 
  When deleting columns, i should not be provided
> DT
       A               B
   <int>          <list>
1:     1          [NULL]
2:     2 a,b,c,d,e,f,...
3:     3          [NULL]
> set(DT, 2L, "B", NULL)
Error in set(DT, 2L, "B", NULL) : 
  When deleting columns, i should not be provided.  < - - ***while the actual error is still the same .***
> DT
       A               B
   <int>          <list>
1:     1          [NULL]
2:     2 a,b,c,d,e,f,...                          <-- *** the 2nd item in the  column B doesn't disappear after the operations.***
3:     3          [NULL]
```
and yeah i m confused about the last table mentioned in the issue, is it supposed to show the expected output or the output we got after doing all these operation

**Comment by ben-schwen** [comment] 2024-03-08 10:25
It's the expected output when the set operation succeeded instead of erroring.

Note that we recently changed the way NULL elements are printed to distinct them from the empty string.

Changes need to be made in `Cassign` which is one of the trickier C parts in our codebase.

FWIW you also do not have to mention Michael in every issue, since he subscribed to all changes anyway IINM

**Comment by Nj221102** [comment] 2024-03-08 10:27
> It's the expected output when the set operation succeeded instead of erroring.
> 
> Note that we recently changed the way NULL elements are printed to distinct them from the empty string.
> 
> Changes need to be made in `Cassign` which is one of the trickier C parts in our codebase.
> 
> FWIW you also do not have to mention Michael in every issue, since he subscribed to all changes anyway IINM

Thanks, will keep that in mind.

**Comment by MichaelChirico** [comment] 2024-03-09 13:32
Confirming what Ben said: the change from `` (nothing) to `[NULL]` is due to #4250, i.e., the actual data in the table is the same in both cases, but just prints differently.

The error is thrown here:

https://github.com/Rdatatable/data.table/blob/15c127e99f8d6aab599c590d4aec346a850f1334/src/assign.c#L420

So indeed you'll need to edit the C code here to make the fix. That code is relatively complex, but should also be pretty well-tested, so a good strategy is to add a new test for the desired behavior, then try and make changes. If you do something wrong, you'll likely fail other tests, so if you have a change that passes all existing + your new test, it's likely correct.

**Comment by joshhwuu** [comment] 2024-07-31 21:18
Was looking at this because (at first glance) it seemed to be related to #6167. I believe that setting a column to `NULL` given `i` is not allowed for both list and non-list columns:

```R
DT = data.table(A=1:3, B=list())
DT[2, A := NULL]
Error in `[.data.table`(DT, 2, `:=`(A, NULL)) : 
  When deleting columns, i should not be provided
```

Are we expecting that `list` columns are treated differently as in we can delete individual rows of columns by selecting `i` and setting the col to NULL? Or that we should change this behavior for all types of columns?

FWIW I think the deletion can be done by setting to `list(list(NULL))` instead
```R
DT[2, B := list(list(NULL))]
       A      B
   <int> <list>
1:     1 [NULL]
2:     2 [NULL]
3:     3 [NULL]
```

**Comment by MichaelChirico** [comment] 2024-08-01 05:37
I think the point is we _can_ make `DT[2L, B:=NULL]` "just work", because it's currently an error.

That said, I don't think we should -- it would break the very simple "x := NULL" ---> "delete x" paradigm we have going.

OTOH, I find this behavior less ideal:

```r
DT[2L, B := .(NULL)]
```

We _might_ expect that to assign `list(NULL)` as the second row, not remembering that this is actually interpreted as "LHS: 1 column, RHS: list with one item--> the corresponding value for LHS column --> equivalent to B := NULL". I would guess there's no way to make `DT[2, B:=.(NULL)]` "work" without also letting `DT[2, B:=NULL]` work (well, without substantially rewiring `set()`/`assign`/`[` to accommodate this).

And given the even shorter `DT[2L, B:= .(.(NULL))]` works "as expected", I think that's plenty concise.

Maybe what can be done is to improve the error message for this case (LHS: list column, also `i` present) to include something to the effect of "if you intended to assign `NULL` to the list, use a `list(list(NULL))` in the query" (wording may need to be fine-tuned to be sufficiently generalized)

**Comment by joshhwuu** [comment] 2024-08-01 19:51
> Maybe what can be done is to improve the error message for this case (LHS: list column, also `i` present) to include something to the effect of "if you intended to assign `NULL` to the list, use a `list(list(NULL))` in the query" (wording may need to be fine-tuned to be sufficiently generalized)

I think this is the way to go as well! @Nj221102 since this issue is assigned to you, would you like to write up a PR? Otherwise I can take over or even include it in #6167, as that PR covers a similar part of the code

**Comment by Nj221102** [comment] 2024-08-01 20:45
> > Maybe what can be done is to improve the error message for this case (LHS: list column, also `i` present) to include something to the effect of "if you intended to assign `NULL` to the list, use a `list(list(NULL))` in the query" (wording may need to be fine-tuned to be sufficiently generalized)
> 
> I think this is the way to go as well! @Nj221102 since this issue is assigned to you, would you like to write up a PR? Otherwise I can take over or even include it in #6167, as that PR covers a similar part of the code

done :), check it out.

**Closed** 2024-09-08 01:50 UTC
Labels: bug
