### ISSUE TITLE
Inconsistent NA string between fread and fwrite

### ISSUE THREAD

**Issue by ipstone** [Rdatatable/data.table#2673] opened 2018-03-14 13:44 UTC
The default NA string is different between fread and fwrite. Ideally they can be the same: na="NA".
Users might be caught by surprise with the different default settings.

```
fwrite(x, file = "", append = FALSE, quote = "auto",
  sep = ",", sep2 = c("","|",""),
  eol = if (.Platform$OS.type=="windows") "\r\n" else "\n",
  na = "", dec = ".", row.names = FALSE, col.names = TRUE,
  qmethod = c("double","escape"),
  logicalAsInt = FALSE, dateTimeAs = c("ISO","squash","epoch","write.csv"),
  buffMB = 8L, nThread = getDTthreads(),
  showProgress = getOption("datatable.showProgress"),
  verbose = getOption("datatable.verbose"))
```

but fread:
```
fread(input, sep="auto", sep2="auto", nrows=-1L, header="auto", na.strings="NA", file,
stringsAsFactors=FALSE, verbose=getOption("datatable.verbose"), autostart=1L,
skip=0L, select=NULL, drop=NULL, colClasses=NULL,
integer64=getOption("datatable.integer64"),         # default: "integer64"
dec=if (sep!=".") "." else ",", col.names, 
check.names=FALSE, encoding="unknown", quote="\"", 
strip.white=TRUE, fill=FALSE, blank.lines.skip=FALSE, key=NULL, 
showProgress=getOption("datatable.showProgress"),   # default: TRUE
data.table=getOption("datatable.fread.datatable")   # default: TRUE
)
```

**Comment by HughParsonage** [comment] 2018-03-14 13:50
Duplicate of #2281

**Closed by HughParsonage** 2018-03-14 13:50 UTC
