### ISSUE TITLE
[bug]variable masked in a function

### ISSUE THREAD

**Issue by ieiwk** [Rdatatable/data.table#5968] opened 2024-02-28 03:06 UTC
in a function with an argument name that is also used in a data.table column, accessing that variable returns strange things:
> ( function( x, a) { x[ 9, a]})( data.table::as.data.table( list( 'a' = letters, 'b' = LETTERS)))
   a b
1: i I

for 'b' the result is expected:
> ( function( x, a) { x[ 9, b]})( data.table::as.data.table( list( 'a' = letters, 'b' = LETTERS)))
[1] "I"

for 'a' to return the expeced restult, surrounding a with '(' and ')' works:
> ( function( x, a) { x[ 9, ( a)]})( data.table::as.data.table( list( 'a' = letters, 'b' = LETTERS)))
[1] "i"

data.table Version: 1.14.10

**Comment by ieiwk** [comment] 2024-02-28 03:50
update: 1.15.0 also has this case

**Comment by MichaelChirico** [comment] 2024-02-28 05:34
I believe this is WAI. Your minimal code is a bit hard to read, so let's spell it out more carefully:

```r
DT = data.table(a = letters, b = LETTERS)
f = \(x, a) x[9, a]
g = \(x, a) x[9, b]

f(DT)
#         a      b
#    <char> <char>
# 1:      i      I
g(DT)
# [1] "I"
```

The key is that argument `a` is _missing_ inside `f()`, but this missingness gets passed on to `[`:

```r
trace(data.table:::`[.data.table`, at=1, quote(message("j is missing? ", missing(j))))
invisible(f(DT))
# j is missing? TRUE
invisible(g(DT))
# j is missing? FALSE
```

So really this is about how R works. One possible way to get around this is not to rely on the missingness within `j`, e.g. supplying a default of `j=NULL` instead, but this likely has back-compatibility issues, so would not be pursued without commensurate benefit.

There's likely some better way to design your function, but you'll need to provide more details. In the meantime, please also check out the vignette on programming:

https://cran.r-project.org/web/packages/data.table/vignettes/datatable-programming.html

**Comment by MichaelChirico** [comment] 2024-02-28 05:36
Closing the issue, but feel free to comment further & we can help work around this issue.

**Closed by MichaelChirico** 2024-02-28 05:36 UTC
Labels: wontfix

**Comment by ieiwk** [comment] 2024-02-28 07:46
Thank you, Michael.

Your reply is informative and suggestiong working. I also learned another way of defining functions in R, i.e. \(...) ...; and the usage of trace.

I can guess that the missingness was passed to `[.data.table`. But I did not expect that supplying a default when defing a function would change the missingness, because a parameter with a default would also be missing when not passed an argument.

By the way, what does WAI stand for?

**Comment by ieiwk** [comment] 2024-02-28 07:48
> I believe this is WAI. Your minimal code is a bit hard to read, so let's spell it out more carefully:
> 
> ```r
> DT = data.table(a = letters, b = LETTERS)
> f = \(x, a) x[9, a]
> g = \(x, a) x[9, b]
> 
> f(DT)
> #         a      b
> #    <char> <char>
> # 1:      i      I
> g(DT)
> # [1] "I"
> ```
> 
> The key is that argument `a` is _missing_ inside `f()`, but this missingness gets passed on to `[`:
> 
> ```r
> trace(data.table:::`[.data.table`, at=1, quote(message("j is missing? ", missing(j))))
> invisible(f(DT))
> # j is missing? TRUE
> invisible(g(DT))
> # j is missing? FALSE
> ```
> 
> Thus `f(DT)` is the same as `DT[9,]`, while `g(DT)` is the same as `DT[9,b]`.
> 
> So really this is about how R works. One possible way to get around this is not to rely on the missingness within `j`, e.g. supplying a default of `j=NULL` instead, but this likely has back-compatibility issues, so would not be pursued without commensurate benefit.
> 
> There's likely some better way to design your function, but you'll need to provide more details. In the meantime, please also check out the vignette on programming:
> 
> https://cran.r-project.org/web/packages/data.table/vignettes/datatable-programming.html

Thank you, Michael.

Your reply is informative and suggestion working. I also learned another way of defining functions in R, i.e. (...) ...; and the usage of trace.

I can guess that the missingness was passed to [.data.table. But I did not expect that supplying a default when defing a function would change the missingness, because a parameter with a default would also be missing when not passed an argument.

By the way, what does WAI stand for?

**Comment by MichaelChirico** [comment] 2024-02-28 19:07
WAI=working as intended

> I can guess that the missingness was passed to [.data.table. But I did not expect that supplying a default when defing a function would change the missingness, because a parameter with a default would also be missing when not passed an argument.

I may have misspoken. Anyway, I think your function just needs to handle missingness, or default values, specifically:

```r
f <- function(x, a) {
  if (missing(a)) {
    # what should happen?
  } else {
    x[9, a]
  }
}

# or
f <- function(x, a = NULL) {
  if (is.null(a)) {
    # what should happen?
  } else {
    x[9, a]
  }
```

**Comment by ieiwk** [comment] 2024-02-29 04:41
> WAI=working as intended
> 
> > I can guess that the missingness was passed to [.data.table. But I did not expect that supplying a default when defing a function would change the missingness, because a parameter with a default would also be missing when not passed an argument.
> 
> I may have misspoken. Anyway, I think your function just needs to handle missingness, or default values, specifically:
> 
> ```r
> f <- function(x, a) {
>   if (missing(a)) {
>     # what should happen?
>   } else {
>     x[9, a]
>   }
> }
> 
> # or
> f <- function(x, a=NULL) {
>   if (is.null(a)) {
>     # what should happen?
>   } else {
>     x[9, a]
>   }
> }
> ```

I see. Thank you for your kindness.
