### ISSUE TITLE
Chained queries bug

### ISSUE THREAD

**Issue by Gayyam** [Rdatatable/data.table#4210] opened 2020-01-29 22:48 UTC
I am so sorry I cannot reliably reproduce this bug. This is because it happens only sometimes, and that too after some time has passed since I run the chained query.

![Chained queries bug](https://user-images.githubusercontent.com/9971062/73403436-4b6d7580-4354-11ea-81ce-d1cddc2f1267.PNG)

In this image, I run a chained query (which I have now rewritten using `fcase` - Thank you!) to create a column and print a summary of the newly created column. Notice how the output changes when I run the summary query for the fifth time.

I have also seen this occur once before, with the taskbar open, on a much larger dataset where the chained query took a few seconds to execute. After the chained query _finished running_, the processor usage increased to about 5-10% for a few seconds. Then, when I saw the newly created column, I realised that the code had been run twice.

In all, I have seen this occur about 10 times for two chained queries. The only thing that I could say with certainty is that in all cases, (a portion of) the chained query runs even before it is asked to!

<details><summary>sessionInfo()</summary>

```
 R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_New Zealand.1252  LC_CTYPE=English_New Zealand.1252    LC_MONETARY=English_New Zealand.1252 LC_NUMERIC=C                         LC_TIME=English_New Zealand.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.12.9 readxl_1.3.1     

loaded via a namespace (and not attached):
 [1] compiler_3.6.2   tools_3.6.2      pillar_1.4.3     rstudioapi_0.10  tibble_2.1.3     yaml_2.2.0       crayon_1.3.4     Rcpp_1.0.3       cellranger_1.1.0 pkgconfig_2.0.3  rlang_0.4.3
```

**Comment by jangorecki** [comment] 2020-01-30 14:42
Thank you for the report. Are you able to reproduce same problem when not having any extra packages loaded? Using just R and data.table.

**Comment by Gayyam** [comment] 2020-01-30 21:01
Thank you. I will try. By "just R", do you mean vanilla R GUI or is RStudio fine?

**Comment by jangorecki** [comment] 2020-01-31 01:47
Ideally vanilla R command line

**Comment by shrektan** [comment] 2020-02-27 13:26
@Gayyam Since you are using Windows, despite the small possibility, I still suspect it may due to the DLL issues - you build data.table from source but the previous version of datatable.dll is locked leads to some weird issues. So please close all your R session and rebuild data.table again. If this still happens, please: 

 

- Use `saveRDS()` to save the same variable `aaVisits`
- Restart a new session 
- Use `readRDS()` to read the variable `aaVisits` and then call `setDT()` on it
- Load only `data.table`
- Rerun `aaVisits[,.N,keyby=TravelParty]`

If it's still reproducible, I would happy to help if you can share the data (the RDS file).

**Comment by Gayyam** [comment] 2020-04-24 03:45
Hi all,

Sorry for the radio silence on this. I hope to get back to this soon. 

In the meanwhile, I have captured the issue via OBS (still on RStudio, but using v1.12.8 instead of v1.12.9). Thank you for your patience.

https://www.dropbox.com/s/z21zw0pgwbmbl19/data.table%20chained%20queries%20issue.mp4?dl=0

Thanks!

**Comment by jangorecki** [comment] 2020-04-24 09:28
@Gayyam is it reproducible in R console?

**Comment by jangorecki** [comment] 2020-11-14 08:44
Closing, we can re-open when more details to reproduce will be provided.

**Closed** 2020-11-14 08:44 UTC
Labels: not reproducible
