### ISSUE TITLE
expand grid of two data.tables

### ISSUE THREAD

**Issue by philipdelff** [Rdatatable/data.table#5305] opened 2022-01-07 20:57 UTC
For completeness, it would be helpful to have a way to expand a grid of two data.tables without merging by any columns. This is what merge.data.frame by default does if there is no columns to merge by.

```{r}
> df1 <- data.frame(a=1:2,b=3:4)
> df2 <- data.frame(c=5:6,d=7:8)
> merge(df1,df2)
  a b c d
1 1 3 5 7
2 2 4 5 7
3 1 3 6 8
4 2 4 6 8
```

In merge.data.table this is not allowed:
```{r}
> library(data.table)
> merge(as.data.table(df1),as.data.table(df2),allow.cartesian=TRUE)
Error in merge.data.table(as.data.table(df1), as.data.table(df2), allow.cartesian = TRUE) : 
  A non-empty vector of column names for `by` is required.
```
To my best knowledge there is no direct way of doing this in data.table. [NMdata::egdt](https://github.com/philipdelff/NMdata/blob/master/R/egdt.R) does this using data.table by a very simple implementation of the solution given by Josh O'Brian here:
https://stackoverflow.com/questions/12321797/cartesian-product-using-data-table-package

Could this somehow be supported by data.table? To me, it does not have to be by merge.data.table but just some function within data.table.

**Comment by ben-schwen** [comment] 2022-01-07 23:57
Thanks for filling the request. Duplicate of

**Closed** 2022-01-07 23:59 UTC
Labels: duplicate
