### ISSUE TITLE
Error in if (stringsAsFactors) x <- factor(x) :    argument is not interpretable as logical

### ISSUE THREAD

**Issue by disha-mendhekar** [Rdatatable/data.table#4155] opened 2020-01-01 00:58 UTC
Up until yesterday, I never got this error from my shiny app. Here's my code. I appreciate any help! 

**Warning: Error in if: argument is not interpretable as logical
  54: as.data.frame.character
  52: data.frame
  49: server** 

**Error in if (stringsAsFactors) x <- factor(x) : 
  argument is not interpretable as logical**

latlongs<-reactiveValues()   
  latlongs$df2 <- data.frame(Longitude = numeric(0), Latitude = numeric(0))
  
  value<-reactiveValues()
  SpatialPolygonsDataFrame(SpatialPolygons(list()), data=data.frame (notes=character(0), stringsAsFactors = F))<-value$Poly

**Comment by jangorecki** [comment] 2020-01-01 05:06
Hi, thanks for report. Unfortunately with the tiny amount of details you provided we cannot help much. Actually how we could even know that problem is related to data.table? at the first glance it looks like a data.frame issue. I see you are using `stringsAsFactors = F`, if by any chance you defined a `F` variable in year code already (or you use `<<-` where LHS is a variable), then this is probably the cause of error. I suggest to always use `FALSE` instead of `F`.
I am closing this issue for now because there is nothing we can do. If you are able to provide your code, so we can at least know if it is a data.table problem and not data.frame, then I will re-open it. The more details you provide the more likely we will track down the problem, now there is not even a session info or data.table version...

**Closed by jangorecki** 2020-01-01 05:06 UTC

**Comment by aarora79** [comment] 2020-01-29 23:39
Stumbled upon this while debugging a similar issue with dplyr::arrange, not sure if your suggestion solved this issue or not but it did for me. I was using T for TRUE and while i was not using T/t as a variable name anywhere else in my code but moment i changed T to TRUE the error was gone. Thank you!

**Comment by MichaelChirico** [comment] 2020-01-30 03:50
FWIW the offending line listed in the original error is not even part of `data.table`'s source code, so it's really not clear the relevance to `data.table`. That line is from `base` (or perhaps elsewhere):

```
grep -Fnr "if(stringsAsFactors) x <- factor(x)" src/library/base/R -B 5 -A 5
rc/library/base/R/dataframe.R-294-## in case someone passes 'nm'
src/library/base/R/dataframe.R-295-as.data.frame.character <-
src/library/base/R/dataframe.R-296-    function(x, ..., stringsAsFactors = default.stringsAsFactors())
src/library/base/R/dataframe.R-297-{
src/library/base/R/dataframe.R-298-    nm <- deparse1(substitute(x))
src/library/base/R/dataframe.R:299:    if(stringsAsFactors) x <- factor(x)
src/library/base/R/dataframe.R-300-    if(!"nm" %in% names(list(...)))
src/library/base/R/dataframe.R-301-        as.data.frame.vector(x, ..., nm = nm)
src/library/base/R/dataframe.R-302-    else as.data.frame.vector(x, ...)
src/library/base/R/dataframe.R-303-}
src/library/base/R/dataframe.R-304-
```
