### ISSUE TITLE
Multi-index/pivot data.table, like pandas?

### ISSUE THREAD

**Issue by Pinto-P** [Rdatatable/data.table#3554] opened 2019-05-09 11:57 UTC
Hello.

I have been looking for some functionality like the multi-index dataframes that can be done in Pandas but, as it seems, not in R (at least with all its power). [Here](https://stackoverflow.com/questions/30944281/r-multi-index-on-columns-and-or-rows) is an example and the best (visual) solution I could find.

So, is there any intent of adding that in this library? It's something really useful with some kinds of data and I would like to use that with data.tables.

Thank you.

**Comment by jangorecki** [comment] 2019-05-09 12:08
Pandas name for that is quite confusing.
Data.table do have multiple columns indexes, on rows, not on columns. Anyway what pandas has behind the similar name is a hierarchy of columns. Data.table does not have such functionality, and I have never heard about such request. By design this kind of structure is far from what data.table is, a tabular data capable to handle any type of data as a column. It is not difficult to build such functionality around data.table, but it doesn't really bring much benefits, other than data representation, which is still better to do in knitr or other tools that works on presentation layer already. Hierarchies in data and metadata is quite deep subject, thus I think that simple wrapper using regex is preferred way.

**Comment by jangorecki** [comment] 2019-05-11 03:30
Closing as of now as "won't fix". If it will keep coming back we can consider providing some functionality like this.

**Closed by jangorecki** 2019-05-11 03:30 UTC
