### ISSUE TITLE
[R-Forge #2466] Treat is.object() j results as an object, not as a list

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#598] opened 2014-06-08 13:16 UTC
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2466&group_id=240&atid=978)

So that the list(list(...)) isn't needed here.   The result of lm() is classed, so it'd be better to return the whole object in a single cell, since it's an object. 

> DT = data.table(x=1:3,y=1:30,z=rnorm(30))
> ans = DT[,list(list(lm(z~y))), by=x]
> ans
>    x   V1
> 1: 1 <lm>
> 2: 2 <lm>
> 3: 3 <lm>
> ans[2,V1]
> [[1]]

Call:
lm(formula = z ~ y)

Coefficients:
(Intercept)            y  
    0.28289     -0.02831

**Comment by jangorecki** [comment] 2020-04-05 10:50
duplicate of #4326

**Closed by jangorecki** 2020-04-05 10:50 UTC
Labels: duplicate, feature request
