### ISSUE TITLE
[R-Forge #5289] .I should always reflect the original row local

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#539] opened 2014-06-08 13:15 UTC
Submitted by: Michele Carriero; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=5289&group_id=240&atid=978)

Please consider the following:

``` S
dt <- data.table(a=sample(letters, 100, T), b=rnorm(100))
dt[ a=="c", list(.N, .I)]
   N .I
1: 4  1
2: 4  2
3: 4  3
4: 4  4

dt[a=="c", list(.N, .I), by=a]
   a N .I
1: c 4 54
2: c 4 67
3: c 4 71
4: c 4 86
```

The first statement subsets the table first and then calculates locations. The second shows the original location of all rows having `a=="c"`. 

Unless there are reasons (which I'm currently missing) for which the above needs to happen, I think that both expressions should give the second result.

Regards,
Michele.

**Comment by jangorecki** [comment] 2020-04-05 12:41
closing as duplicate of #2598

**Closed by jangorecki** 2020-04-05 12:41 UTC
Labels: duplicate, feature request
