### ISSUE TITLE
tricky optimizations for indexes

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1174] opened 2015-06-08 21:53 UTC
Currently only `==`/`%in%` seems to be optimized for indexes. Also `max` and `which.max` (also for `min`) could be optimized. For consistency `max` returns biggest group on `max` of indexed column, while `which.max` returns scalar. Similarly to `mult` argument.
```r
library(data.table)
options("datatable.verbose"=TRUE)
DT <- data.table(a=1L)
set2key(DT,a)
# forder took 0 sec
DT[max(a)]
#    a
# 1: 1
DT[a==max(a)]
# Using existing index 'a'
# Starting bmerge ...done in 0 secs
#    a
# 1: 1
DT[which.max(a)]
#    a
# 1: 1
```

**Comment by franknarf1** [comment] 2015-06-09 12:55
I don't know how the internals work, but maybe the same could be done for `unique`?

    set.seed(1); DT <- data.table(a=sample(1:5,100,TRUE),b=rnorm(100),key="a")
    DT[J(setdiff(unique(a),1:3)),mean(b),by=.EACHI]
    #    a          V1
    # 1: 4 -0.11901369
    # 2: 5  0.09927857

**Comment by arunsrinivasan** [comment] 2015-07-18 23:28
duplicate of https://github.com/Rdatatable/data.table/issues/1068

**Closed by arunsrinivasan** 2015-07-18 23:28 UTC
Labels: feature request
