### ISSUE TITLE
print.data.table infinite loop when called from mlr3

### ISSUE THREAD

**Issue by tdhock** [Rdatatable/data.table#4396] opened 2020-04-24 21:13 UTC
Hi all, I think it has something to do with the new features of data table printing, so I'm tagging @TysonStanley @jangorecki @MichaelChirico who I saw working on that. 

I came across this issue while checking mlr3, which uses data tables. The code below works fine with CRAN versions of data.table+mlr3 but the issue below happens with CRAN mlr3-0.2.0 and current data.table master, which is why I am filing it here rather than in mlr3. However I'm tagging @mllg @berndbischl @jakob-r @pat-s from mlr3 since they may be interested and able to help.

The issue happens when runnining `example(BenchmarkResult, package="mlr3")` on the example line `print(bmr)` which is supposed to print the data table. Instead I get an infinite loop:

```
> example("BenchmarkResult", package="mlr3")

BnchmR> set.seed(123)

BnchmR> learners = list(
BnchmR+   lrn("classif.featureless", predict_type = "prob"),
BnchmR+   lrn("classif.rpart", predict_type = "prob")
BnchmR+ )

BnchmR> design = benchmark_grid(
BnchmR+   tasks = list(tsk("sonar"), tsk("spam")),
BnchmR+   learners = learners,
BnchmR+   resamplings = rsmp("cv", folds = 3)
BnchmR+ )

BnchmR> print(design)
                task                         learner         resampling
1: <TaskClassif[43]> <LearnerClassifFeatureless[32]> <ResamplingCV[19]>
2: <TaskClassif[43]>       <LearnerClassifRpart[32]> <ResamplingCV[19]>
3: <TaskClassif[43]> <LearnerClassifFeatureless[32]> <ResamplingCV[19]>
4: <TaskClassif[43]>       <LearnerClassifRpart[32]> <ResamplingCV[19]>

BnchmR> bmr = benchmark(design)
INFO  [13:59:34.153] Benchmark with 12 resampling iterations 
INFO  [13:59:34.211] Applying learner 'classif.featureless' on task 'sonar' (iter 1/3) 
INFO  [13:59:34.278] Applying learner 'classif.featureless' on task 'sonar' (iter 2/3) 
INFO  [13:59:34.304] Applying learner 'classif.featureless' on task 'sonar' (iter 3/3) 
INFO  [13:59:34.331] Applying learner 'classif.rpart' on task 'sonar' (iter 1/3) 
INFO  [13:59:34.622] Applying learner 'classif.rpart' on task 'sonar' (iter 2/3) 
INFO  [13:59:34.676] Applying learner 'classif.rpart' on task 'sonar' (iter 3/3) 
INFO  [13:59:34.735] Applying learner 'classif.featureless' on task 'spam' (iter 1/3) 
INFO  [13:59:34.764] Applying learner 'classif.featureless' on task 'spam' (iter 2/3) 
INFO  [13:59:34.793] Applying learner 'classif.featureless' on task 'spam' (iter 3/3) 
INFO  [13:59:34.824] Applying learner 'classif.rpart' on task 'spam' (iter 1/3) 
INFO  [13:59:34.981] Applying learner 'classif.rpart' on task 'spam' (iter 2/3) 
INFO  [13:59:35.134] Applying learner 'classif.rpart' on task 'spam' (iter 3/3) 
INFO  [13:59:35.312] Finished benchmark 

BnchmR> print(bmr)
Error: C stack usage  9524196 is too close to the limit
> traceback()
1697: match.fun(FUN)
1696: lapply(x, runlock)
1695: FUN(X[[i]], ...)
1694: lapply(x, runlock)
1693: FUN(X[[i]], ...)
1692: lapply(x, runlock)
.. (OUTPUT TRUNCATED BY tdhock FOR BREVITY)
15: FUN(X[[i]], ...)
14: lapply(x, runlock)
13: runlock(ans)
12: `[.data.table`(self$data, , list(nr = .GRP, iters = .N, resample_result = list(if (.N > 
        0L) ResampleResult$new(copy(.SD), uhash[1L]) else NULL)), 
        by = uhash)
11: self$data[, list(nr = .GRP, iters = .N, resample_result = list(if (.N > 
        0L) ResampleResult$new(copy(.SD), uhash[1L]) else NULL)), 
        by = uhash]
10: self$aggregate(measures = list(), conditions = TRUE)
9: remove_named(self$aggregate(measures = list(), conditions = TRUE), 
       c("uhash", "resample_result"))
8: .subset2(x, "print")(...)
7: print.R6(bmr)
6: print(bmr) at Rex35b63004e5f5#21
5: eval(ei, envir)
4: eval(ei, envir)
3: withVisible(eval(ei, envir))
2: source(tf, local, echo = echo, prompt.echo = paste0(prompt.prefix, 
       getOption("prompt")), continue.echo = paste0(prompt.prefix, 
       getOption("continue")), verbose = verbose, max.deparse.length = Inf, 
       encoding = "UTF-8", skip.echo = skips, keep.source = TRUE)
1: example("BenchmarkResult", package = "mlr3")
> devtools::session_info()
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       Ubuntu 18.04.4 LTS          
 system   x86_64, linux-gnu           
 ui       X11                         
 language en_US:en                    
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Phoenix             
 date     2020-04-24                  

─ Packages ───────────────────────────────────────────────────────────────────
 package     * version date       lib source                                
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.2)                        
 backports     1.1.6   2020-04-05 [1] CRAN (R 3.6.3)                        
 callr         3.4.3   2020-03-28 [1] CRAN (R 3.6.2)                        
 checkmate     2.0.0   2020-02-06 [1] CRAN (R 3.6.3)                        
 cli           2.0.2   2020-02-28 [1] CRAN (R 3.6.2)                        
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.2)                        
 curl          4.3     2019-12-02 [1] CRAN (R 3.6.2)                        
 data.table    1.12.9  2020-04-24 [1] Github (rdatatable/data.table@dd7609e)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.2)                        
 devtools      2.3.0   2020-04-10 [1] CRAN (R 3.6.3)                        
 digest        0.6.25  2020-02-23 [1] CRAN (R 3.6.2)                        
 ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.2)                        
 fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.2)                        
 fs            1.4.1   2020-04-04 [1] CRAN (R 3.6.3)                        
 glue          1.4.0   2020-04-03 [1] CRAN (R 3.6.3)                        
 lgr           0.3.4   2020-03-20 [1] CRAN (R 3.6.3)                        
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.2)                        
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.2)                        
 mlr3        * 0.2.0   2020-04-17 [1] CRAN (R 3.6.3)                        
 mlr3misc      0.2.0   2020-04-15 [1] CRAN (R 3.6.3)                        
 paradox       0.2.0   2020-04-15 [1] CRAN (R 3.6.3)                        
 pkgbuild      1.0.6   2019-10-09 [1] CRAN (R 3.6.2)                        
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.2)                        
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 3.6.2)                        
 processx      3.4.2   2020-02-09 [1] CRAN (R 3.6.2)                        
 ps            1.3.2   2020-02-13 [1] CRAN (R 3.6.2)                        
 R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.2)                        
 remotes       2.1.1   2020-02-15 [1] CRAN (R 3.6.3)                        
 rlang         0.4.5   2020-03-01 [1] CRAN (R 3.6.2)                        
 rpart         4.1-15  2019-04-12 [1] CRAN (R 3.6.3)                        
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.2)                        
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.2)                        
 testthat      2.3.2   2020-03-02 [1] CRAN (R 3.6.3)                        
 usethis       1.6.0   2020-04-09 [1] CRAN (R 3.6.3)                        
 uuid          0.1-4   2020-02-26 [1] CRAN (R 3.6.3)                        
 withr         2.2.0   2020-04-20 [1] CRAN (R 3.6.3)                        

[1] /home/tdhock/lib/R/library
> 
```

Below I show the desired output, using mlr3 and data.table from CRAN.

```
(base) tdhock@maude-MacBookPro:~/R/mlr3/R$ R --vanilla -e 'example("BenchmarkResult", package="mlr3");devtools::session_info()'

R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> example("BenchmarkResult", package="mlr3");devtools::session_info()

BnchmR> set.seed(123)

BnchmR> learners = list(
BnchmR+   lrn("classif.featureless", predict_type = "prob"),
BnchmR+   lrn("classif.rpart", predict_type = "prob")
BnchmR+ )

BnchmR> design = benchmark_grid(
BnchmR+   tasks = list(tsk("sonar"), tsk("spam")),
BnchmR+   learners = learners,
BnchmR+   resamplings = rsmp("cv", folds = 3)
BnchmR+ )

BnchmR> print(design)
            task                     learner     resampling
1: <TaskClassif> <LearnerClassifFeatureless> <ResamplingCV>
2: <TaskClassif>       <LearnerClassifRpart> <ResamplingCV>
3: <TaskClassif> <LearnerClassifFeatureless> <ResamplingCV>
4: <TaskClassif>       <LearnerClassifRpart> <ResamplingCV>

BnchmR> bmr = benchmark(design)
INFO  [14:11:44.631] Benchmark with 12 resampling iterations 
INFO  [14:11:44.716] Applying learner 'classif.featureless' on task 'sonar' (iter 1/3) 
INFO  [14:11:44.787] Applying learner 'classif.featureless' on task 'sonar' (iter 2/3) 
INFO  [14:11:44.815] Applying learner 'classif.featureless' on task 'sonar' (iter 3/3) 
INFO  [14:11:44.839] Applying learner 'classif.rpart' on task 'sonar' (iter 1/3) 
INFO  [14:11:44.947] Applying learner 'classif.rpart' on task 'sonar' (iter 2/3) 
INFO  [14:11:45.036] Applying learner 'classif.rpart' on task 'sonar' (iter 3/3) 
INFO  [14:11:45.115] Applying learner 'classif.featureless' on task 'spam' (iter 1/3) 
INFO  [14:11:45.146] Applying learner 'classif.featureless' on task 'spam' (iter 2/3) 
INFO  [14:11:45.196] Applying learner 'classif.featureless' on task 'spam' (iter 3/3) 
INFO  [14:11:45.232] Applying learner 'classif.rpart' on task 'spam' (iter 1/3) 
INFO  [14:11:45.405] Applying learner 'classif.rpart' on task 'spam' (iter 2/3) 
INFO  [14:11:45.576] Applying learner 'classif.rpart' on task 'spam' (iter 3/3) 
INFO  [14:11:45.777] Finished benchmark 

BnchmR> print(bmr)
<BenchmarkResult> of 12 rows with 4 resampling runs
 nr task_id          learner_id resampling_id iters warnings errors
  1   sonar classif.featureless            cv     3        0      0
  2   sonar       classif.rpart            cv     3        0      0
  3    spam classif.featureless            cv     3        0      0
  4    spam       classif.rpart            cv     3        0      0

BnchmR> bmr$tasks
          task_hash task_id          task
1: dea3e1fd99a2120d   sonar <TaskClassif>
2: 7cf4341432d6352e    spam <TaskClassif>

BnchmR> bmr$learners
       learner_hash          learner_id                     learner
1: 3bbabd1058707305 classif.featureless <LearnerClassifFeatureless>
2: fc402e71eadd46bb       classif.rpart       <LearnerClassifRpart>

BnchmR> # first 5 individual resamplings
BnchmR> head(as.data.table(bmr, measures = c("classif.acc", "classif.auc")), 5)
                                  uhash          task
1: daed045d-4cfb-47f4-b97b-d639912d559c <TaskClassif>
2: daed045d-4cfb-47f4-b97b-d639912d559c <TaskClassif>
3: daed045d-4cfb-47f4-b97b-d639912d559c <TaskClassif>
4: fefe55e8-80d4-44b1-ab1f-c7eb6e613e66 <TaskClassif>
5: fefe55e8-80d4-44b1-ab1f-c7eb6e613e66 <TaskClassif>
                       learner     resampling iteration prediction
1: <LearnerClassifFeatureless> <ResamplingCV>         1     <list>
2: <LearnerClassifFeatureless> <ResamplingCV>         2     <list>
3: <LearnerClassifFeatureless> <ResamplingCV>         3     <list>
4:       <LearnerClassifRpart> <ResamplingCV>         1     <list>
5:       <LearnerClassifRpart> <ResamplingCV>         2     <list>

BnchmR> # aggregate results
BnchmR> bmr$aggregate()
   nr  resample_result task_id          learner_id resampling_id iters
1:  1 <ResampleResult>   sonar classif.featureless            cv     3
2:  2 <ResampleResult>   sonar       classif.rpart            cv     3
3:  3 <ResampleResult>    spam classif.featureless            cv     3
4:  4 <ResampleResult>    spam       classif.rpart            cv     3
   classif.ce
1:  0.4660455
2:  0.2739130
3:  0.3940399
4:  0.1086721

BnchmR> # aggregate results with hyperparameters as separate columns
BnchmR> mlr3misc::unnest(bmr$aggregate(params = TRUE), "params")
   nr  resample_result task_id          learner_id resampling_id iters
1:  1 <ResampleResult>   sonar classif.featureless            cv     3
2:  2 <ResampleResult>   sonar       classif.rpart            cv     3
3:  3 <ResampleResult>    spam classif.featureless            cv     3
4:  4 <ResampleResult>    spam       classif.rpart            cv     3
   classif.ce method xval
1:  0.4660455   mode   NA
2:  0.2739130   <NA>    0
3:  0.3940399   mode   NA
4:  0.1086721   <NA>    0

BnchmR> # extract resample result for classif.rpart
BnchmR> rr = bmr$aggregate()[learner_id == "classif.rpart", resample_result][[1]]

BnchmR> print(rr)
<ResampleResult> of 3 iterations
* Task: sonar
* Learner: classif.rpart
* Warnings: 0 in 0 iterations
* Errors: 0 in 0 iterations

BnchmR> # access the confusion matrix of the first resampling iteration
BnchmR> rr$predictions()[[1]]$confusion
        truth
response  M  R
       M 30 18
       R  3 19
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       Ubuntu 18.04.4 LTS          
 system   x86_64, linux-gnu           
 ui       X11                         
 language en_US:en                    
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Phoenix             
 date     2020-04-24                  

─ Packages ───────────────────────────────────────────────────────────────────
 package      * version date       lib source        
 assertthat     0.2.1   2019-03-21 [1] CRAN (R 3.6.2)
 backports      1.1.6   2020-04-05 [1] CRAN (R 3.6.3)
 callr          3.4.3   2020-03-28 [1] CRAN (R 3.6.2)
 checkmate      2.0.0   2020-02-06 [1] CRAN (R 3.6.3)
 cli            2.0.2   2020-02-28 [1] CRAN (R 3.6.2)
 crayon         1.3.4   2017-09-16 [1] CRAN (R 3.6.2)
 data.table     1.12.8  2019-12-09 [1] CRAN (R 3.6.3)
 desc           1.2.0   2018-05-01 [1] CRAN (R 3.6.2)
 devtools       2.3.0   2020-04-10 [1] CRAN (R 3.6.3)
 digest         0.6.25  2020-02-23 [1] CRAN (R 3.6.2)
 ellipsis       0.3.0   2019-09-20 [1] CRAN (R 3.6.2)
 fansi          0.4.1   2020-01-08 [1] CRAN (R 3.6.2)
 fs             1.4.1   2020-04-04 [1] CRAN (R 3.6.3)
 glue           1.4.0   2020-04-03 [1] CRAN (R 3.6.3)
 lgr            0.3.4   2020-03-20 [1] CRAN (R 3.6.3)
 magrittr       1.5     2014-11-22 [1] CRAN (R 3.6.2)
 memoise        1.1.0   2017-04-21 [1] CRAN (R 3.6.2)
 mlr3         * 0.2.0   2020-04-17 [1] CRAN (R 3.6.3)
 mlr3measures   0.1.3   2020-04-01 [1] CRAN (R 3.6.3)
 mlr3misc       0.2.0   2020-04-15 [1] CRAN (R 3.6.3)
 paradox        0.2.0   2020-04-15 [1] CRAN (R 3.6.3)
 pkgbuild       1.0.6   2019-10-09 [1] CRAN (R 3.6.2)
 pkgload        1.0.2   2018-10-29 [1] CRAN (R 3.6.2)
 prettyunits    1.1.1   2020-01-24 [1] CRAN (R 3.6.2)
 processx       3.4.2   2020-02-09 [1] CRAN (R 3.6.2)
 ps             1.3.2   2020-02-13 [1] CRAN (R 3.6.2)
 R6             2.4.1   2019-11-12 [1] CRAN (R 3.6.2)
 remotes        2.1.1   2020-02-15 [1] CRAN (R 3.6.3)
 rlang          0.4.5   2020-03-01 [1] CRAN (R 3.6.2)
 rpart          4.1-15  2019-04-12 [1] CRAN (R 3.6.3)
 rprojroot      1.3-2   2018-01-03 [1] CRAN (R 3.6.2)
 sessioninfo    1.1.1   2018-11-05 [1] CRAN (R 3.6.2)
 testthat       2.3.2   2020-03-02 [1] CRAN (R 3.6.3)
 usethis        1.6.0   2020-04-09 [1] CRAN (R 3.6.3)
 uuid           0.1-4   2020-02-26 [1] CRAN (R 3.6.3)
 withr          2.2.0   2020-04-20 [1] CRAN (R 3.6.3)

[1] /home/tdhock/lib/R/library
> 
> 
(base) tdhock@maude-MacBookPro:~/R/mlr3/R$ 
```

**Comment by MichaelChirico** [comment] 2020-04-25 16:37
The `traceback()` gives away the source of the recursion:

```
15: lapply(x, runlock)
14: FUN(X[[i]], ...)
13: lapply(x, runlock)
12: FUN(X[[i]], ...)
11: lapply(x, runlock)
10: FUN(X[[i]], ...)
9: lapply(x, runlock)
8: runlock(ans)
7: `[.data.table`(self$data, , list(nr = .GRP, iters = .N, resample_result = list(if (.N > 
       0L) ResampleResult$new(copy(.SD), uhash[1L]) else NULL)), 
       by = uhash)
6: self$data[, list(nr = .GRP, iters = .N, resample_result = list(if (.N > 
       0L) ResampleResult$new(copy(.SD), uhash[1L]) else NULL)), 
       by = uhash]
5: self$aggregate(measures = list(), conditions = TRUE)
4: remove_named(self$aggregate(measures = list(), conditions = TRUE), 
       c("uhash", "resample_result"))
3: .subset2(x, "print")(...)
2: print.R6(bmr)
1: print(bmr)
```

**Comment by MichaelChirico** [comment] 2020-04-26 09:40
Duplicate of #4173 

Fix is ready here: https://github.com/Rdatatable/data.table/pull/4183

**Comment by pat-s** [comment] 2020-08-26 14:27
@tdhock Seems this is fixed. Close here?

**Closed** 2021-08-13 19:49 UTC
Labels: duplicate

**Comment by berndbischl** [comment] 2021-08-13 19:51
thanks a lot from our side 
@mllg
