### ISSUE TITLE
set function crashes the R session

### ISSUE THREAD

**Issue by clerousset** [Rdatatable/data.table#4824] opened 2020-11-30 16:55 UTC
A very bad usage of `set` leads to the systematic crash of the Rsession. 

`#` `minimal reproductible example` :
```
library(data.table)
n<-1e6
dt<-
  data.table(
    fact=factor(rep("A",n)),
    case=rep(TRUE,n),
    coeff=rep(5,n))
x<-"fact"
 set(
    dt,
    i= which(dt$case==TRUE),
    j= "fact",
    value=dt[(case),..x]*dt$coeff
    )
```
For the crash to happen :
- n should be big (n=1e4 : no crash, n=1e5 : crash)
- `dt$fact` needs to be a `factor`
- argument `i` needs to be used in `set`
- argument `j` needs to be exactly "fact" (needs to overwrite column "fact")
- one should use `..x` and not "fact" in `dt[(case),..x]`

`#` `Output of sessionInfo()`
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)Matrix products: defaultlocale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252
[3] LC_MONETARY=French_France.1252 LC_NUMERIC=C
[5] LC_TIME=French_France.1252attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   baseother attached packages:
[1] data.table_1.13.0loaded via a namespace (and not attached):
[1] compiler_4.0.0 tools_4.0.0

**Comment by jangorecki** [comment] 2020-11-30 17:08
Thank you for reporting, are you able to reproduce it on recent version?
On Linux and recent devel I am not having a crash, yet result is corrupted object, so needs some fix anyway.
```r
library(data.table)
n<-1e6
dt<-
  data.table(
    fact=factor(rep("A",n)),
    case=rep(TRUE,n),
    coeff=rep(5,n))
x<-"fact"
 set(
    dt,
    i= which(dt$case==TRUE),
    j= "fact",
    value=dt[(case),..x]*dt$coeff
    )
#Warning message:
#In Ops.factor(left, right) : '*' not meaningful for factors
dt
#Error in as.character.factor(x) : malformed factor
```

**Comment by shrektan** [comment] 2020-11-30 17:38
I can reproduce the crash on Windows 10 with the dev version of data.table.  A simple repro could be this:

```r
library(data.table)
n <- 1e6
dt <- data.table(fact = rep(1.0, n))
x <- "fact"
set(dt,
    i = seq_len(1e5),
    j = "fact",
    value = rep(NA, 1e5))
```

The root cause, IMHO, is that the logical value `NA` was assigned to the numeric vector (factor vectors are in double), which should be coerced to the numeric NA_REAL first.

**Comment by jangorecki** [comment] 2020-11-30 20:28
Thanks for simplifying example. Factor is int not double.
```r
str(unclass(factor("a")))
# int 1
# - attr(*, "levels")= chr "a"
```

**Closed** 2021-05-07 08:08 UTC
Labels: bug, segfault
