### ISSUE TITLE
Invalid .internal.selfref detected when assigning multiple columns with `:=` after using dplyr::setdiff()

### ISSUE THREAD

**Issue by aaron-oz** [Rdatatable/data.table#6657] opened 2024-12-11 19:58 UTC
`#` [`Minimal reproducible example`](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example); please be sure to set `verbose=TRUE` where possible!

```
full.dt <- data.table(x = 1:10, y = 11:20)
sub.dt <- data.table(x = seq(1, 10, by = 2), y = seq(11, 20, by = 2))
diff.dt <- dplyr::setdiff(full.dt, sub.dt)
diff.dt

       x     y
   <num> <num>
1:     2    12
2:     4    14
3:     6    16
4:     8    18
5:    10    20

diff.dt[, `:=` (a = 'a', b = 'b')]

Warning message:
In `[.data.table`(diff.dt, , `:=`(a = "a", b = "b")) :
  Invalid .internal.selfref detected and fixed by taking a (shallow) copy of the data.table 
so that := can add this new column by reference. At an earlier point, this data.table has 
been copied by R (or was created manually using structure() or similar). Avoid 
names<- and attr<- which in R currently (and oddly) may copy the whole data.table. 
Use set* syntax instead to avoid copying: ?set, ?setnames and ?setattr. If this message 
doesn't help, please report your use case to the data.table issue tracker so the root 
cause can be fixed or this message improved.

diff.dt

       x     y      a      b
   <num> <num> <char> <char>
1:     2    12      a      b
2:     4    14      a      b
3:     6    16      a      b
4:     8    18      a      b
5:    10    20      a      b
```

`#` `Output of sessionInfo()`

```
R version 4.4.1 (2024-06-14)
Platform: x86_64-redhat-linux-gnu
Running under: Red Hat Enterprise Linux 9.4 (Plow)

Matrix products: default
BLAS/LAPACK: FlexiBLAS OPENBLAS-OPENMP;  LAPACK version 3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/New_York
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.16.4  dplyr_1.1.4        Seurat_5.1.0       SeuratObject_5.0.2
[5] sp_2.1-4           Matrix_1.7-1       reshape2_1.4.4     ggplot2_3.5.1     

loaded via a namespace (and not attached):
  [1] deldir_2.0-4           pbapply_1.7-2          gridExtra_2.3         
  [4] rlang_1.1.4            magrittr_2.0.3         RcppAnnoy_0.0.22      
  [7] matrixStats_1.4.1      ggridges_0.5.6         compiler_4.4.1        
 [10] spatstat.geom_3.3-3    png_0.1-8              vctrs_0.6.5           
 [13] stringr_1.5.1          pkgconfig_2.0.3        fastmap_1.2.0         
 [16] utf8_1.2.4             promises_1.3.0         purrr_1.0.2           
 [19] jsonlite_1.8.9         goftest_1.2-3          later_1.3.2           
 [22] spatstat.utils_3.1-0   irlba_2.3.5.1          parallel_4.4.1        
 [25] cluster_2.1.6          R6_2.5.1               ica_1.0-3             
 [28] stringi_1.8.4          RColorBrewer_1.1-3     spatstat.data_3.1-2   
 [31] reticulate_1.39.0      parallelly_1.38.0      spatstat.univar_3.0-1 
 [34] lmtest_0.9-40          scattermore_1.2        Rcpp_1.0.13-1         
 [37] tensor_1.5             future.apply_1.11.3    zoo_1.8-12            
 [40] sctransform_0.4.1      httpuv_1.6.15          splines_4.4.1         
 [43] igraph_2.1.1           tidyselect_1.2.1       abind_1.4-8           
 [46] spatstat.random_3.3-2  codetools_0.2-20       miniUI_0.1.1.1        
 [49] spatstat.explore_3.3-3 listenv_0.9.1          lattice_0.22-6        
 [52] tibble_3.2.1           plyr_1.8.9             shiny_1.9.1           
 [55] withr_3.0.1            ROCR_1.0-11            Rtsne_0.17            
 [58] future_1.34.0          fastDummies_1.7.4      survival_3.6-4        
 [61] polyclip_1.10-7        fitdistrplus_1.2-1     pillar_1.9.0          
 [64] KernSmooth_2.23-24     plotly_4.10.4          generics_0.1.3        
 [67] RcppHNSW_0.6.0         munsell_0.5.1          scales_1.3.0          
 [70] globals_0.16.3         xtable_1.8-4           glue_1.8.0            
 [73] lazyeval_0.2.2         tools_4.4.1            RSpectra_0.16-2       
 [76] RANN_2.6.2             leiden_0.4.3.1         dotCall64_1.2         
 [79] cowplot_1.1.3          grid_4.4.1             tidyr_1.3.1           
 [82] colorspace_2.1-1       nlme_3.1-164           patchwork_1.3.0       
 [85] cli_3.6.3              spatstat.sparse_3.1-0  spam_2.11-0           
 [88] fansi_1.0.6            viridisLite_0.4.2      uwot_0.2.2            
 [91] gtable_0.3.5           digest_0.6.37          progressr_0.14.0      
 [94] ggrepel_0.9.6          htmlwidgets_1.6.4      farver_2.1.2          
 [97] htmltools_0.5.8.1      lifecycle_1.0.4        httr_1.4.7            
[100] mime_0.12              MASS_7.3-60.2         
```

**Comment by ecoRoland2** [comment] 2024-12-12 06:06
@aaron-oz Could you please elaborate on what you see as the issue here? As far as I can see, everything works as intended and the warning is correct. I assume `dplyr:::setdiff.data.frame` does exactly what the warning says by the internal call to `dplyr_reconstruct`.

**Comment by aaron-oz** [comment] 2024-12-13 20:15
@ecoRoland2 I think you're correct. I had interpreted  "Use set* syntax instead to avoid copying" as pertaining to `setdiff()` too (somehow 'set'ting the difference between two data frames), but the second half of that sentence makes is clearer that the suggestion relates specifically to "?set, ?setnames and ?setattr".

**Comment by ben-schwen** [comment] 2024-12-15 21:11
Offtopic: While `setdiff` looks like a `set*` operation it also has a different semantic meaning of performing set operations (like union, intersection, difference) while `set*` operations in `data.table` like `setnames` are true setter functions.

I'll close this here since, as Roland pointed out, everything works as intended.

**Closed by ben-schwen** 2024-12-15 21:11 UTC

**Comment by MichaelChirico** [comment] 2024-12-20 06:40
I agree the warning is WAI here. Here are some alternatives to avoid the warning:

#### Explicitly copy the {dplyr} result

```r
diff.dt = copy(dplyr::setdiff(full.dt, sub.dt))
```

#### Use `fsetdiff()` instead

```r
diff.dt = fsetdiff(full.dt, sub.dt)
```

#### Use a "native" anti-join instead

```r
diff.dt = full.dt[!sub.dt, on=.NATURAL]
```

`on=.NATURAL` can be dropped if `full.dt` is keyed (`setkey(full.dt); full.dt[!sub.dt]`), or we can use `on=names(sub.dt)`.
