### ISSUE TITLE
unique and na.omit

### ISSUE THREAD

**Issue by ywhuofu** [Rdatatable/data.table#1774] opened 2016-07-16 04:32 UTC
I think it can be improving if we make the syntax consistent between `unique` and `na.omit` when choosing the columns. 

 `unique(dt, by=c('var'))` and `na.omit(dt, col=c('var'))`

why not   `na.omit(dt, by=c('var'))`

**Comment by jangorecki** [comment] 2016-07-16 11:42
duplicate of #1283

**Closed by jangorecki** 2016-07-16 11:42 UTC
