### ISSUE TITLE
Logo for data.table

### ISSUE THREAD

**Issue by gaborcsardi** [Rdatatable/data.table#1237] opened 2015-07-21 18:21 UTC
I think data.table deserves a nice logo. E.g. a sea-lion saying arr-arr. ;-)

**Comment by mattdowle** [comment] 2015-07-21 19:19
+1  :-)

**Comment by shrektan** [comment] 2015-07-22 00:29
+ 1 


Its such an amazing work, masterpiece.  Love you guys. 


发自网易邮箱大师
在2015年07月22日 03:19，Matt Dowle 写道:

+1 :-)

**Comment by rsaporta** [comment] 2015-07-22 01:14
Aggreeeed!   something involving `:=` perhaps?   Except, out of context, that looks too much like an emoticon

**Comment by jangorecki** [comment] 2015-07-22 08:11
@rsaporta I combined `:=` together with `[` and made something like.
![dt](https://cloud.githubusercontent.com/assets/3627377/8820906/3aad1d88-3051-11e5-816f-aedcb98e82a8.png)
I'm not graphic skilled person so don't count on me for real logo.

**Comment by DavidArenburg** [comment] 2015-07-22 08:26
@jangorecki at least you tried...

**Comment by mattdowle** [comment] 2015-07-24 05:56
How about something like this : 
![selection_001](https://cloud.githubusercontent.com/assets/2779998/8868426/1b43c900-318d-11e5-9577-91ec6b99973d.png)

More here:  http://www.shutterstock.com/pic-182509166/stock-photo-icon-button-pictogram-with-seal-symbol.html?src=xhzr-JIlHZwlPyvxdd1dzQ-1-0

**Comment by DavidArenburg** [comment] 2015-07-24 10:28
How is it `data.table` related? It's actually make an impressions of slowness to me...

**Comment by mattdowle** [comment] 2015-07-24 20:06
Good feedback.  Sea lion just R related - they say R R.  Ok needs to be a fast sea lion.  Not sure it needs to make perfect sense - it's just a logo.   Look at GitHub's for example ... what's a cat got to do with github? But Twitter's on the other makes sense.

**Comment by eantonya** [comment] 2015-07-24 20:49
http://www.quora.com/GitHub/What-is-the-story-behind-GitHub%E2%80%99s-octocat-mascot

**Comment by gaborcsardi** [comment] 2015-08-13 15:28
Here is a try.

![data table](https://cloud.githubusercontent.com/assets/660288/9253796/d703401e-41ad-11e5-815d-ccdc3261bfef.png)

Points are:
* it is a table, obviously
* it is not a regular table (i.e. data frame), being ragged a bit
* the sea lion says: R
* has the h2o yellow

I am not entirely satisfied with it, e.g. a better font could help. Ideas welcome.

**Comment by shrektan** [comment] 2015-08-13 15:40
@gaborcsardi nice try!

**Comment by swihart** [comment] 2015-08-13 15:52
@gaborcsardi Very creative!    Just for my own edification:  Are we allowed to incorporate the official R logo?

**Comment by gaborcsardi** [comment] 2015-08-13 15:56
@swihart 

`:=` is a great idea, I just forgot that! I am not sure where to put it with my design, but it is definitely something that could be in the logo.

As for the R logo, probably, but we would need to ask, because it is a trade mark. There is a new R logo, actually, but they haven't published it yet, they are working out the terms for its usage.

**Comment by jangorecki** [comment] 2015-08-13 17:10
@gaborcsardi very nice, just putting brackets on the image:
![d703401e-41ad-11e5-815d-ccdc3261bfef](https://cloud.githubusercontent.com/assets/3627377/9256234/52561772-41e6-11e5-870d-a34405c0e693.png)
But I don't have any nice idea to put `:=` there

**Comment by gaborcsardi** [comment] 2015-08-13 17:26
@jangorecki brackets are a great idea, I'll add them.

**Comment by swihart** [comment] 2015-08-13 17:26
What about a small multiple / or tiled approach for ":=".  Would it be too overloaded to put ":=" in the bottom corner of each square?  Or faded, centered in the background of each square (in the color of the adjacent square)?  

If the brackets on the outside are too overwhelming, the symbol "[:=]" could be tiled as described above.

FWIW.

**Comment by swihart** [comment] 2015-08-13 17:31
Or, as a classy chain around the sea lion's neck, with the medallion "[ , := , ]".

Or a classy tattoo.  Or on the chest like a Superman logo?

**Comment by swihart** [comment] 2015-08-13 17:33
In all seriousness, if the tiled idea doesn't work, what about doing 1 big faded `:=`...  The dots could between the a and t of data and the a and b of table and the bars could go across the ta of data and the bl of table...all faded in the background.  Sorry to just be throwing ideas out and not crafting it myself -- I'm not too talented in this area.

**Comment by gaborcsardi** [comment] 2015-08-13 17:42
@swihart Yeah, I guess tiled squares or faded := in the background is probably a little too much. I think these brackets are a bit heavy, but some lighter ones might work.

I was also thinking about having the sea lion balance the dot on its nose....

**Comment by swihart** [comment] 2015-08-13 17:49
@gaborcsardi That's clever.  Could be a ball/sphere with the `:=`.  Or the `:=` itself.

Just brainstorming.

**Comment by tdeenes** [comment] 2015-08-13 18:26
Here is a simplified version without the sea lion (although I am not against it - .
![datatable_logo](https://cloud.githubusercontent.com/assets/7604321/9257892/99070570-41f8-11e5-9872-df603ea25d79.png)

**Comment by daroczig** [comment] 2015-08-19 07:18
@swihart, I think (and might be totally wrong but) the closing bracket is not needed, a simple logo like this would fit the trending minimalist designs: `[:=`

As I wanted to see how it would like, I spend a few minutes in Gimp -- please forgive me this try:

![dt](https://cloud.githubusercontent.com/assets/495736/9350572/e5595d44-4606-11e5-9733-7f57a2792372.png)

Probably these are less frustrating: 

![dt-fonts](https://cloud.githubusercontent.com/assets/495736/9350691/a6bdc952-4607-11e5-82bc-1b1c1a6fa8b0.jpg)

**Comment by romunov** [comment] 2015-08-19 07:46
I like the second "minimalistic" one. I wouldn't bother by cramming R in there.

**Comment by swihart** [comment] 2015-08-19 21:15
![slide10](https://cloud.githubusercontent.com/assets/4581196/9368927/33e1e7fa-4694-11e5-9e7d-90e15ce53254.jpg)

  *  `:=` ?  Check.
  *  At least `[` ?  Check.
  *  Bonus `]` ?  Check.
  *  `data` ?  Check.
  *  `table` ?  Check.
  *  monospace font ?  Check.
  *  `sealion` that says `R`?  Check.
  *  Implied h2o yellow ?  Check.

Excuse the alignment(s).  And colors.  I thought this idea was simple enough (similar to the idea of @jangorecki).  The image of the sea lion is not the one I wish to use; but I remember @DavidArenburg mentioning that a sea lion might evoke slowness -- I imagine because they are fumblers on land.  But they are quick in water.  And yet, we can't hear them "R, R!" underwater.  So, the head needs to be poking up so we can hear it say "R, R!"  That's why I chose this image, to demonstrate the sea lion in the water, able to say the sound that got him recruited in the first place.  And possibly that the sea lion is balancing the whole thing on its nose.

**Comment by swihart** [comment] 2015-08-19 21:27
![cropped_slide12](https://cloud.githubusercontent.com/assets/4581196/9369481/77ffb252-4697-11e5-9ee7-24115fd0a5cf.png)

Or crop the bottom space and get the sea lion into the brackets.

**Comment by daroczig** [comment] 2015-08-19 21:34
Thanks a lot for the feedback, @romunov, I also like the minimalistic approach better.
Actually, I can imagine the following image as a sea lion. Or two guys checking what's inside of the bracket:

![sealion-r](https://cloud.githubusercontent.com/assets/495736/9369454/0f2a2b72-467e-11e5-850c-34d47885c365.jpg)

And another alternative for the face of a sea lion with all the main chars from `data.table`:

![img_20150819_143202-2](https://cloud.githubusercontent.com/assets/495736/9369624/52219568-467f-11e5-879e-eb41a5c2108e.jpg)

**Comment by szilard** [comment] 2015-08-19 21:53
Just slightly related, but sneak-peek from slides from my coming talk at the Budapest R meetup
http://www.meetup.com/Budapest-Users-of-R-Network/events/222568658/ - maybe it can be incorporated in some form:
<img width="546" alt="screen shot 2015-08-19 at 11 49 23 pm" src="https://cloud.githubusercontent.com/assets/844827/9369987/431c04e2-46cd-11e5-9a68-f94679cde9d3.png">

**Comment by leeper** [comment] 2015-08-19 22:11
Something minimalist:

![table](https://cloud.githubusercontent.com/assets/3505428/9370365/594bcf50-4695-11e5-9f40-cecc3b498d73.png)

**Comment by mattdowle** [comment] 2015-08-20 02:28
Didn't realise there was so much creativity out there!  Awesome.  I like the yellow sealion (he or she looks content) and all the ways of getting [ and := in there too.  Another requirement may be that it needs to be small enough to look good as an icon only on the Chrome toolbar; e.g. part of my toolbar looks like this : 
![selection_001](https://cloud.githubusercontent.com/assets/2779998/9374083/4c72944c-46a6-11e5-9611-9d1401854c12.png)
Then it's easier to add to slide footers etc.  But we could have a big icon and also a smaller version, too.
On the sealion usage, I happened on this 1996 quote from Linus Torvalds : 
"  Some people have told me they don’t think a fat penguin really embodies the grace of Linux, which just tells me they have never seen an angry penguin charging at them in excess of 100mph. They’d be a lot more careful about what they say if they had. "

**Comment by petermeissner** [comment] 2015-08-20 07:26
+1 for leeper's (maybe with tdeenes' colors)
+1 for daroczig minimal number 5

**Comment by tdeenes** [comment] 2015-08-20 12:09
+1 for leeper

Here is an other idea (a speedy see-cow :)
![logo2](https://cloud.githubusercontent.com/assets/7604321/9382918/054ed11c-4745-11e5-8fdc-9a5f92c0eacb.png)

**Comment by tdeenes** [comment] 2015-08-20 12:10
The same in a less 'threatening' colour + a nose:
![logo3](https://cloud.githubusercontent.com/assets/7604321/9382929/264602a0-4745-11e5-9005-03d7179b9b2c.png)

**Comment by romunov** [comment] 2015-08-20 12:13
+1 to @leeper's design. Great for icons and tshirts at the same time.

**Comment by mrdwab** [comment] 2015-08-20 16:05
I like @leeper's "table" too, but the straight legs as a substitute for square brackets don't quite work.

**Comment by leeper** [comment] 2015-08-21 00:56
I made my design in about 5min in MS Paint and don't really have time to do anything further with it. Consider it CC0. Anyone can modify as they see fit.

**Comment by mattdowle** [comment] 2015-08-22 00:01
![dtlogo](https://cloud.githubusercontent.com/assets/2779998/9421299/b36663b0-4825-11e5-801e-aebc7da4c3e5.png)

**Comment by gaborcsardi** [comment] 2015-08-22 01:47
I think this is getting quite good. Personally I would like the top a little less heavy, e.g. how about a light table pattern? It also needs a nice strong font for the bigger version of the logo. :)

**Comment by swihart** [comment] 2015-08-22 14:04
@mattdowle nice update to @leeper !  We're getting there!  @gaborcsardi -- do you think the table needs to be lighter or just tilted more so less area appears?  The uniform color adds to the minimalism, in my opinion.

**Comment by DavidArenburg** [comment] 2015-08-24 10:48
I think we are lacking some style here... We could take some ideas from [these guys](https://www.stickermule.com/user/1070448958/stickers) maybe \hides

**Comment by ajzz** [comment] 2015-08-26 01:57
Because @daroczig asked me to:
![image](https://cloud.githubusercontent.com/assets/3092439/9483979/eacc2b2c-4b5a-11e5-81f5-b71257e51f56.png)

**Comment by daroczig** [comment] 2015-08-26 04:15
I cannot draw shiny hexagons, so I kept thinking about a minimalistic/flat design based on @ajzz's color scheme and my previous examples:

![data table](https://cloud.githubusercontent.com/assets/495736/9485261/cfca802e-4b6b-11e5-8096-ede50cb893d9.gif)

![data table2](https://cloud.githubusercontent.com/assets/495736/9485291/29907f32-4b6c-11e5-9644-55a6f24e164e.gif)

![data table3](https://cloud.githubusercontent.com/assets/495736/9485313/87d49f24-4b6c-11e5-81f5-5970a7fd8e73.gif)

Although the @leeper & @mattdowle way seems to be pretty promising.

**Comment by arunsrinivasan** [comment] 2015-08-26 05:48
Given that `data.table` is a *advanced/poweful tool/instrument* for data manipulation, I was thinking more like a power saw / drill or something like that :-).

Another option is (a data) 'equaliser' (for a nice combination of speed/memory efficiency/features/syntax etc..)?

**Comment by mbacou** [comment] 2015-08-26 07:54
Couldn't resist (-:

![image](https://cloud.githubusercontent.com/assets/260325/9488191/0a5ecddc-4ba6-11e5-8de8-a73622210106.png)

**Comment by petermeissner** [comment] 2015-08-26 08:27
playing around with @daroczig ...

![daroczig_pm](https://cloud.githubusercontent.com/assets/939139/9488833/e2709f94-4bdc-11e5-83a3-b3983ddcd956.png) 

playing around with @ajzz ...

![ajzz_pm](https://cloud.githubusercontent.com/assets/939139/9488834/e271c0cc-4bdc-11e5-8f76-7235fdc4b8f4.png)

**Comment by ajzz** [comment] 2015-08-26 15:24
@petermeissner I had the 9 blocks smaller so the highlighted ones are the right aspect ratio to look like the colon mark relative to the square brackets. Somehow having them on the left aesthetically was less pleasing although technically less correct (perhaps because I read from left to right). There is also a meta motif of the gap between the brackets representing a "battery" and the blocks inside which represent a "table" being the power ;)

@daroczig wish we could somehow make a pacman motif with those symbols :)

**Comment by daroczig** [comment] 2015-09-04 07:03
To bring up this thread a bit again, I found the following image fitting the best @arunsrinivasan's proposal:

![](http://33.media.tumblr.com/2419c27b09d42f14cca55c8025dd501b/tumblr_nrujo8ew8p1s373hwo1_250.gif)

**Comment by swihart** [comment] 2015-09-05 02:27
[Do we want colon and equal sign aligned or malaligned?](http://tex.stackexchange.com/q/4216/41307)

$:=$ vs $\coloneqq$ vs $=:$ vs $\eqqcolon$ ?

**Comment by MichaelChirico** [comment] 2016-02-02 21:24
@petermeissner 's take on @ajzz 's is my favorite so far. Perfect for setting the Rdatatable account logo, bookmark icon, etc.

**Comment by mattdowle** [comment] 2016-10-04 17:24
For icons, bookmark etc yes agree @petermeissner 's take on @ajzz's is looking good.  With @ajzz's suggestion to highlight the blocks inside to resemble :=

For a sticker, to be available on stickermule ... drawing together ideas from above and following the [sticker specification](https://github.com/terinjokes/StickerConstructorSpec), how about : 

![dtlogo resized](https://cloud.githubusercontent.com/assets/2779998/19084642/3e9ec880-8a1c-11e6-9986-480cad381e1a.png)

**Comment by stephlocke** [comment] 2016-10-22 17:22
Coming back to a seal-less logo
![image](https://cloud.githubusercontent.com/assets/6452610/19621198/7e3404a8-9884-11e6-92da-3acdf5e006bb.png)

**Comment by romunov** [comment] 2016-10-23 06:47
That's nice. And now I can not unsee Zoidberg. :) 👍

**Comment by petermeissner** [comment] 2016-10-23 06:48
- nice one!

... could you make its height the same as its width?
... how does it look if the stuff below the block is also looking block-like instead of 2d?

**Comment by stephlocke** [comment] 2016-10-23 08:14
Will make a variant that's square later today

**Comment by stephlocke** [comment] 2016-10-23 09:55
![logo](https://cloud.githubusercontent.com/assets/6452610/19625400/3de6749a-990f-11e6-965d-b08f98ac02b5.png)
![logo2d](https://cloud.githubusercontent.com/assets/6452610/19625398/3de55470-990f-11e6-9677-6c9b51b6028d.png)
![logoflattop](https://cloud.githubusercontent.com/assets/6452610/19625399/3de61a22-990f-11e6-871d-57bb6fd75763.png)

**Comment by mattdowle** [comment] 2016-12-10 09:52
Thanks for all the input everyone!
Decided to make a decision.  I asked around people who don't know what the project is and showed the various images above.  The main feedback was that the name of the package needs to be present clearly in strong font.  I have fond memories of sea lion from the MC at the conference dinner at the first useR! I attended (LA 2014) which I think I might have told Gabor before and I guess he picked up on it and filed this issue.  Table with `:=` syntax as legs was inspired @leeper!
So it's now on the homepage and links to stickermule.
On the smaller icon I've tried to create a favicon for the homepage for bookmarks, but r-datatable.com is just a web forward.  There's no way to set a favicon for a forward (I asked domainmonster.com support as well and they confirmed) since there's no way on guthub to set your own favicon.  If we ever go for an independent homepage, can come back to that then.  If there's a way to change bookmark icons manually in Chrome or other browsers then we could make an icon available for people to do that.  I'm not sure many would though if it's manual.  I hunted for a solution but couldn't find even a low level way to change a bookmark icon in Chrome.
So thanks again @gaborcsardi  and everyone!  We now have a logo!

**Closed by mattdowle** 2016-12-10 09:52 UTC

**Comment by gaborcsardi** [comment] 2016-12-10 14:17
Cool!

@mattdowle Btw. I am planning on supporting logos on METACRAN. All you would need to do is putting a PNG of appropriate size in the released package, at a specified place within `inst`. 

I'll let you know once I decide about the details.
