### ISSUE TITLE
[R-Forge #2330]  Optimize .SD[i] query to keep the elegance but make it faster unchanged.

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#613] opened 2014-06-08 13:16 UTC
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2330&group_id=240&atid=978)

By using .I   See :
http://stackoverflow.com/a/12955084/403310

**Comment by jangorecki** [comment] 2015-11-28 17:46
isn't it duplicate of  #735 ?

**Comment by mattdowle** [comment] 2016-01-12 22:13
Raised again here :

**Comment by mattdowle** [comment] 2016-02-23 18:56
And again here :

**Comment by kslays** [comment] 2019-02-28 04:43
Here are more related links:
https://github.com/Rdatatable/data.table/issues/735#issuecomment-63198483 and https://github.com/Rdatatable/data.table/issues/735#issuecomment-98836402
https://stackoverflow.com/a/24558696/
https://stackoverflow.com/a/16574176/
https://stackoverflow.com/q/47539186/

**Comment by jangorecki** [comment] 2024-01-07 10:01
Request in this issue is already resolved. It is documented in #735

**Closed by jangorecki** 2024-01-07 10:01 UTC
Labels: feature request
