### ISSUE TITLE
Can we have a fast fill function

### ISSUE THREAD

**Issue by statquant** [Rdatatable/data.table#1226] opened 2015-07-15 16:43 UTC
Could we get a fast "fill" function that would replicated na.locf in data.table.
Basically say fill will replace NA,NaN by whatever non NA,NaN was before. This is usefull by group

**Comment by arunsrinivasan** [comment] 2015-07-18 23:36
possible duplicate of https://github.com/Rdatatable/data.table/issues/854

**Closed by arunsrinivasan** 2015-07-18 23:36 UTC
Labels: feature request
