### ISSUE TITLE
Factor is not created when `i` is specified

### ISSUE THREAD

**Issue by symbalex** [Rdatatable/data.table#6465] opened 2024-09-05 02:56 UTC
When I order in `i` and then attempt to create a `factor` class using update-by-reference, the `factor` isn't created.

May be related to https://github.com/Rdatatable/data.table/issues/2403 but it appears to be a bit different (as the levels _are_ created in #2403).

Reprex:

```
library(data.table)
dt <- data.table(x = c("cat", "dog", "bird")
                 , y = c(3, 2, 0.5))
# I want to make a data.table with 
# factor levels determined by ordering of y
# i.e. bird, dog, cat should be the order
dt[order(y), x := factor(x, levels = unique(x))] 
str(dt) # factor not created
dt[, x := factor(x, levels = unique(x[order(y)]))] # works
str(dt)
```

Output of `sessionInfo()`

```
> sessionInfo()
R version 4.4.0 (2024-04-24)
Platform: x86_64-apple-darwin20
Running under: macOS Ventura 13.4.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Australia/Melbourne
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.15.4

loaded via a namespace (and not attached):
[1] compiler_4.4.0    tools_4.4.0       rstudioapi_0.16.0
```

**Comment by TysonStanley** [comment] 2024-09-05 04:53
I replicate the functionality reported here. Does seem unexpected.

**Comment by MichaelChirico** [comment] 2024-09-05 06:35
Actually I think this is a duplicate of #2925, looking at the `verbose=TRUE` output:

```
dt[order(y), x := factor(x, levels = unique(x)), verbose=TRUE]
# forderReuseSorting: opt not possible: is.data.table(DT)=0, sortGroups=1, all1(ascArg)=1
# forder.c received 3 rows and 1 columns
# forderReuseSorting: opt=0, took 0.000s
# Detected that j uses these columns: [x]
# Assigning to 3 row subset of 3 rows
# RHS_list_of_columns == false
```

Because `i` is present, we assume the column should retain the same storage type --> the `factor()` output is cast back to character, hence losing the levels.

We can confirm this by doing `debug(factor)` before the attempted assignment -- we'll see that we get the correct object at some point:

```r
(f)
# [1] bird dog  cat 
# Levels: bird dog cat
```

**Closed by MichaelChirico** 2024-09-05 06:35 UTC

**Comment by MichaelChirico** [comment] 2024-09-05 06:38
Reading more carefully, I got bit in exactly the same way as you in the 2nd comment there :)

https://github.com/Rdatatable/data.table/issues/2925#issuecomment-937593670
