### ISSUE TITLE
Many DT issues when using data after readr/dplyr (ie tbl_df data)

### ISSUE THREAD

**Issue by zeltak** [Rdatatable/data.table#1161] opened 2015-05-26 05:19 UTC
Hi
I have many many issues with DT not working correctly after doing some dplyr manipulation or using readr to read in csv data which results in the DF to have both DT and tbl_df formats.
I have posted this on the dplyr github page but they say its a DT bug :)
https://github.com/hadley/readr/issues/173#event-308416259

here are some of the erros i get which all go away if i convert the data to DF then to DT and issue the commands again

error 1:

out<- read_csv("/media/NAS/Uni/Data/MV3/Out/v01.2003.csv")
out<-as.data.table(out)

out[, day:=as.Date(strptime(date, "%d/%m/%Y"))]
Error in :=(day, as.Date(strptime(date, "%d/%m/%Y"))) : 
Check that is.data.table(DT) == TRUE. Otherwise, := and :=(...) are defined for use in j, once only and in particular ways. See help(":=").

error 2:
> setkey(days2003 ,aodid,day)
> setkey(aqua.2003,aodid,day)
> m1 <- merge(days2003, aqua.2003, all.x = T)
Error in `[.tbl_df`(y, xkey, nomatch = ifelse(all.x, NA, 0), allow.cartesian = allow.cartesian) : 
  unused arguments (nomatch = ifelse(all.x, NA, 0), allow.cartesian = allow.cartesian)

this is a show stopper bug (for me at least :)) and would love to help debug this

as a side note on linux the dev version of DT wont load :)
* DONE (data.table)
Reloading installed data.table
unloadNamespace("data.table") not successful. Forcing unload.
Error in get(Info[i, 1], envir = env) : 
  lazy-load database '/home/zeltak/R/x86_64-pc-linux-gnu-library/3.2/data.table/R/data.table.rdb' is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

best

Z

**Comment by jangorecki** [comment] 2015-05-26 07:24
Make your example reproducible and let us know which version you are using. Also if using 1.9.5 which version of it you are using - when installed. There has been some recent changes in 1.9.5 which fixes problems with classes so it might be already fixed in latest devel.

**Comment by zeltak** [comment] 2015-05-26 08:54
Thx Jan

ill try and create a reproducible dataset later today. i am on version 1.9.4. i cant seem to get 1.9.5 to load on linux (it seems to install fine). i get this error:

DONE (data.table) Reloading installed data.table unloadNamespace("data.table") not successful. Forcing unload. Error in get(Info[i, 1], envir = env) : lazy-load database '/home/zeltak/R/x86_64-pc-linux-gnu-library/3.2/data.table/R/data.table.rdb' is corrupt In addition: Warning message: In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

any clue?

**Comment by zeltak** [comment] 2015-05-26 08:54
Thx Jan

ill try and create a reproducible dataset later today. i am on version
1.9.4. i cant seem to get 1.9.5 to load on linux (it seems to install
fine). i get this error:

DONE (data.table) Reloading installed data.table
unloadNamespace("data.table") not successful. Forcing unload. Error in
get(Info[i, 1], envir = env) : lazy-load database
'/home/zeltak/R/x86_64-pc-linux-gnu-library/3.2/data.table/R/data.table.rdb'
is corrupt In addition: Warning message: In get(Info[i, 1], envir = env) :
internal error -3 in R_decompress1

any clue?

zeltak

**Comment by jangorecki** [comment] 2015-05-26 15:46
try `setattr(out, "class", c("data.table","data.frame"))`

**Comment by franknarf1** [comment] 2015-05-26 19:56
Using 1.9.4 is fine; jan was just saying "*if* you were using 1.9.5..."

It's possible your data is becoming corrupted. That was the problem the last time I saw this sort of thing: http://stackoverflow.com/q/30250608 I'd inspect the data after each step (reading in from csv, conversion to data.table, etc.) and force it back to simple classes, as jan suggested, if/when it gets weird.

**Comment by arunsrinivasan** [comment] 2015-05-27 14:38
This is fixed in 1.9.5. Either upgrade or wait for the next CRAN release, or use the solution provided by Jan using `setattr()` to explicitly set class to `c("data.table", "data.frame")`.

**Closed by arunsrinivasan** 2015-05-27 14:38 UTC

**Comment by helix123** [comment] 2015-06-14 13:20
This seems to be related (data.table * 1.9.5    2015-06-14 Github (Rdatatable/data.table@e22190a)):


    set.seed(45L)
    DT <- data.table(V1=c(1L,2L),
                 V2=LETTERS[1:3],
                 V3=round(rnorm(4),4),
                 V4=1:12)


    set.seed(46L)
    DT2 <- data.table(V1=c(1L,2L),
                 V2=LETTERS[1:3],
                 V3=round(rnorm(4),4),
                 V4=1:12)


    a <- dplyr::intersect(DT[ ,.(V1, V2)], DT2[ ,.(V1, V2)])

    a2 <- copy(a)

    class(a)
    a[ , V5:=V1+1]
    ##Warning message:
    ##  In `[.data.table`(a, , `:=`(V5, V1 + 1)) :
    ##  Invalid .internal.selfref detected and fixed by taking a (shallow) copy of the data.table so that := can add this new column by reference. At an earlier point, this data.table has been copied by R (or been created manually using structure() or similar). Avoid key<-, names<- and attr<- which in R currently (and oddly) may copy the whole data.table. Use set* syntax instead to avoid copying: ?set, ?setnames and ?setattr. Also, in R<=v3.0.2, list(DT1,DT2) copied the entire DT1 and DT2 (R's list() used to copy named objects); please upgrade to R>v3.0.2 if that is biting. If this message doesn't help, please report to datatable-help so the root cause can be fixed.

    class(a2)
    DTa <- as.data.table(a2)

    DTa[ , V5:=V1+1]
    ## works
