### ISSUE TITLE
IDs not assigned properly using function of .SD by group in data.table

### ISSUE THREAD

**Issue by bramvisser** [Rdatatable/data.table#1493] opened 2016-01-11 19:47 UTC
When using `felm()` inside data.table it seems that the `by` variables get mixed up. Could be that not all the factor levels are available in all the `.SD` subsets?

Please see this question on SO: http://stackoverflow.com/questions/34713439/idxs-not-assigned-properly-using-felm-by-group-in-data-table

    > bug.report(package="data.table")
    Package: data.table
     Version: 1.9.6
     Maintainer: Matt Dowle <mattjdowle@gmail.com>
     Built: R 3.2.3; x86_64-w64-mingw32; 2016-01-09 04:19:59 UTC; windows
    
    R Version:
     platform = x86_64-w64-mingw32
     arch = x86_64
     os = mingw32
     system = x86_64, mingw32
     status = 
     major = 3
     minor = 2.3
     year = 2015
     month = 12
     day = 10
     svn rev = 69752
     language = R
     version.string = R version 3.2.3 (2015-12-10)
     nickname = Wooden Christmas-Tree

**Comment by bramvisser** [comment] 2016-01-11 19:57
When filing the bug report I noticed that the [How to file a bug report](https://github.com/Rdatatable/data.table/wiki/How-to-file-a-bug-report) page is empty. Might want to have a look at that. It's linked to from [Contributing](https://github.com/Rdatatable/data.table/blob/master/Contributing.md).

**Comment by arunsrinivasan** [comment] 2016-02-09 21:43
Thanks. This is a duplicate of https://github.com/Rdatatable/data.table/issues/967.

`getfe(model[[1]])` returns a *factor* for each group.. And data.table's `by` isn't clever enough to identify the levels correctly and combine properly yet..

**Closed** 2016-02-09 21:44 UTC
Labels: bug, duplicate
