### ISSUE TITLE
Is keeping the key here intentional?

### ISSUE THREAD

**Issue by eantonya** [Rdatatable/data.table#1016] opened 2015-01-21 18:55 UTC
```R
dt = data.table(a = 1:4, b = 1:4)

setkey(dt, a, b)
key(dt[, b, by = a])
#[1] "a"
```

I ran into an issue where this was unwanted behavior (desired behavior was no key), and want to confirm if it's on purpose/helpful in some contexts.

**Comment by arunsrinivasan** [comment] 2015-01-21 19:09
Yes, it is intentional.

**Comment by eantonya** [comment] 2015-01-21 19:34
What's the reason for keeping it (besides being able to)? Is this different from/better than using `keyby` to set the key in these scenarios?

**Comment by arunsrinivasan** [comment] 2015-01-21 20:52
Can't remember exactly, but key being lost after operations (when there is no need to) came up often IIRC. It seemed more appropriate to retain keys when possible.

Retaining / losing keys depending on the type of operation seems hard to me. At least not clear on what type of operation should / shouldn't retain. Would be nice to come up with rules for that.

**Comment by arunsrinivasan** [comment] 2015-03-01 10:43
Closing this, as it's intended behaviour.

**Closed by arunsrinivasan** 2015-03-01 10:43 UTC
Labels: question
