### ISSUE TITLE
names are stripped from named list columns in data.table

### ISSUE THREAD

**Issue by mrdwab** [Rdatatable/data.table#2670] opened 2018-03-12 16:26 UTC
`as.data.table`, `data.table`, and `setDT` all seem to ignore `names` of `list`s in list-columns. They can't be added back into the `list` either. Is there a reason for this? Is there a way around it?

Example:

```
library(data.table)

## Sample data
L <- list(A = 1:2, B = NULL, C = 3:4)
DF <- data.frame(ID = 1:3, V1 = I(L))

## Names are there for data.frames ...
str(DF)
# 'data.frame':	3 obs. of  2 variables:
#  $ ID: int  1 2 3
#  $ V1:List of 3
#   ..$ A: int  1 2
#   ..$ B: NULL
#   ..$ C: int  3 4
#   ..- attr(*, "class")= chr "AsIs"

# ... but not for data.tables
str(as.data.table(DF))
# Classes ‘data.table’ and 'data.frame':	3 obs. of  2 variables:
#  $ ID: int  1 2 3
#  $ V1:List of 3
#   ..$ : int  1 2
#   ..$ : NULL
#   ..$ : int  3 4
#   ..- attr(*, "class")= chr "AsIs"

# Same results with these approaches
str(data.table(DF))
str(setDT(DF))

# Can't manually add them in either....
names(DF$V1) <- names(L)
str(DF)
# Classes ‘data.table’ and 'data.frame':	3 obs. of  2 variables:
#  $ ID: int  1 2 3
#  $ V1:List of 3
#   ..$ : int  1 2
#   ..$ : NULL
#   ..$ : int  3 4
#   ..- attr(*, "class")= chr "AsIs"
```

Here's my `sessionInfo`:

```
sessionInfo()
# R version 3.4.2 (2017-09-28)
# Platform: x86_64-pc-linux-gnu (64-bit)
# Running under: Ubuntu 17.10
# 
# Matrix products: default
# BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
# LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
# 
# locale:
#  [1] LC_CTYPE=en_IN.UTF-8       LC_NUMERIC=C               LC_TIME=en_IN.UTF-8       
#  [4] LC_COLLATE=en_IN.UTF-8     LC_MONETARY=en_IN.UTF-8    LC_MESSAGES=en_IN.UTF-8   
#  [7] LC_PAPER=en_IN.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
# [10] LC_TELEPHONE=C             LC_MEASUREMENT=en_IN.UTF-8 LC_IDENTIFICATION=C       
# 
# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
# [1] data.table_1.10.5
# 
# loaded via a namespace (and not attached):
# [1] compiler_3.4.2 tools_3.4.2    yaml_2.1.17  
```

**Comment by MichaelChirico** [comment] 2018-03-12 16:36
closely related to #1588

**Comment by jangorecki** [comment] 2020-04-02 19:44
I would lean towards not supporting list names. Each element of those names is always scalar, so it is reasonable to store names in a character column, just next to a list column. I believe it will also improve the performance when accessing list by name, vs filtering by that name in data.table `i` argument.

**Comment by jangorecki** [comment] 2020-04-06 18:25
AFAIU it is a duplicate of #1588

**Closed by jangorecki** 2020-04-06 18:25 UTC
Labels: non-atomic column
