### ISSUE TITLE
Support for chunkwise operations in fread?

### ISSUE THREAD

**Issue by hope-data-science** [Rdatatable/data.table#5388] opened 2022-05-21 02:28 UTC
In `readr` package, chunkwise function is supported (<https://readr.tidyverse.org/reference/read_delim_chunked.html>). Is it possible to let is supported in `data.table::fread`?

I tried to tackle this using the `skip` parameter, it turns out that it would be quite slow, seems to encounter issue in <https://github.com/Rdatatable/data.table/issues/4496>. Any ideas?

Thanks.

**Comment by MichaelChirico** [comment] 2022-05-21 02:58
duplicate of #1721

**Closed by MichaelChirico** 2022-05-21 02:58 UTC
Labels: duplicate
