### ISSUE TITLE
ERROR: compilation failed for package 'data.table'

### ISSUE THREAD

**Issue by sengoku93** [Rdatatable/data.table#2875] opened 2018-05-14 18:08 UTC
Hi,

I am having difficulty installing data.table in R 3.4.3. The error I get below:
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include  -fopenmp -fPIC  -Wall -g -O2  -c assign.c -o assign.o
clang: error: unsupported option '-fopenmp'
make: *** [assign.o] Error 1
ERROR: compilation failed for package ‘data.table’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/data.table’
Warning in install.packages :
  installation of package ‘data.table’ had non-zero exit status

Any suggestions would be appreciated. Thank you!

**Comment by jangorecki** [comment] 2018-05-30 13:00
Problem is known, and solved. The only problem is that recent binaries are not shipped on CRAN. This is also duplicate of #2406. Closing.

**Closed by jangorecki** 2018-05-30 13:00 UTC
Labels: omp

**Comment by mattdowle** [comment] 2018-05-31 00:39
I sent an email to cran@r-project.org about this earlier today.  [CRAN checks page for data.table](https://cran.r-project.org/web/checks/check_results_data.table.html) shows that r-oldrel-osx-x86_64 is a month stale. old-rel means R 3.4.*  MacOS binary are usually the slowest,  taking a week or two.  But 1 month is much more than usual.
