### ISSUE TITLE
Unexpected results when using as.factor()

### ISSUE THREAD

**Issue by geneorama** [Rdatatable/data.table#967] opened 2014-11-22 00:03 UTC
Sorry if this has already been reported, or if it's user error.

The `factor` command converts the column to the first factor.

``` R
dt <- data.table(id = 1:3, grp = letters[1:3])
dt[ , grp, keyby=id]
```

```
  id grp
1:  1   a
2:  2   b
3:  3   c
```

``` R
dt[ , as.factor(grp), keyby=id]
```

```
   id V1
1:  1  a
2:  2  a
3:  3  a
```

`sessionInfo()`

```
R version 3.1.1 (2014-07-10)
Platform: i386-w64-mingw32/i386 (32-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.9.5

loaded via a namespace (and not attached):
[1] chron_2.3-45 tools_3.1.1 
```

**Comment by arunsrinivasan** [comment] 2017-03-30 23:21
Also make sure all other issues referenced here are solved once/if tackled.

**Comment by ben-schwen** [comment] 2021-01-22 09:42
Original issue as well as #1493 and #2054 work now as intended. Closing here.

**Closed by ben-schwen** 2021-01-22 09:42 UTC
Labels: bug
