### ISSUE TITLE
data.table compilation failed in Centos 6.8

### ISSUE THREAD

**Issue by TYRANISTAR** [Rdatatable/data.table#3726] opened 2019-07-24 11:57 UTC
```
* installing *source* package ‘data.table’ ...
** package ‘data.table’ successfully unpacked and MD5 sums checked
** libs
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG   -I/usr/local/include  -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c assign.c -o assign.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG   -I/usr/local/include  -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c between.c -o between.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG   -I/usr/local/include  -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c bmerge.c -o bmerge.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG   -I/usr/local/include  -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c chmatch.c -o chmatch.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG   -I/usr/local/include  -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c dogroups.c -o dogroups.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG   -I/usr/local/include  -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c fastmean.c -o fastmean.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG   -I/usr/local/include  -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c fcast.c -o fcast.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG   -I/usr/local/include  -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c fmelt.c -o fmelt.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG   -I/usr/local/include  -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c forder.c -o forder.o
forder.c: In function ‘range_str’:
forder.c:295: error: expected end of line before ‘update’
make: *** [forder.o] Error 1
ERROR: compilation failed for package ‘data.table’
* removing ‘/usr/lib64/R/library/data.table’
```

According to this [post](url): https://github.com/Rdatatable/data.table/issues/3512 the issue seems to be an old gcc installation but according to yum i have the latest version up and running:

```
$ yum install gcc
Loaded plugins: fastestmirror, refresh-packagekit
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: ftp.cc.uoc.gr
 * epel: pkg.adfinis-sygroup.ch
 * extras: ftp.cc.uoc.gr
 * updates: ftp.cc.uoc.gr
http://downloads.linux.hp.com/repo/spp/rhel/6.5/x86_64/current/repodata/repomd.xml: [Errno 14] PYCURL ERROR 6 - "Couldn't resolve host 'downloads.linux.hp.com'"
Trying other mirror.
Package gcc-4.4.7-23.el6.x86_64 already installed and latest version
Nothing to do
```

I didn't quite understand the Makevars solution posted there as well. Can't find ~/.R/Makevars anywhere. Same issue appeared when using R-3.5.2.

**Comment by MichaelChirico** [comment] 2019-07-24 12:04
Looks like an openMP issue, there's a parallel loop on that line, please check your openMP installation:

https://github.com/Rdatatable/data.table/blob/master/src/forder.c#L295

**Comment by TYRANISTAR** [comment] 2019-07-24 12:07
The library is libgomp correct?

```
$ yum install libgomp
Loaded plugins: fastestmirror, refresh-packagekit
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: ftp.cc.uoc.gr
 * epel: pkg.adfinis-sygroup.ch
 * extras: ftp.cc.uoc.gr
 * updates: ftp.cc.uoc.gr
http://downloads.linux.hp.com/repo/spp/rhel/6.5/x86_64/current/repodata/repomd.xml: [Errno 14] PYCURL ERROR 6 - "Couldn't resolve host 'downloads.linux.hp.com'"
Trying other mirror.
Package libgomp-4.4.7-23.el6.x86_64 already installed and latest version
Nothing to do

```

**Comment by jangorecki** [comment] 2019-07-30 17:04
I see in your logs
```
Package gcc-4.4.7-23.el6.x86_64 already installed and latest version
```
gcc 4.4.7 is exactly the old version we are talking about, you need 4.8.2.
please see https://github.com/Rdatatable/data.table/issues/3291#issuecomment-498534741 for more details.
If you are able to reproduce issue using gcc 4.8.2+ please report back, for now closing this issue.

**Closed by jangorecki** 2019-07-30 17:04 UTC
