### ISSUE TITLE
__USE_MINGW_ANSI_STDIO compile warning on Windows

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#5530] opened 2022-11-17 00:03 UTC
When submitting 1.14.6 to CRAN, the Windows compile log showed the following. I haven't noticed this before on win-builder or GLCI Windows checks. Maybe it only occurs on CRAN's Windows server for some reason, or maybe it's there in GLCI and Appveyor but we just haven't noticed. This was with 1.14.6 which was a minimal patch in patch-1.14 branch. So it could be that it has been fixed or doesn't happen in master. Anyway, Uwe didn't mention it and it was accepted and published.

This is a copy and paste of the entire contents verbatim of https://win-builder.r-project.org/incoming_pretest/data.table_1.14.6_20221116_070601/Windows/00install.out.  That file gets deleted after 7 days so copied here.  Included the link too in case its file name including the timestamp is ever useful.

```
* installing *source* package 'data.table' ...
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c assign.c -o assign.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c between.c -o between.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c bmerge.c -o bmerge.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c chmatch.c -o chmatch.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c cj.c -o cj.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c coalesce.c -o coalesce.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c dogroups.c -o dogroups.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c fastmean.c -o fastmean.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c fcast.c -o fcast.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c fifelse.c -o fifelse.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c fmelt.c -o fmelt.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c forder.c -o forder.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c frank.c -o frank.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c fread.c -o fread.o
In file included from fread.h:3,
                 from fread.c:27:
dt_stdio.h:25: warning: "__USE_MINGW_ANSI_STDIO" redefined
   25 |   #define __USE_MINGW_ANSI_STDIO 1
      | 
In file included from d:\rtools42\x86_64-w64-mingw32.static.posix\include\corecrt.h:10,
                 from d:\rtools42\x86_64-w64-mingw32.static.posix\include\crtdefs.h:10,
                 from d:\rtools42\x86_64-w64-mingw32.static.posix\include\time.h:9,
                 from d:\rtools42\x86_64-w64-mingw32.static.posix\include\sys\time.h:10,
                 from fread.c:8:
d:\rtools42\x86_64-w64-mingw32.static.posix\include\_mingw.h:435: note: this is the location of the previous definition
  435 | #define __USE_MINGW_ANSI_STDIO 0      /* was not defined so it should be 0 */
      | 
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c freadR.c -o freadR.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c froll.c -o froll.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c frollR.c -o frollR.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c frolladaptive.c -o frolladaptive.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c fsort.c -o fsort.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c fwrite.c -o fwrite.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c fwriteR.c -o fwriteR.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c gsumm.c -o gsumm.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c ijoin.c -o ijoin.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c init.c -o init.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c inrange.c -o inrange.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c nafill.c -o nafill.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c nqrecreateindices.c -o nqrecreateindices.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c openmp-utils.c -o openmp-utils.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c quickselect.c -o quickselect.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c rbindlist.c -o rbindlist.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c reorder.c -o reorder.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c shift.c -o shift.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c snprintf.c -o snprintf.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c subset.c -o subset.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c transpose.c -o transpose.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c types.c -o types.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c uniqlist.c -o uniqlist.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c utils.c -o utils.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c vecseq.c -o vecseq.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG     -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -pedantic -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c wrappers.c -o wrappers.o
gcc -shared -s -static-libgcc -o data.table.dll tmp.def assign.o between.o bmerge.o chmatch.o cj.o coalesce.o dogroups.o fastmean.o fcast.o fifelse.o fmelt.o forder.o frank.o fread.o freadR.o froll.o frollR.o frolladaptive.o fsort.o fwrite.o fwriteR.o gsumm.o ijoin.o init.o inrange.o nafill.o nqrecreateindices.o openmp-utils.o quickselect.o rbindlist.o reorder.o shift.o snprintf.o subset.o transpose.o types.o uniqlist.o utils.o vecseq.o wrappers.o -fopenmp -lz -Ld:/rtools42/x86_64-w64-mingw32.static.posix/lib/x64 -Ld:/rtools42/x86_64-w64-mingw32.static.posix/lib -LD:/RCompile/recent/R/bin/x64 -lR
mv data.table.dll data_table.dll
installing to d:/RCompile/CRANincoming/R-devel/lib/00LOCK-data.table/00new/data.table/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (data.table)
```

**Comment by tdhock** [comment] 2022-12-04 14:14
hi I believe this is a duplicate of https://github.com/Rdatatable/data.table/issues/5374 which has already been fixed, by moving the #define data.table up in fread.h

**Closed** 2022-12-04 14:14 UTC
Labels: platform-specific
