### ISSUE TITLE
warnings from boxplot() in j

### ISSUE THREAD

**Issue by mcol** [Rdatatable/data.table#5418] opened 2022-07-12 08:55 UTC
Warnings are raised when using `boxplot()` in j:

```
dt <- setDT(copy(iris))
invisible(dt[, boxplot(Sepal.Length ~ Species)])

# Warning messages:
#     1: In as.data.table.list(jval, .named = NULL) :
#     Item 2 has 3 rows but longest item has 5; recycled with remainder.
# 2: In as.data.table.list(jval, .named = NULL) :
#     Item 3 has 2 rows but longest item has 5; recycled with remainder.
# 3: In as.data.table.list(jval, .named = NULL) :
#     Item 6 has 3 rows but longest item has 5; recycled with remainder.
```

The following produces an identical plot without raising warnings
```
boxplot(dt$Sepal.Length ~ dt$Species)
```

`#` `Output of sessionInfo()`
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.14.2

loaded via a namespace (and not attached):
[1] compiler_4.1.0 tools_4.1.0

**Comment by mcol** [comment] 2022-07-12 08:57
Following #2442, the following approaches allow to fix the warnings:

```
invisible(dt[, I(boxplot(Sepal.Length ~ Species))])
invisible(dt[, as.null(boxplot(Sepal.Length ~ Species))])
```

**Comment by MichaelChirico** [comment] 2022-07-12 15:06
my own approach is

```r
 j = {
  ...
  NULL
}
```

note that the root cause is barplot() returns a list and data.table assumes list output from j are columns. there's no way to know you want to throw away/ignore this output -- as.null() and NULL signal to the reader and to data.table that [ is called for side effects

closing because this is a known issue and I believe there's another open issue about an option for [ to handle this a bit more gracefully

**Closed by MichaelChirico** 2022-07-12 15:06 UTC
