### ISSUE TITLE
different evaluation behaviour depending on column class?

### ISSUE THREAD

**Issue by mteixido** [Rdatatable/data.table#2054] opened 2017-03-09 14:01 UTC
Hi,

I have a data table with two columns x and g, I want to construct all possible pairs of x values within a group (given by g). The following code generates succesfully the pairs if x is a numeric vector:

```r
library(data.table)
X=data.table(x=c(1,2,3,4),g=c(1,1,2,2))
X[,expand.grid(x=x,y=x),by=g]
   g x y
1: 1 1 1
2: 1 2 1
3: 1 1 2
4: 1 2 2
5: 2 3 3
6: 2 4 3
7: 2 3 4
8: 2 4 4
```

however doing exactly the same operation on characters results in a different output:

```
X=data.table(x=c('1','2','3','4'),g=c(1,1,2,2))
X[,expand.grid(x=x,y=x),by=g]
   g x y
1: 1 1 1
2: 1 2 1
3: 1 1 2
4: 1 2 2
5: 2 1 1
6: 2 2 1
7: 2 1 2
8: 2 2 2
```
I'm missing something obvious or this is a bug of the data.table package?

I'm using data.table_1.9.6 on R 3.2.3

Thanks

**Comment by MichaelChirico** [comment] 2017-03-09 15:20
I'm not 100% sure what's happening, but it's `stringsAsFactors` fault:

```
X[ , expand.grid(x=x, y=x, stringsAsFactors=FALSE), by=g]
#    g x y
# 1: 1 1 1
# 2: 1 2 1
# 3: 1 1 2
# 4: 1 2 2
# 5: 2 3 3
# 6: 2 4 3
# 7: 2 3 4
# 8: 2 4 4
```

**Comment by MichaelChirico** [comment] 2017-03-09 15:30
I guess this is related to #562, and maybe identical to #967

**Comment by arunsrinivasan** [comment] 2017-03-30 23:20
@MichaelChirico is right on about being a duplicate of https://github.com/Rdatatable/data.table/issues/967.

**Closed by arunsrinivasan** 2017-03-30 23:20 UTC
