### ISSUE TITLE
fread version 1.10.4 Error: isLOGICAL(showProgress) is not TRUE

### ISSUE THREAD

**Issue by bmreilly** [Rdatatable/data.table#2048] opened 2017-03-01 19:38 UTC
I recently updated to version 1.10.4, and since the update whenever I use fread() I get an error: 

```
fread(f)
Error: isLOGICAL(showProgress) is not TRUE
```

Unless I specify `showProgress=FALSE`

Is this intentional or is this an issue?

**Comment by jangorecki** [comment] 2017-03-05 11:50
duplicate of #1998

**Closed by jangorecki** 2017-03-05 11:50 UTC
Labels: duplicate
