### ISSUE TITLE
[R-Forge #2185] Add features/documentation for sliding windows with data.table

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#626] opened 2014-06-08 13:16 UTC
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2185&group_id=240&atid=978)

As asked [here](http://stackoverflow.com/questions/11676476/r-data-table-sliding-window):

but in that question `data.table` already seems much faster (6.4s) than the alternative (973s).

Should be just documenting (including timings) how to use good sliding window functions with `data.table`, rather than any new functionality per se.

**Comment by jangorecki** [comment] 2018-04-21 03:53
closing as duplicate of #2778

**Closed by jangorecki** 2018-04-21 03:53 UTC
Labels: documentation
