### ISSUE TITLE
print.data.table : expose options('data.table.print.row.names')

### ISSUE THREAD

**Issue by smcinerney** [Rdatatable/data.table#1097] opened 2015-03-27 03:31 UTC
A FR for ```print.data.table``` to use ```options('data.table.print.row.names')```to determine whether to print ```row.names``` or not. (Default: TRUE)

Currently it always prints row,names (followed by colon), and this setting is not exposed as either an option, or a function argument.

```require(data.table)
DT = data.table(x = 1:3, y=list(1:2, 3:4, 5:7))
data.table:::print.data.table(DT)
#    x     y
# 1: 1   1,2
# 2: 2   3,4
# 3: 3 5,6,7

options('data.table.print.row.names' = F)
data.table:::print.data.table(DT)
#    x     y
#  1   1,2
#  2   3,4
#  3 5,6,7
```

**Comment by arunsrinivasan** [comment] 2015-03-27 07:36
duplicate of #353. Just use `print(DT, row.names=FALSE)`.

```R
print(DT, row.names=FALSE)
#  x     y
#  1   1,2
#  2   3,4
#  3 5,6,7
```

**Comment by smcinerney** [comment] 2015-04-03 05:18
It's not a duplicate. I should have made clear I'm asking for an option that also affects the printing behavior when you just type name of the  ```DT```

I showed this to Matt Dowle last week, he agreed it wasn't a duplicate and was a worthwhile enhance.
Please reopen this.

**Comment by arunsrinivasan** [comment] 2015-04-03 07:42
Out of curiosity, why dint you just clarify that here?

**Comment by smcinerney** [comment] 2015-04-03 10:31
(I thought it's self-evident that people wouldn't report an issue without having searched the existing issues, which I had done). Anyway, hoping this could make 1.9.6

**Comment by smcinerney** [comment] 2015-04-03 10:32
Does 'here' mean on the github mailing-list, as opposed to in the issues database?

Date: Fri, 3 Apr 2015 00:42:05 -0700

**Comment by jangorecki** [comment] 2015-04-18 23:05
@smcinerney not sure if I understand correctly. Is it just a matter of changing `print.data.table` argument `row.names` default from `TRUE` to `getOption("data.table.print.row.names")`?

**Comment by smcinerney** [comment] 2015-04-19 10:46
Yes - and also updating documentation for data.table to say "see print.data.table for options() governing how data.tables are displayed".

**Comment by MichaelChirico** [comment] 2016-01-09 20:12
If I understand correctly, this is another instance where having a man page for `print.data.table` would help.

**Comment by arunsrinivasan** [comment] 2016-01-19 20:52
I'd be happy to review PRs for both fix and doc.

**Closed** 2016-03-06 16:59 UTC
Labels: feature request
