### ISSUE TITLE
data.table reverses column names

### ISSUE THREAD

**Issue by alanpaulkwan** [Rdatatable/data.table#1301] opened 2015-08-30 01:47 UTC
I hope I'm not redundant, but in data.table 1.9.5 (at this point an experimental version, I know) data.table will assign the wrong column names to the output. 

It seems in merge(x,y,by=c('c','d','e')) data.table will report columns according to the column order of c, d and e in Y. So, if the column order is cde in x and dce in y, then the final output will show: 

cde

but in actuality report

dce

This is probably confusing so please see the example below.

> require(data.table,lib.loc = '/mnt/saswork/aak87/downloaded_packages/')
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.6 (Santiago)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8      
 [8] LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.9.5    RevoUtilsMath_7.4.0 RevoUtils_7.4.0     RevoMods_7.4.0      RevoScaleR_7.4.0   

loaded via a namespace (and not attached):
[1] chron_2.3-45     codetools_0.2-10 foreach_1.4.2    iterators_1.0.7  tools_3.1.3     
> tbl1=data.table(value=runif(1000),b=letters,c=toupper(rev(letters)),d=1:40)
Warning messages:
1: In data.table(value = runif(1000), b = letters, c = toupper(rev(letters)),  :
  Item 2 is of size 26 but maximum size is 1000 (recycled leaving remainder of 12 items)
2: In data.table(value = runif(1000), b = letters, c = toupper(rev(letters)),  :
  Item 3 is of size 26 but maximum size is 1000 (recycled leaving remainder of 12 items)
> tbl2=data.table(c=toupper(rev(letters)),d=1:40,b=letters,value=runif(1000))
Warning messages:
1: In data.table(c = toupper(rev(letters)), d = 1:40, b = letters,  :
  Item 1 is of size 26 but maximum size is 1000 (recycled leaving remainder of 12 items)
2: In data.table(c = toupper(rev(letters)), d = 1:40, b = letters,  :
  Item 3 is of size 26 but maximum size is 1000 (recycled leaving remainder of 12 items)
> 
> merge(tbl1,tbl2,by=c('b','c','d'),allow.cartesian=1)
      b  c d    value.x   value.y
   1: A  2 z 0.69294311 0.7710016
   2: A  2 z 0.69294311 0.3711291
   3: A  2 z 0.04935918 0.7710016
   4: A  2 z 0.04935918 0.3711291
   5: A  4 z 0.53663464 0.6934052
  ---                            
1956: Z 37 a 0.49965233 0.7197576
1957: Z 39 a 0.49390338 0.2390024
1958: Z 39 a 0.49390338 0.4621884
1959: Z 39 a 0.60779905 0.2390024
1960: Z 39 a 0.60779905 0.4621884

**Comment by arunsrinivasan** [comment] 2015-08-30 08:52
Duplicate of https://github.com/Rdatatable/data.table/issues/1290, fixed in https://github.com/Rdatatable/data.table/commit/78a9b6282bb8a4cbbf2efc979e0ea4b4060039d7.

```r
require(data.table)
set.seed(45L)
tbl1 = data.table(value=runif(1000),b=letters,c=toupper(rev(letters)),d=1:40)
tbl2 = data.table(c=toupper(rev(letters)),d=1:40,b=letters,value=runif(1000))

ans1 <- merge(tbl1, tbl2, by=c('b', 'c', 'd'))
ans2 <- merge(as.data.frame(tbl1), as.data.frame(tbl2), by=c('b','c','d'))
setDT(ans2)

identical(setorder(ans1), setorder(ans2))
# [1] TRUE
```

**Closed by arunsrinivasan** 2015-08-30 08:52 UTC
