### ISSUE TITLE
Invalid construction of column types in `rbindlist()`

### ISSUE THREAD

**Issue by AsserHic** [Rdatatable/data.table#1685] opened 2016-04-29 10:25 UTC
It seems that `rbindlist()` fails in combining two `data.tables` with columns that are not present in both tables and have their own class types. Interestingly, the very same columns with the same class types can be combined if they are present on both tables.

1. Error message is misleading as it refers to internal column numbers as indices of the input tables. There are not necessarily that many columns present in the input tables even.
2. One should not face an issue in these merges as unique columns should not conflict with anything by definition.

## Reproduce this error

```R
rbind(data.table(a=1), data.table(b=Sys.time()), use.names=TRUE, fill=TRUE)
```

Error message:
```
 Error in rbindlist(l, use.names, fill, idcol) : 
  Class attributes at column 2 of input list at position 2 does not match with column 2 of input list at position 1. Coercion of objects of class 'factor' alone is handled internally by rbind/rbindlist at the moment. 
```

**Comment by jangorecki** [comment] 2016-04-29 11:01
Did you check on latest development version?
For me:
```r
library(data.table)
rbind(data.table(a=1), data.table(b=Sys.time()), use.names=TRUE, fill=TRUE)
#    a                   b
#1:  1                <NA>
#2: NA 2016-04-29 12:00:16
```

**Comment by MichaelChirico** [comment] 2016-04-29 12:38
this sounds familiar, I feel like this is a duplicate (and may have been fixed in devel, as Jan suggests)

**Comment by arunsrinivasan** [comment] 2016-05-01 20:01
Sorry, can't reproduce on `v1.9.7` (current devel). Please write back if you think it doesn't work as expected on the current devel.

**Closed by arunsrinivasan** 2016-05-01 20:01 UTC

**Comment by sanjmeh** [comment] 2018-02-04 08:11
I have been searching where is the fix for this problem. 
The problem of rbind returning an error still exists. 
Seems the above link (copied here: [link ])(https://github.com/Rdatatable/data.table/labels/fixed%20in%20devel)is not working.

**Comment by MichaelChirico** [comment] 2018-02-04 09:22
link is broken
