### ISSUE TITLE
Printing of an expression type column does not work when the expression wraps to a new line

### ISSUE THREAD

**Issue by RichardRedding** [Rdatatable/data.table#3011] opened 2018-08-24 09:22 UTC
Printing of an expression type column does not work when the expression wraps to a new line

Works:
```
data.table(e = expression(1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12))
```

Doesn't:
```
data.table(e = expression(1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12 + 13))
```

At least on my computer, outside of a `data.table`, the first expression would print all on one line and the second would be split over two.

***I have just noticed when doing `rbindlist` that it says expression type columns are not supported
***Therefore, maybe the issue is that I was able to create a `data.table` with an expression type column at all

P.S. I was unable to download the development version of data.table as per the wiki:
`data.table::update.dev.pkg(repo="https://gitlab.com/Rdatatable/data.table")
Error: Line starting '<!DOCTYPE html> ...' is malformed!`

Instead I did:
`devtools::install_github("Rdatatable/data.table")`

**Comment by jangorecki** [comment] 2018-08-24 10:15
as for the upgrade call, the url was incorrect, I already corrected it in wiki. `data.table::update.dev.pkg(repo="https://Rdatatable.gitlab.io/data.table")`

**Comment by MichaelChirico** [comment] 2019-05-04 13:39
> I have just noticed when doing `rbindlist` that it says expression type columns are not supported

`data.table` has no issue with storing `expression`s in a column (should be a `list` column I guess?), the error is coming from `rbindlist` which doesn't support stitching together such columns... you'll have to make a workaround for this for now.

**Comment by MichaelChirico** [comment] 2019-05-04 13:46
As to your main issue, on my machine:

```
data.table(e = expression(1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12 + 13)
```

is an error:

> Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent

with `traceback()`:

```
3: `rownames<-`(`*tmp*`, value = paste0(format(rn, right = TRUE, 
       scientific = FALSE), ":")) at print.data.table.R#73
2: print.data.table(x)
1: function (x, ...) 
   UseMethod("print")(x)
```

So there's something wrong in `print.data.table`...

Ideally you'll be able to use https://github.com/Rdatatable/data.table/pull/3414 to customize a print method for `expression` columns, but it probably shouldn't be erroring in the meantime.

**Comment by MichaelChirico** [comment] 2019-05-04 13:51
I see... it's breaking because the output wraps to a new line but `print.data.table` expects only one line since the table is 1-row:

```
expression(1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12 + 13)
# expression(1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12 + 
#     13)
```

I'll fix this in #3414

**Comment by MichaelChirico** [comment] 2019-05-04 17:18
For the record, I dove into this a bit; `print` is using `print.default`, internally `PrintExpression` I think is using `R_print.cutoff` to truncate but I don't think we have access to that, so there's no way to prevent the wrapping on the `expression` directly AFAICT

**Comment by jangorecki** [comment] 2020-05-24 12:26
As of now the most recent conclusion about `expression` type as a data.table column, is to keep it inside a list. Expression in general is a vector of language objects. The problem is that whenever any of its input is just atomic scalar, then its type is not language anymore.
```r
sapply(expression(-1,1), is.language)
# [1]  TRUE FALSE
```
so because it can mix types, it behaves more like a list than a vector.
Because it behave like a list, it then make sense to not duplicate the work we have already for handling lists.
Unless of course someone can show a case where wrapping expression into list impose an overhead, then it make sense to consider supporting that directly.
Closing that for now, yet your feedback is very welcome, ideally in #4040. I will copy my comments from here to that issue.

**Closed by jangorecki** 2020-05-24 12:26 UTC
Labels: non-atomic column
