### ISSUE TITLE
rowsBumping column from INT to STR when using integer64 = 'character' option

### ISSUE THREAD

**Issue by BlindApe** [Rdatatable/data.table#1790] opened 2016-08-02 18:00 UTC
When fread find a decimal point in a integer column bump it to STR instead to Numeric (Why is considered the dot for bump to STR?)

Read 0.0% of 463753 rowsBumping column 46 from INT to STR on data row 2772, field contains '5.4'

I set the dec parameter in fread explicit to '.' but didn't solve the problem.
This cause prediction procedure of new data fails.
What can I do for avoid this behavior?

> sessionInfo()
> R version 3.3.1 (2016-06-21)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.9.6

loaded via a namespace (and not attached):
[1] chron_2.3-47

**Comment by MichaelChirico** [comment] 2016-08-02 18:30
Why not supply `colClasses` as `numeric` instead of `integer`?

**Comment by BlindApe** [comment] 2016-08-02 18:42
Sure that fix it, but I have nearly 300 variables of mixed types and think bump from INT to STR when find a dot isn't the smartest behaviour.

**Comment by aadler** [comment] 2016-08-02 22:03
Sorry for intruding, but my initial read of the header was bumping from Intelligence to Strength, and I was wondering what AD&D has to do with data.table. :)

**Comment by arunsrinivasan** [comment] 2016-08-03 19:33
Please read the [support](https://github.com/Rdatatable/data.table/wiki/Support) page and improve your post.

**Comment by masip85** [comment] 2016-08-21 15:55
Same issue.

The column with coercion is called: LICENSE.STATUS.CHANGE.DATE

![captura de pantalla 2016-08-21 a las 17 50 16](https://cloud.githubusercontent.com/assets/12863854/17838211/cd15c3d8-67c7-11e6-938b-f334ca41bcba.png)

This is what verbose tell me:

![captura de pantalla 2016-08-21 a las 17 52 07](https://cloud.githubusercontent.com/assets/12863854/17838223/11192660-67c8-11e6-833f-61a4c353ac9c.png)

As you can see I am using no coercion at all. And another question could be why verbose tell me I am using 5 rows if I specify 100?

**Comment by arunsrinivasan** [comment] 2016-08-26 16:42
Please provide minimal reproducible examples.

**Comment by BlindApe** [comment] 2016-10-09 13:00
At least I find the origin of the problem:

require(data.table)
dtb <- data.table('c1' =  c(44, 81, 44, 45, 66, 66, 85, 100, 84, 103, 66, 85 ,101.5, 85, 96) , 'c2' = rep(1234567891234567, 15), 'c3' = rep(2, 15))
write.csv(dtb, file = 'data.csv', row.names = FALSE)
dtb <- fread('data.csv', verbose = TRUE, integer64 = 'character')
sapply(dtb, class)
dtb <- fread('data.csv', verbose = TRUE)
sapply(dtb, class)

The problem is when you use integer64 = 'character', then INT is converted to STR instead of NUMERIC.

Seams the INT -> REAL conversion has a internal step to INT64 (!?):

Bumping column 1 from INT to INT64 on data row 13, field contains '101.5'
Bumping column 1 from INT64 to REAL on data row 13, field contains '101.5'

and when we use integer64 = 'character' the REAL conversion isn't reached.

**Comment by st-pasha** [comment] 2017-07-06 20:51
Duplicate of #1872

**Closed by st-pasha** 2017-07-06 20:51 UTC
Labels: duplicate, fread
