### ISSUE TITLE
Fread 'sep' must be a single character

### ISSUE THREAD

**Issue by sabrikaragonen** [Rdatatable/data.table#2361] opened 2017-09-15 07:06 UTC
We're using double pipe "||" as seperator in csv files. It makes our data transfer process more robust.
However, when I try to use fread with these files, I get the error in the title.  
Is it possible to change that behaviour in fread? It should accept double characters as seperator, too.

**Comment by st-pasha** [comment] 2017-09-15 07:10
Duplicate of #2011

**Comment by mattdowle** [comment] 2018-03-03 10:13
Yep, closing at duplicate. Thanks @st-pasha.  Keeping the earlier one open.

**Closed by mattdowle** 2018-03-03 10:13 UTC
Labels: duplicate, feature request, fread
