### ISSUE TITLE
Windows 10 is faster with -fno-openmp than setDTthreads(1) on many repeated calls

### ISSUE THREAD

**Issue by ColeMiller1** [Rdatatable/data.table#4527] opened 2020-06-05 03:10 UTC
OpenMP support may cause issues with Windows performance, especially with many repeated calls. 
```r
library(data.table)
setDTthreads(1L)
allIterations <- data.table(v1 = runif(1e5), v2 = runif(1e5))
DoSomething <- function(row) someCalculation <- row[["v1"]] + 1

system.time(for (r in 1:nrow(allIterations)) DoSomething(allIterations[r, ]))
##1.12.8 
##   user  system elapsed 
##  17.09    4.48   22.14 

##master
##   user  system elapsed 
##  17.50    4.53   22.51 

##master w/ OpenMP lines deleted from subset.c
##   user  system elapsed 
##  12.37    0.01   12.85 
```
Note, I would expect using ```setDTthreads(1L)``` would minimize any impacts to performance but that does not appear to be the case on Windows 10.

**Comment by jangorecki** [comment] 2020-06-05 09:02
That is interresting, could you check if replacing `num_threads(1)` with `if (false)` will solve that? I was just recently checking that we can safely rely on `num_threads` only here: https://github.com/Rdatatable/data.table/pull/4484#discussion_r433855471
What is your compiler and version?

**Comment by ColeMiller1** [comment] 2020-06-06 00:49
Using 
```
#pragma omp parallel for if (1 < 0) num_threads(getDTthreads())
```
Does not help (I also changed the two ```_Pragma("...")``` lines). Based on performance, it seems like it is still trying to fork a process or whatever the equivalent is for Windows.

I use what is in Rtools 3.5.0.4 which appears to be MinGW gcc 4.9.3??? I am not versed in compilers. After googling, I will install Rtools 4.0 which is at gcc 8.3.0 and update this post later. Below is from the ```build-info.txt``` of both 32- and 64-bit version

```
version : MinGW-W64-builds-4.2.0
user    : Jeroen
date    : 09.12.2015- 9:12:03
args    : --mode=gcc-4.9.3 --rt-version=v3 --arch=i686 --exceptions=dwarf --static-gcc --threads=posix --enable-languages=c,c++,fortran
PATH    : /mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/MiKTeX 2.9/miktex/bin:/c/Program Files/Git/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

version : MinGW-W64-builds-4.2.0
user    : Jeroen
date    : 09.12.2015- 5:21:38
args    : --mode=gcc-4.9.3 --rt-version=v3 --arch=x86_64 --exceptions=seh --static-gcc --threads=posix --enable-languages=c,c++,fortran
PATH    : /mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/MiKTeX 2.9/miktex/bin:/c/Program Files/Git/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```

Finally, when I do ```install.packages('data.table')```, does my compiler matter then? Because I get identical performance with CRAN version.

**Comment by jangorecki** [comment] 2020-06-06 10:26
if you install from binaries then it doesn't matter. For measuring performance install from source, use `-O3 -mtune=native` flags, and use recent gcc, 7+ should be fine.

**Comment by ColeMiller1** [comment] 2020-06-06 12:23
I upgraded to R 4.0.1 / rtools 4.0 which includes gcc 8.3. I recompiled and same performance issues. 

I am uncertain on how to change the ```-O3 -mtune=native``` flags. With ```install.packages(...)```, I have tried ```INSTALL_opts``` and ```configure.args```. I have tried to compile directly from the Terminal with ```R CMB INSTALL data.table_1.12.9.tar.gz -03 -mtune=native```. Note: ```cc()``` does not work on Windows 10.

**Comment by jangorecki** [comment] 2020-06-06 12:53
if it doesn't exists, just create it
```sh
cat ~/.R/Makevars 
#CC=gcc
#CFLAGS=-O3 -mtune=native
```

**Comment by jangorecki** [comment] 2020-06-06 13:07
So if none of `if (1<0)` and `num_threads(1)` will not eliminate openmp overhead on windows, then I think we have to ignore that, and eventually document, that if user wants to use single thread always, then it may be better to compile with openmp disabled.

**Comment by ColeMiller1** [comment] 2020-06-06 18:56
That seems somewhat user unfriendly - I embarrassingly would not know how to do that. Is something like this not maintainable?

```
//global variables
bool get_nt = true;
int nt = 0;

...
// inside a function
  if (get_nt) nt = getDTthreads();
  get_nt = false;

  if (nt > 1) {
#pragma omp parallel for num_threads(nt)
    for (int i=0; i<n; i++) {
      if (stop) continue;
      int elem = idxp[i];
      if ((elem<1 && elem!=NA_INTEGER) || elem>max) stop=true;
    }
  }
  else {
    for (int i=0; i<n; i++) {
      if (stop) continue;
      int elem = idxp[i];
      if ((elem<1 && elem!=NA_INTEGER) || elem>max) stop=true;
    }
  }
```
I reworked subset.c to follow the flow above. 
```r
library(data.table)
allIterations <- data.table(v1 = runif(1e5), v2 = runif(1e4))
DoSomething <- function(row) someCalculation <- row[["v1"]] + 1
system.time(for (r in 1:nrow(allIterations)) DoSomething(allIterations[r, ]))

##setDTthreads(1L)
##   user  system elapsed 
##  16.09    0.14   16.61 

##setDTthreads(2L)
##   user  system elapsed 
##  58.11   32.06   78.61 
```
Obviously, my hack has negatively impacted multiple threads - I believe it's related to where I included it in the ```#define _Pragma("...")``` bit... I am looking at the resources and testing other things out. Ideally, your suggestion of ```#pragma omp parallel if(1<0) for num_threads(2)``` would have been great - maybe there's still something to that. 

I will report back with progress.

**Comment by ColeMiller1** [comment] 2020-06-07 02:41
Also, specific to ```subset.c```, is it typical to design parallel teams to make more parallel teams? That is, ```subsetDT``` makes teams for each column and then each column in ```subsetvectorraw``` gets teams to subset the vector itself.

**Comment by jangorecki** [comment] 2020-06-07 12:24
If you are asking for nested parallelism then we want to avoid it, collapsing nested loops is fine.

**Comment by ColeMiller1** [comment] 2020-06-10 01:11
Sorry about the previous post about nested parallelism - I accidentally introduced it while editing ```subset.c```. There are no issues in the actual master branch.

My experimentation has been unsuccessful. I am interested in compiling without OpenMP to verify that there is no performance issues. How do I compile without OpenMP...? 

I see there are two ```Makevars``` files in ```src```. This in ```.in```:
```
PKG_CFLAGS = @openmp_cflags@
PKG_LIBS = @openmp_cflags@ -lz

all: $(SHLIB)
	if [ "$(SHLIB)" != "datatable$(SHLIB_EXT)" ]; then mv $(SHLIB) datatable$(SHLIB_EXT); fi
	if [ "$(OS)" != "Windows_NT" ] && [ `uname -s` = 'Darwin' ]; then install_name_tool -id datatable$(SHLIB_EXT) datatable$(SHLIB_EXT); fi
```
And this is ```.win```:
```
PKG_CFLAGS = $(SHLIB_OPENMP_CFLAGS)
PKG_LIBS = $(SHLIB_OPENMP_CFLAGS) -lz

all: $(SHLIB)
	mv $(SHLIB) datatable$(SHLIB_EXT)
```
When using ```install.packages(..., type = "source"), this is what a line looks like:
```
"C:/rtools40/mingw64/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.1/include" -DNDEBUG       -fopenmp   -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c wrappers.c -o wrappers.o
```
While I have attempted some research, I do not know where to begin.

**Comment by ColeMiller1** [comment] 2020-06-13 14:10
Still working on this - tried the throttle threads PR but it still did not work.

What is an example where OpenMP should shine? Using 1.12.8 and ```x = sample(1e7L)```, ```order(x)``` is still 3x faster on 1 thread than ```forder(x)```. Note, using multiple threads helps but it still does not catch up to ```order(x)```.
```r
library(data.table)

x = sample(1e7L)

setDTthreads(1L)

 bench::mark(data.table:::forder(x),
 order(x),
 min_iterations = 10L)

### A tibble: 2 x 13
##  expression               min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
 ## <bch:expr>             <bch> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>
##1 data.table:::forder(x) 923ms  929ms      1.07    38.1MB    0.459     7     3
##2 order(x)               354ms  355ms      2.79    38.1MB    1.19      7     3

setDTthreads(2L)

##  expression               min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
##  <bch:expr>             <bch> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>
##1 data.table:::forder(x) 614ms  657ms      1.50    38.1MB    0.376     8     2
##2 order(x)               359ms  368ms      2.73    38.1MB    1.17      7     3
```

**Comment by ColeMiller1** [comment] 2020-06-13 17:37
And I just tried replacing ```$(SHLIB_OPENMP_CFLAGS) / @openmp_cflags@``` with -fno-openmp. This worked and there are no performance penalties in ```subsetDT```.

**Comment by jangorecki** [comment] 2020-06-13 22:40
Could you please try this? using `-O3 -mtune=native`, so openmp will work.
```r
remotes::install_gitlab("jangorecki/data.table@omp-overhead")
library(data.table)
setDTthreads(0L)
getDTthreads()
fcopy = data.table:::fcopy
x = sample.int(1e8L)
system.time(a<-fcopy(x, 1L)) ## schedule(static) num_threads(1)
system.time(a<-fcopy(x, 2L)) ## if (1<0) schedule(static) num_threads(getDTthreads())
system.time(a<-fcopy(x, 3L)) ## schedule(dynamic) num_threads(1)
system.time(a<-fcopy(x, 4L)) ## if (1<0) schedule(dynamic) num_threads(getDTthreads())
```

**Comment by ColeMiller1** [comment] 2020-06-14 03:47
I copied your Makevars suggestions - it still compiled with ```-02``` and without the ```mtune-native```. Here is the performance:

```
> setDTthreads(0L)
> getDTthreads()
[1] 4
> fcopy = data.table:::fcopy
> x = sample.int(1e8L)
> system.time(a<-fcopy(x, 1L)) ## schedule(static) num_threads(1)
fcopy: integer length 100000000 took 0.145s
   user  system elapsed 
   0.11    0.05    0.16 
> system.time(a<-fcopy(x, 2L)) ## if (1<0) schedule(static) num_threads(getDTthreads())
fcopy: integer length 100000000 took 0.151s
   user  system elapsed 
   0.15    0.08    0.24 
> system.time(a<-fcopy(x, 3L)) ## schedule(dynamic) num_threads(1)
fcopy: integer length 100000000 took 3.523s
   user  system elapsed 
   3.42    0.01    3.52 
> system.time(a<-fcopy(x, 4L)) ## if (1<0) schedule(dynamic) num_threads(getDTthreads())
fcopy: integer length 100000000 took 3.546s
   user  system elapsed 
   3.47    0.03    3.53 
````

**Comment by jangorecki** [comment] 2020-06-14 10:32
and just to double check
```r
system.time(for (i in 1:10) a<-fcopy(x, 1L))
system.time(for (i in 1:10) a<-fcopy(x, 2L))
```

**Comment by ColeMiller1** [comment] 2020-06-14 10:36
```
> system.time(for (i in 1:10) a<-fcopy(x, 1L))
fcopy: integer length 100000000 took 0.207s
fcopy: integer length 100000000 took 0.256s
fcopy: integer length 100000000 took 0.160s
fcopy: integer length 100000000 took 0.160s
fcopy: integer length 100000000 took 0.146s
fcopy: integer length 100000000 took 0.142s
fcopy: integer length 100000000 took 0.148s
fcopy: integer length 100000000 took 0.141s
fcopy: integer length 100000000 took 0.138s
fcopy: integer length 100000000 took 0.156s
   user  system elapsed 
   1.06    1.03    2.22 
> system.time(for (i in 1:10) a<-fcopy(x, 2L))
fcopy: integer length 100000000 took 0.136s
fcopy: integer length 100000000 took 0.148s
fcopy: integer length 100000000 took 0.144s
fcopy: integer length 100000000 took 0.153s
fcopy: integer length 100000000 took 0.185s
fcopy: integer length 100000000 took 0.145s
fcopy: integer length 100000000 took 0.148s
fcopy: integer length 100000000 took 0.157s
fcopy: integer length 100000000 took 0.146s
fcopy: integer length 100000000 took 0.145s
   user  system elapsed 
   1.14    0.89    2.04 
```

**Comment by jangorecki** [comment] 2020-06-14 10:44
I would say, that there is no extra overhead on windows caused by the way how we escape openmp. Any degrade of performance must be caused by other factor. You can try running this last two calls having `-fno-openmp`. If difference will be visible, then I think we should just document it.

**Comment by ColeMiller1** [comment] 2020-06-14 10:53
Is there a global Makevars somewhere to make the change to ```-fno-openmp```? 

It's possible that ```dt[1L]``` is a particularly bad case - on Windows, multiple processes are fired up and then restored for each column due to where the parallelization is. So if there's 30 microseconds of overhead, I would see that on each column.

**Comment by jangorecki** [comment] 2020-06-14 11:03
I just replace `@openmp_cflags@` with `-fno-openmp` in Makevars.in. For windows replace `$(SHLIB_OPENMP_CFLAGS)` in Makevars.win.
Just checked and putting `-fno-openmp` in `~/.R/Makevars` is ignored, so the above seems to be the most straightforward way.

**Comment by ColeMiller1** [comment] 2020-06-14 11:58
It took some time to figure out how to clone your gitlab repo:

On Windows ```-fno-openmp```
```
   user  system elapsed 
   1.10    0.77    1.90 
   user  system elapsed 
   1.11    0.94    2.13 
```

On Windows ```-fopenmp```
```
   user  system elapsed 
   0.96    0.87    1.89
   user  system elapsed 
   1.04    0.89    2.07
```
I agree for this use case that there is no appreciable difference. 

Here is a case where this is a difference. The implication is that while no one will be subsetting a row at a time, the ideal API for subsetting by group is ```DT[, .SD[1:2], grp]``` - this overhead can really add up as groups increase.

```r
library(data.table)
mat = matrix(0L, nrow =1000L, ncol= 100L)

DT = as.data.table(mat)
DF = as.data.frame(mat)

##-fopenmp
setDTthreads(1L)
system.time(for (i in seq_len(nrow(DT))) {DT[i]})
##   user  system elapsed 
##   0.59    0.38    1.00 
system.time(for (i in seq_len(nrow(DF))) {DF[i,]})
##   user  system elapsed 
##   1.12    0.02    1.19 

##-fno-openmp
system.time(for (i in seq_len(nrow(DT))) {DT[i]})
##   user  system elapsed 
 ##  0.19    0.01    0.22 
system.time(for (i in seq_len(nrow(DF))) {DF[i,]})
##   user  system elapsed 
##   1.01    0.00    1.03

**Comment by jangorecki** [comment] 2020-06-14 13:18
I see it does have impact then. This is on linux, having nrow scaled up to 1e5. So it seems to be Windows specific overhead.
```r
library(data.table)
mat = matrix(0L, nrow =1e5L, ncol= 10L)
DT = as.data.table(mat)
DF = as.data.frame(mat)
```
```r
##-fopenmp
setDTthreads(1L)
system.time(for (i in seq_len(nrow(DT))) {DT[i]})
#   user  system elapsed 
# 11.864   0.286  12.150 
system.time(for (i in seq_len(nrow(DF))) {DF[i,]})
#   user  system elapsed 
#   6.82    0.00    6.82 
```
```r
##-fno-openmp
system.time(for (i in seq_len(nrow(DT))) {DT[i]})
#   user  system elapsed 
# 12.148   0.008  12.157 
system.time(for (i in seq_len(nrow(DF))) {DF[i,]})
#   user  system elapsed 
#  7.292   0.000   7.293 
```

**Comment by mattdowle** [comment] 2020-06-15 17:46
Great info @ColeMiller1, many thanks for investigating here. Seems like the new throttle works on Linux but not on WIndows. So that's something that needs further work then, agree.

Can I clear up a few sentences on this one.

> OpenMP support may cause issues with Windows performance, especially with many repeated calls.

Why the *especially*? This issue is *just* about repeated calls, and repeated calls on small data, right?

> What is an example where OpenMP should shine?

Any of the examples in https://h2oai.github.io/db-benchmark/.  They are single calls on large data that take more than a few seconds, and in some cases minutes, to run.

In generally, `[.data.table` doesn't like being repeated (it has overhead). That's why we have `set()` low-overhead alternative and why we use `[[` and `$` with data.table for ordinary operations. We'd like to one day to get to a state where the user doesn't need to know (for example by reworking [.data.table) but that hasn't happened yet.

And in general data.table doesn't like doing things one row at a time, which is true in R is general, and Python too. Always work to do to make it easier for user but it's just not recommended practice in high level languages like R.

So yet we do want to work on one-row-at-a-time benchmarks like this one, but I wonder how how it should be on the list.

**Comment by ColeMiller1** [comment] 2020-06-16 04:04
I agree that single row subsetting itself is not a large concern - the original example is related to #3735. But that's where I found another Windows user had slower subsets than Linux users for many repeated calls.

*Why should we care about this*? Operations by group can be affected, especially if when we subset by group (e.g. ```dt[, .SD[1:2], grp]```. For Windows users, there can be negative impacts even with ```setDTthreads(1L)```.

I hope my choice of words doesn't make us overlook that there are opportunities to make ```data.table``` the best tool for both large data and small data regardless of platform. In working towards #852, I have a branch that takes down 14s to 5.3s for ```matrix(0L, nrow =1e5L, ncol= 10L)``` without OpenMP. With OpenMP, it goes from 24.5s to 13.6 s. So, 80us at a time can add up with optimizations.

FWIW - this may be centered around where the OpenMP loop is. While it is extremely buggy, putting the ```pragma omp parallel for ...``` in the ```subsetDT``` instead of the ```subsetVectorRaw``` changes the time on this branch to 8.3s. The main difference being that whereas Linux has no overhead, Windows seems to have overhead anytime the process is forked and unforked. As ```subsetDT``` is currently written, every column will get a new set of teams to go out and subset the vector.

**Comment by jangorecki** [comment] 2020-06-16 23:58
Old but related topic: http://forum.openmp.org/forum/viewtopic.php?f=3&t=1722
Also few hits on SO mentions visual studio, so looks to be windows specific.

**Comment by MichaelChirico** [comment] 2020-06-18 02:40
Just hit a work issue where it was pretty natural to do rowwise `[`:

The basic idea is I need to collapse some columns into a metadata column, e.g.

```
NN = 1e5
DT = data.table(ID = 1:NN, V1 = rnorm(NN), V2=rnorm(NN))
```

I tried:

```
DT[ , metadata := lapply(seq_len(.N), function(ii) .SD[ii]), .SDcols = c('V1', 'V2')]
```

And it's indeed rather slow.

`transpose` essentially works in this case because `V1` and `V2` are the same type, but generally they could be different types (-> coercion) and include non-`transpose`-compatible types (e.g. `list`)

**Comment by ColeMiller1** [comment] 2020-06-18 11:56
@MichaelChirico thanks for the example. Using ```by``` would help speed this up some (maybe a dedicated ```nest()``` feature would be better:

``` r
library(data.table) ##1.12.8
setDTthreads(1L)
NN = 1e4
DT = data.table(ID = 1:NN, V1 = rnorm(NN), V2=rnorm(NN))

system.time(DT[ , metadata := lapply(seq_len(.N), function(ii) .SD[ii]), .SDcols = c('V1', 'V2')])
#>    user  system elapsed 
#>    1.86    0.12    1.98
system.time(DT[ , metadata2 := .(.(copy(.SD))), by = ID, .SDcols = c('V1', 'V2')])
#>    user  system elapsed 
#>    0.26    0.02    0.28
all.equal(DT$metadata, DT$metadata2)
#> [1] TRUE
```
I had to use ```copy()``` because otherwise the result has the ```locked``` attribute.

**Comment by MichaelChirico** [comment] 2020-06-18 12:10
The `copy()` part should be fixed in dev right?

**Comment by ColeMiller1** [comment] 2020-06-18 12:43
@MichaelChirico I just downloaded master - does not appear to be fixed. TBH, I'm not aware of an issue related to nesting ```.SD``` by group:

```r
DT[, metadata3 := .(.(.SD)), by = ID, .SDcols = c("V1", "V2")]

attributes(DT$metadata3[[1L]])
##$row.names
##[1] 1

##$class
##[1] "data.table" "data.frame"

##$.internal.selfref
##<pointer: 0x05772498>

##$names
##[1] "V1" "V2"

##$.data.table.locked
##[1] TRUE

all.equal(DT$metadata2[[1L]], DT$metadata3[[1L]])
##[1] "Datasets has different number of (non-excluded) attributes: target 2, current 3"
```

**Comment by jangorecki** [comment] 2020-06-18 18:06
This can be observed on Linux as well:
this branch removes overhead: https://github.com/Rdatatable/data.table/compare/dogroups-overhead?expand=1
while this branch still has the overhead: https://github.com/Rdatatable/data.table/compare/dogroups-overhead2?expand=1

**Comment by jangorecki** [comment] 2020-06-18 22:02
@ColeMiller1 could confirm if #4558 resolves this issue?

**Comment by ColeMiller1** [comment] 2020-06-19 01:11
@jangorecki sorry for the delay. Yes! (I even like that I do not have to add ```setDTthreads(1L)``` at the top!)

``` r
library(data.table)
mat = matrix(0L, nrow =1e5L, ncol= 10L)
DT = as.data.table(mat)
DF = as.data.frame(mat)

system.time(for (i in seq_len(nrow(DT))) {DT[i]})
#>    user  system elapsed 
#>   13.42    0.43   14.15
system.time(for (i in seq_len(nrow(DF))) {DF[i,]})
#>    user  system elapsed 
#>   12.66    0.03   12.97
```

The ```system.time``` is still a little higher - it would be great if we could add an argument to ```subsetDT``` about whether the indices need to be checked. From ```[.data.table```, we already checked once so there's no need to convert zeros and negative IDs again.

But, that's small overall and could be addressed by a follow-up issue. The subsetting performance was the only place I noticed the OpenMP issue. Please feel free to close this when the PR is merged.

Thanks for all of your help!

**Closed** 2020-06-26 22:05 UTC
Labels: openmp, performance, platform-specific
