### ISSUE TITLE
Be able to specify sort order within by

### ISSUE THREAD

**Issue by jsams** [Rdatatable/data.table#2894] opened 2018-05-21 05:21 UTC
Frequently, when using `by`, I want some other column(s) to be sorted within the by. E.g. if I have user-week level data, and I'm doing some operation with `by=user`, maybe I'm creating some lag indicator and want each user's data to be sorted by the `week` variable. Right now, I need to first set the key to be `user, week`, but then I have 5, 10, 15 commands after the `setkey` operation and eventually this very much ends up being a kind of "action at a distance" type situation and therefore, in my experience, fragile.

So, I'm wondering how difficult it would be to have another keyword or some other syntax indicating that the `by` data should be sorted within each group by a variable but not grouped by that variable. (I can't believe I'm referencing Stata, but...) [Stata has something like this](https://www.stata.com/help.cgi?bysort), and I think it is useful in keeping the logic of the query complete in one place.

It probably also make sense to allow some kind of +/- indicator for ascending versus descending sort like setorder.

One syntax possibility is having a nested list `(key)by=.(user, .(week))` (not too sure how hard this is to parse out on your end). Keyword names might be `bysort`, `windowsort`, `winsort`, `withinsort`, but probably some other better name exists. That said, I'm sure the actual machinery to get this working is more difficult than the keyword decision.

**Comment by MichaelChirico** [comment] 2018-05-21 06:08
`DT[order(week), do_j, by = user]`?

**Comment by HughParsonage** [comment] 2018-05-21 12:01
Thanks for the suggestion, but I'm unclear on the 'fragility' of your current setup. Can you provide an example where your current approach comes unstuck or becomes error-prone?

**Comment by jsams** [comment] 2018-05-21 17:40
There's a state dependence on the data storage in the query logic that can be easily broken with otherwise innocuous modifications to data. That's a fundamental fragility because that state dependence cannot be checked/enforced as part of the query.

I mean, this is precisely why window functions in SQL have sorting operators instead of just depending on the sort order of some pre-existing index/key/storage order of the data. The sorting is part of the fundamental logic of the query, irrespective of the properties of the underlying data storage.

Michael's suggestion--while certainly inventive!--I would argue is not great. It completely breaks the standard analogy of `x` being akin to `WHERE` like filtering (not to mention if I am using keys correctly, it's going to kill performance).

If you really want example code, there's some below. But I think the point I'm making is that the problems increase exponentially with a larger code base, so trivial examples will be, well, trivial.

Say I write some original code that is not broken:
```R
setkey(dt, user, week)
dt[, play_per_user := .N, by=user]
dt[, user_per_week :=.N, by=week]
dt[, user_month_intensity := .N, by=.(user, month)]
dt[, user_week_level_lag := user_week_level - shift(user_week_level), by=user]
```

Then I come by 6 months later and decide I want the lag scaled by some month level variable obtained elsewhere, so insert that variable at the point in the code flow where I need it:
```R
setkey(dt, user, week)
dt[, play_per_user := .N, by=user]
dt[, user_per_week :=.N, by=week]
dt[, user_month_intensity := sum(user_week_level_var), by=.(user, month)]
# later, add some variable where it's available and scale the shift at the month level
dt = merge(dt, dt2, by='month')
dt[, lag_var := (user_week_level - shift(user_week_level)) / month_var, by=user]
```

But now I've silently broken the code because I don't realize that the by statement has a dependency on the sort order that isn't explicitly stated/enforced. Add in a dozen or more statements, each multiple lines so that the `setkey` and the lagged by aren't even on the same screen, and the problem is exacerbated. Multiply that by dozens of files each hundreds of lines long that feed data down some chain, and modifications become exponentially more difficult to manage.

Maybe you might argue that the modification clearly alters the logic of the lag operator and I should have caught it. You wouldn't be incorrect. I would certainly be annoyed at me for not catching that error.

But when the data insertion has nothing to do with the lag, I have no reason to read through all the statements after the merge and the lag operator is broken. The modification is locally correct but breaks things at a distance, which is my essential point. You can add locally correct code with the current syntax but still break things elsewhere:
```R
setkey(dt, user, week)
dt[, play_per_user := .N, by=user]
dt[, user_per_week :=.N, by=week]
# later, add some variable where it's available and scale the month 
# summary by something at the month level
dt = merge(dt, dt2, by='month')
dt[, user_month_intensity := sum(user_week_level_var * dt2_month_var),
    by=.(user, month)]
dt[, lag_var := user_week_level - shift(user_week_level), by=user]
```

Having the explicit sort, which is a part of the fundamental query logic, as part of the  query statement allows these kinds of modifications without having to re-read the entire series of statements after and checking the logic to make sure something isn't broken. That's an enormous boost to productivity. The only checks that I need to do is whether modifications to the variable definition break other code, but this can be done with a simple grep.

The alternative is to re-set the key before each query, which kind of breaks the point of data.table to reduce the typing needs of the user.

So, the state dependence in the current setup is fragile, and a syntactical guarantee of the full logic of the query is an advantageous addition to the ecosystem. Don't get me wrong, I understand this is a non-trivial change. But I do think it is worthwhile.

**Comment by franknarf1** [comment] 2018-05-21 20:17
The problem is

```
dt = merge(dt, dt2, by='month')
```

should never happen. Instead, use an update join:

```
dt[, dt2_var := dt2[.SD, on=.(month), x.dt2_var]]
```

This works if `dt` maintains the same number of rows before and after the merge you had in mind. (And if that number changes, the before and after tables really should not be called by the same name.) Since it's just another `:=` operation, we are not messing up `dt`'s keys at all here.

Side note: there's a bug/unsatisfied FR that may require using `copy(.SD)` instead of `.SD` in the code above sometimes.

**Comment by MichaelChirico** [comment] 2018-05-22 02:02
> Michael's suggestion--while certainly inventive!--I would argue is not great. It completely breaks the standard analogy of i being akin to WHERE like filtering (not to mention if I am using keys correctly, it's going to kill performance).

Hence, unfortunately this analogy is incomplete -- `i` is also used for _ad-hoc_ sorting. 

Not every table has a universal sort order -- this is the point of [secondary indices](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-secondary-indices-and-auto-indexing.html). For bigger tables, I often set a key and then 3 or 4 different secondary indices (especially common for me are swapped keys like `pickup, dropoff` and `dropoff, pickup`.

So, in your example, I might write:

 ```R
setkey(dt, user, week)
setindex(dt, month)
# ...
dt[order(month), lag_var := user_week_level - shift(user_week_level), by=user]
```

The performance of the last like should be almost the same as if the key were `user, month` without the `order` predicate (of course the sorting is happening in the `setindex` line, so this isn't much of a coup unless you're going to be doing several operations requiring the `month` sort order).

**Comment by jangorecki** [comment] 2018-05-22 03:18
> I mean, this is precisely why window functions in SQL have sorting operators instead of just depending on the sort order of some pre-existing index/key/storage order of the data.

Not only window functions but everything else that depends on order is also affected. RDBMSes cannot depend on sort order because they doesn't have any. SQL is inherently unordered. You can use clustered index, `row_number() over ()` field or view to `order by` but it technically it is just workaround.

**Comment by HughParsonage** [comment] 2018-05-22 07:55
As an aside, 

```r
dt = merge(dt, dt2, by='month', sort = FALSE)
```
 
sidesteps the problem.

**Comment by HughParsonage** [comment] 2018-05-22 08:30
I think you have a point, when you use a function like `shift` in `j`, you presume an ordering on `dt`, which you'd like to assert. I think Michael's use of `order` in `i` is canonical, however. Remember that `by` does not affect the result's order (`keyby` does). 

``` r
library(data.table)
set.seed(1)
dt <- data.table(store = sample(LETTERS[1:3], size = 100, replace = TRUE),
                 price = round(rlnorm(1000, 1), 2),
                 hour = round(runif(100, 8, 17), 3))

staff_by_store <- data.table(store = LETTERS[1:3], staff = 1:3)

dt1 <- copy(dt2 <- copy(dt3 <- copy(dt)))

dt1[order(hour), price_increase := price - shift(price), by = store]

setkey(dt2, store, hour)
dt2[, price_increase := price - shift(price), keyby = store]

dt3[staff_by_store, on = "store"
    ][order(hour),
      price_increase := price - shift(price),
      by = store][]
#>       store price   hour staff price_increase
#>    1:     A  4.05 12.651     1           3.14
#>    2:     A 11.39  9.405     1           9.23
#>    3:     A  2.37 14.181     1           1.24
#>    4:     A 30.01 11.607     1          27.35
#>    5:     A  2.61 11.572     1           1.97
#>   ---                                        
#>  996:     C  2.15 12.467     3          -0.73
#>  997:     C  1.08 16.035     3          -2.36
#>  998:     C 18.54 15.707     3          17.47
#>  999:     C  6.56  9.112     3           0.43
#> 1000:     C  4.42 13.839     3           2.76
```

<sup>Created on 2018-05-22 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).</sup>

--------------

In my view, however, jangorecki's comment is apposite: RDBMS are always ignorant of the ordering of the rows. So whenever you run a function that depends on the ordering you have to assert the ordering each time. `dplyr` has the function `order_by` for this purpose, but my approach when using `data.table` is to just `setkey` or `setorder` whenever I use functions that refer to other rows. 

Another thing to bear in mind is that if the a function requires a column within each group to be ordered,, you only need to assert that the column is sorted over the entire table before doing the grouped operation, not sorted for each group.

**Comment by jangorecki** [comment] 2020-05-18 14:40
If you don't want to set a key on table, the best I think is what @MichaelChirico suggested at the beginning. Finding order in data.table is very fast, so in normal code that should not cause issues. If you need to find order in loop, then to remove overhead you can use set indices on your data and #4458. Closing this issue because there are no any better ideas to address that, and IMO there is no really need. Both: `key` and `DT[order(), ...]` seems to be perfectly enough.

**Closed by jangorecki** 2020-05-18 14:40 UTC
