### ISSUE TITLE
`j`th expression doesn't handle `difftime` correctly

### ISSUE THREAD

**Issue by DavidArenburg** [Rdatatable/data.table#1296] opened 2015-08-27 11:02 UTC
This is related to this [SO](http://stackoverflow.com/a/32246954/3001626) asnwer. 

Consider the following data

```r
dt <- structure(list(SensorID = c(2L, 2L, 2L, 3L, 3L, 3L, 3L, 3L, 3L, 
3L), timestamp = structure(c(1438671392, 1438671398, 1438789520, 
1438671273, 1438671279, 1438671451, 1438671489, 1438671495, 1438671513, 
1438671519), class = c("POSIXct", "POSIXt"), tzone = "")), .Names = c("SensorID", 
"timestamp"), class = c("data.table", "data.frame"), row.names = c(NA, 
-10L))
```

Now I'm running a `difftime` calculation according to some condition in the `by`th argument. The variable of interest is `test`. I've added the actual values that we are subtracting to the  output too so it will be easier to spot the error

```r
setDT(dt)[, .(
              startTime = timestamp[1L], endTime = timestamp[.N],
              test = difftime(timestamp[.N], timestamp[1L], "mins")), 
       by = .(SensorID, cumsum(difftime(timestamp, shift(timestamp, fill = timestamp[1L]), "secs") > 60))]

#    SensorID cumsum           startTime             endTime          test
# 1:        2      0 2015-08-04 09:56:32 2015-08-04 09:56:38 6.000000 secs
# 2:        2      1 2015-08-05 18:45:20 2015-08-05 18:45:20 0.000000 secs
# 3:        3      1 2015-08-04 09:54:33 2015-08-04 09:54:39 6.000000 secs
# 4:        3      2 2015-08-04 09:57:31 2015-08-04 09:58:39 1.133333 secs
```

So as you can see in the fourth row, `test` is incorrect as the the difference between `startTime` and             `endTime` is actually in minutes rather in seconds. I've tried to play around by specifying `mins` instead of `secs` but without luck

**Comment by jangorecki** [comment] 2015-08-27 12:09
duplicate of #761

**Comment by arunsrinivasan** [comment] 2015-08-27 17:35
The third argument is `tz`. You'll have to specify `units = 'mins'`.

```r
> setDT(dt)[, .(
+     startTime = timestamp[1L], endTime = timestamp[.N],
+     test = difftime(timestamp[.N], timestamp[1L], units="mins")), 
+     by = .(SensorID, cumsum(difftime(timestamp, shift(timestamp, fill = timestamp[1L]), units="secs") > 60))]
#    SensorID cumsum           startTime             endTime          test
# 1:        2      0 2015-08-04 08:56:32 2015-08-04 08:56:38 0.100000 mins
# 2:        2      1 2015-08-05 17:45:20 2015-08-05 17:45:20 0.000000 mins
# 3:        3      1 2015-08-04 08:54:33 2015-08-04 08:54:39 0.100000 mins
# 4:        3      2 2015-08-04 08:57:31 2015-08-04 08:58:39 1.133333 mins
```

**Closed by arunsrinivasan** 2015-08-27 17:35 UTC

**Comment by DavidArenburg** [comment] 2015-08-27 17:50
Arghhhh noob mistake. Pardon.
