### ISSUE TITLE
Adding column names by reference doesn't work with list of data.table created in Parallel

### ISSUE THREAD

**Issue by ziyadsaeed** [Rdatatable/data.table#1272] opened 2015-08-14 17:22 UTC
My test list contains a data.table. Adding a column to the data.table with reference doesn't work. Below is a minimal reproducible code. The problem I have nailed down is that if the list of data tables is created in parallel then the bug appears. If it is created serially then the bug goes away

```R
# Platform Windows 8.1 with Revolution R Open 3.2.0
library("doParallel") #v1.0.8
registerDoParallel(2)

library("foreach") #v1.4.2
library("data.table") #v1.9.4

# Create test csv files
cat("I1, I2, I3
1,2,3
D1, D2, D3, D4
4,5,6,7
40,50,60,70",
  file = "test1.csv"
)

cat("I1, I2, I3
10,20,30
D1, D2, D3, D4
0.4,0.5,0.6,0.7
40,50,60,70",
    file = "test2.csv"
)

ReadData <- function(filename) {
  I.DT <- fread(filename, nrows = 1, header = TRUE, skip = 0)
  D.DT <- fread(filename)
  list("info" = I.DT, "data" = D.DT)
}

files <- c("test1.csv", "test2.csv")

# Create the list of DTs in parallel
parallel.list.of.DT <- foreach(file = files, .export = "fread") %dopar% ReadData(file)
lapply(parallel.list.of.DT, function(List) List$data[, D5 := 8L]) #D5 column shows up in console

# No D5 column is added
str(parallel.list.of.DT)

# Create the list of DTs in serial
serial.list.of.DT <- foreach(file = files, .export = "fread") %do% ReadData(file)
lapply(serial.list.of.DT, function(List) List$data[, D5 := 8L]) #D5 column shows up in console

# D5 column is indeed added
str(serial.list.of.DT)
```

**Comment by arunsrinivasan** [comment] 2015-08-14 17:36
Please provide a minimal example.

**Comment by ziyadsaeed** [comment] 2015-08-14 20:11
minimal reproducible code is now added. I have nailed down the problem. If the List.of.DT is created in parallel using %dopar%. Only then the bug appears. If it is created serially using %do% then the bug goes away.

**Comment by arunsrinivasan** [comment] 2015-08-14 20:16
Thanks for the update. Please try with the [devel version](https://github.com/Rdatatable/data.table/wiki/Installation) `1.9.5`. I can't reproduce it still.

PS: Always try on the latest commit before posting issues. It might have been already fixed.

**Comment by ziyadsaeed** [comment] 2015-08-14 21:08
the devel version has fread problem See this issue https://github.com/Rdatatable/data.table/issues/1267

**Comment by arunsrinivasan** [comment] 2015-08-14 21:12
I'm not sure I follow what that has got to do with this issue. You should be able to create another data set which doesn't require `fread()` (directly using `data.table()` function), and check with `1.9.5`. I'll close this as fixed in devel. Write back if you still get this issue on the devel version.

**Closed by arunsrinivasan** 2015-08-14 21:12 UTC
