### ISSUE TITLE
Duplicated embedded double-quotes not parsed as a single double-quote

### ISSUE THREAD

**Issue by dhersz** [Rdatatable/data.table#5088] opened 2021-07-29 16:40 UTC
Hi. I was dealing today with a csv that has embedded duplicated double-quotes to represent a single double-quote, but they were not actually parsed as a single double-quote. Here's a reproducible example:

```r
library(data.table)

tmp <- tempfile(fileext = ".csv")
writeLines('col,col2
"hi ""my friend""",2', tmp)

dt <- fread(tmp)
dt
#>                 col col2
#> 1: hi ""my friend""    2
```

As you can see, `base::read.csv()` and `readr::read.csv()` deals with this case as expected:

```r
df <- read.csv(tmp)
df
#>              col col2
#> 1 hi "my friend"    2

tbl <- readr::read_csv(tmp)
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   col = col_character(),
#>   col2 = col_double()
#> )
tbl
#> # A tibble: 1 x 2
#>   col                 col2
#>   <chr>              <dbl>
#> 1 "hi \"my friend\""     2
```

`fwrite()` by default writes embedded double quotes as two double quotes in a row, as documented in the `qmethod` param documentation:

> qmethod: A character string specifying how to deal with embedded double quote characters when quoting strings.
> - "escape" - the quote character (as well as the backslash character) is escaped in C style by a backslash, or
> - "double" (default, same as ‘write.csv’), in which case the double quote is doubled with another one. 
> 

So using `fread()` in conjunction with `fwrite()` in this situation produces some weird behaviour of ever-doubling double quotes:

```r
library(data.table)

tmp <- tempfile(fileext = ".csv")
writeLines('col,col2
"hi ""my friend""",2', tmp)

dt <- fread(tmp)
dt
#>                 col col2
#> 1: hi ""my friend""    2

fwrite(dt, tmp)
new_dt <- fread(tmp)
new_dt
#>                     col col2
#> 1: hi """"my friend""""    2

fwrite(new_dt, tmp)
newer_dt <- fread(tmp)
newer_dt
#>                             col col2
#> 1: hi """"""""my friend""""""""    2
```

I haven't played extensively with `fread()`'s `quote` parameter, so I don't know how it changes this behaviour. But anyway, I'd expect that by default `fread()` should read the default `fwrite()` output with no issues.

My session info:

```r
sessionInfo()
#> R version 4.1.0 (2021-05-18)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 20.04.2 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
#> 
#> locale:
#>  [1] LC_CTYPE=pt_BR.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=pt_BR.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=pt_BR.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=pt_BR.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] data.table_1.14.0
#> 
#> loaded via a namespace (and not attached):
#>  [1] rstudioapi_0.13   knitr_1.33        magrittr_2.0.1    hms_1.1.0        
#>  [5] R6_2.5.0          rlang_0.4.11      fansi_0.5.0       stringr_1.4.0    
#>  [9] styler_1.4.1      highr_0.9         tools_4.1.0       xfun_0.23        
#> [13] utf8_1.2.1        cli_2.5.0         withr_2.4.2       htmltools_0.5.1.1
#> [17] ellipsis_0.3.2    yaml_2.2.1        digest_0.6.27     tibble_3.1.2     
#> [21] lifecycle_1.0.0   crayon_1.4.1      readr_1.4.0       purrr_0.3.4      
#> [25] ps_1.6.0          vctrs_0.3.8       fs_1.5.0          glue_1.4.2       
#> [29] evaluate_0.14     rmarkdown_2.8     reprex_2.0.0      stringi_1.6.2    
#> [33] compiler_4.1.0    pillar_1.6.1      backports_1.2.1   pkgconfig_2.0.3
```

Cheers!

**Comment by MichaelChirico** [comment] 2021-10-05 03:17
Thanks for the report. I believe it's a duplicate of #4779; please re-open if that's not so.

**Closed by MichaelChirico** 2021-10-05 03:17 UTC
