### ISSUE TITLE
Extending data.table to support new spatial "simple feature" class?

### ISSUE THREAD

**Issue by mbacou** [Rdatatable/data.table#1900] opened 2016-11-05 00:02 UTC
Is anyone on the data.table team following discussions on extending data.table to support spatial geometries (see @barryrowlingson's open issue here https://github.com/edzer/sfr/issues/7). Could data.table indexing wizardry apply to spatial joins/operations as well?
Not an issue, just a question.

**Comment by MichaelChirico** [comment] 2016-11-05 00:39
I'm very much a fan of this. See #1310 -- this is a thing I've been dealing with a long time. If I had infinite free time, I had fanciful ideas of writing a new spatial package for R that has `data.table` as a backbone... alas...

**Comment by mbacou** [comment] 2016-11-05 21:29
Good, I was afraid this was on non one's radar! Pebesma's Simple Features looks very promising, would make sense to ensure they work well with data.table's structures as well, or can tap into data.table's improved memory management.

**Comment by MichaelChirico** [comment] 2019-08-16 02:53
Closing as a duplicate of #2273 since to channel things through that issue which is quite popular

**Closed by MichaelChirico** 2019-08-16 02:53 UTC
Labels: question
