### ISSUE TITLE
Possible issue (bug?) with RJSONIO

### ISSUE THREAD

**Issue by smartinsightsfromdata** [Rdatatable/data.table#1033] opened 2015-02-06 18:26 UTC
I just posted on stackoverflow a possible bug between data.table and RJSONIO [here](http://stackoverflow.com/questions/28372298/json-issue-bug-with-data-table-and-rjsonio-jsonlite)
Thanks for having a look at the issue.

**Comment by jangorecki** [comment] 2015-02-06 18:46
duplicate of #877

**Comment by arunsrinivasan** [comment] 2015-02-06 21:47
Thanks @smartinsightsfromdata, will take a look.
@jangorecki thanks for spotting the dup.

**Closed by arunsrinivasan** 2015-02-06 21:47 UTC

**Comment by smartinsightsfromdata** [comment] 2015-02-06 22:22
@arunsrinivasan thanks.  What has risen this is that while normally data.table work without problems with my package rpivotTable.
This works:
```R
rpivotTable(iris)
```
While this does not work:
```R
rpivotTable(data.table(iris))   # or rpivotTable(as.data.table(iris)) 
```
Misteriously, if I take off the dot from the colnames of iris, the above works again with no problems.

**Comment by smartinsightsfromdata** [comment] 2015-02-09 11:03
@jangorecki  and @arunsrinivasan As per my post above the issue is still open - as I still have the problem.  Please let me know if I should open another issue or if you plan to re-open this one. Tk

**Comment by jangorecki** [comment] 2015-02-09 15:45
Both cases (data.frame and data.table) works fine for me, both contains dots `.` in the column names:
```r
devtools::install_github("smartinsightsfromdata/rpivotTable")
library(rpivotTable)
rpivotTable(iris)
library(data.table)
rpivotTable(data.table(iris))
```
Can you highlight where is the issue?

**Comment by smartinsightsfromdata** [comment] 2015-02-09 16:40
Interesting.  I tried the above (re-loading from github the library) with my laptop with R RRO and on a debian box with CRAN R and in both cases ``` rpivotTable(data.table(iris)) ``` does not work, i.e. nothing gets displayed.
This is my session info on debian:
```R
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=C         LC_TIME=C            LC_COLLATE=C        
 [5] LC_MONETARY=C        LC_MESSAGES=C        LC_PAPER=C           LC_NAME=C           
 [9] LC_ADDRESS=C         LC_TELEPHONE=C       LC_MEASUREMENT=C     LC_IDENTIFICATION=C 

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rpivotTable_0.1.2.6 data.table_1.9.4    rdatamaps_0.1.4     dplyr_0.3.0.2      
[5] shiny_0.10.2.9006  

loaded via a namespace (and not attached):
 [1] DBI_0.3.1         R6_2.0.1          RCurl_1.95-4.5    RJSONIO_1.3-0     Rcpp_0.11.3      
 [6] assertthat_0.1    bitops_1.0-6      chron_2.3-45      devtools_1.6.1    digest_0.6.8     
[11] htmltools_0.2.6   htmlwidgets_0.3.2 httpuv_1.3.2      httr_0.6.1        magrittr_1.5     
[16] mime_0.2          parallel_3.1.2    plyr_1.8.1        reshape2_1.4.1    stringr_0.6.2    
[21] tools_3.1.2       xtable_1.7-4      yaml_2.1.13  
```

**Comment by jangorecki** [comment] 2015-02-09 16:44
I would suggest to try:
 - data.table `1.9.5`
 - R in command line instead RRO

**Comment by smartinsightsfromdata** [comment] 2015-02-09 17:21
@jangorecki  @arunsrinivasan data.table 1.9.5 indeed fix the issue!!
Many thanks in confirming my trust in data.table (and in the great team working on it).
Is data.table ```1.9.6``` expected soonish??
