### ISSUE TITLE
Bug when doing aggregation and if else statement

### ISSUE THREAD

**Issue by solvith** [Rdatatable/data.table#3521] opened 2019-04-23 13:10 UTC
Reproducible example:
`test<-data.table(GRP_1=c(1,1,2,3),GRP_2=c(1,1,1,1),B=c(3,4,5,3),C=c(5,6,7,3),D=c(1,1,1,1),E=c(1,1,1,1))
#reordered version
faulty<-test[c(3,4,1,2),]

lapply(list(test,faulty),function(dt){
  dt[GRP_1>0,{
    if (.N>1){
      #Aggregation required
      .(B=max(B),
        C=min(C),
        D=min(D),
        E=min(E),
        z=5,
        test='type1')
    }else{
      #Aggregation not required
      .(B,
        C,
        D,
        E,
        z=NaN,
        test='type2')
    }
  },.(GRP_1,GRP_2)]
})

`

Note: you pass in the same data.table with different orders. The second case, the output's column names go missing

![image](https://user-images.githubusercontent.com/6875130/56583421-1b968200-660c-11e9-9d2a-b6266bced765.png)

Thanks a lot open source community

**Comment by solvith** [comment] 2019-04-23 13:10
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_Singapore.1252  LC_CTYPE=English_Singapore.1252    LC_MONETARY=English_Singapore.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Singapore.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] plyr_1.8.4        XXX.MM_1.0.0      httr_1.3.1        dplyr_0.7.4       assertthat_0.2.0  knitr_1.17        digest_0.6.12    
 [8] RODBC_1.3-13      PKI_0.1-3         base64enc_0.1-3   DBI_1.0.0         anytime_0.3.0     pacman_0.4.6      xts_0.9-7        
[15] zoo_1.7-13        data.table_1.10.4

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16       highr_0.6          pillar_1.2.2       bindr_0.1.1        bitops_1.0-6       tools_3.3.1       
 [7] lubridate_1.7.4    evaluate_0.10.1    tibble_1.4.2       gtable_0.2.0       lattice_0.20-33    pkgconfig_2.0.1   
[13] rlang_0.2.0        rstudioapi_0.7     yaml_2.1.18        binman_0.1.0       bindrcpp_0.2.2     stringr_1.3.1     
[19] caTools_1.17.1     grid_3.3.1         glue_1.2.0         R6_2.2.2           XML_3.98-1.11      RSelenium_1.7.1   
[25] semver_0.2.0       ggplot2_2.2.1      magrittr_1.5       scales_0.5.0       ggthemes_3.2.0     RApiDatetime_0.0.3
[31] colorspace_1.2-6   labeling_0.3       stringi_1.1.7      openssl_0.9.9      lazyeval_0.2.0     munsell_0.4.3     
[37] wdman_0.2.2

**Comment by franknarf1** [comment] 2019-04-23 13:55
I guess the authors would not call it a bug. Your code does not explicitly assign names in your `else` clause. There are a couple situations where names will be auto-assigned:

- if your first by= group has names (as with test)
- if you have the form `j = .(...)`

but you are nesting the `.(...)` and so it doesn't have that feature/shortcut:

```
test[1, if (TRUE){.(
        B,
        C,
        D,
        E,
        z=NaN,
        test='type2'
    )}, by=.(GRP_1,GRP_2)]

   GRP_1 GRP_2           z  test
1:     1     1 3 5 1 1 NaN type2
```

Btw, you can use triple backticks to set aside blocks of code in these comments.

**Comment by solvith** [comment] 2019-04-24 01:12
Thanks for the quick comment,

In that case , why cant the logic be to take the column name as it is...
It works without the aggregation.

test[1, {
    1 + 1
    .(
        B,
        C,
        D,
        E,
        z=NaN,
        test='type2'
    )}]

   V1 V2 V3 V4   z  test
1:  3  5  1  1 NaN type2

my fix now is to do this.. which i think might be a little verbose

test[1, {
    1 + 1
    .(
        B=B,
        C=C,
        D=D,
        E=E,
        z=NaN,
        test='type2'
    )}, by=.(GRP_1,GRP_2)]

**Comment by MichaelChirico** [comment] 2019-04-24 02:35
I guess the core of your Q is a duplicate of #2478

**Closed** 2019-04-24 09:14 UTC
Labels: duplicate
