### ISSUE TITLE
Unable to read csv file via fread when using default settings select=NULL

### ISSUE THREAD

**Issue by JauntyJJS** [Rdatatable/data.table#2045] opened 2017-02-28 03:54 UTC
Hi,

I was using data.table version 1.10.4 to read this simple csv file below.

[Annotations-384HDR.csv.txt](https://github.com/Rdatatable/data.table/files/805678/Annotations-384HDR.csv.txt)

I realized that fread gives an error when I insert the default value of the "select=NULL" input provided in the documentation https://www.rdocumentation.org/packages/data.table/versions/1.10.4/topics/fread

Below is a reproducible example

> data<-fread(input="Annotations-384HDR.csv")
> data
     row col WellID WellType ReplicateID SectionID StepID SolutionName
  1:   1   1    A01       NC           1         0      1           NA
  2:   1   2    A02       RC           1         0      1           NA
  3:   1   3    A03       RC           1         0      1           NA
  4:   1   4    A04       RC           1         0      1           NA
  5:   1   5    A05       RC           1         0      1           NA
 ---
> data<-fread(input="Annotations-384HDR.csv",select=NULL)
Error in setcolorder(ans, reorder) :
  neworder is length 0 but x has 10 columns.

Looking the source code of fread, I saw on line 125

    if (!missing(select)) {
        # fix for #1445
        if (is.numeric(select)) {
            reorder = if (length(o <- forderv(select))) o else seq_along(select)
        } else {
            reorder = select[select %chin% names(ans)]
            # any missing columns are warning about in fread.c and skipped
        }
        setcolorder(ans, reorder)
    }

If this is the case, the documentation should not have "select=NULL" but just "select" as in the input for "file" and "col.names" as "select=NULL" means "select" is no longer missing.

Regards,
Jeremy

**Comment by jangorecki** [comment] 2017-03-05 11:51
duplicate of #2007

**Closed by jangorecki** 2017-03-05 11:51 UTC
