### ISSUE TITLE
Stochastic behavior with fread on string

### ISSUE THREAD

**Issue by rexdouglass** [Rdatatable/data.table#2089] opened 2017-03-29 16:18 UTC
Using fread to parse a raw string, of length 987,105. fread exhibits stochastic behavior, running the same command on the same input throws an error sometimes but not others. Details below as this is really bizarre and worth flagging, will resolve and update if I can get it to go away.

Here's a string that throws the error
http://s000.tinyupload.com/index.php?file_id=43086932232163217721

Here's reproducible code
library(data.table)
load(file="temp.Rdata")
data <- fread(temp, sep=",",sep2="", header = FALSE, quote="\'", verbose=TRUE)

And here is sample output from running the above code several times
#Most of the time runs without error as below
>   data <- fread(temp2, sep=",",sep2="", header = FALSE, quote="\'", verbose=TRUE)
None of the 1 'na.strings' are numeric (such as '-9999') which is normal and best for performance.
Input contains a \n (or is ""). Taking this to be text input (not a filename)
Detected eol as \n only (no \r afterwards), the UNIX and Mac standard.
Positioned on line 1 starting: <<1020495,0,'Adel_(GA)','',0,1,1>>
Using supplied sep ','
  sep==','(ascii 44)  with 101 lines of 15 fields using quote rule 0
Detected 15 columns on line 1. This line is either column names or first data row (first 30 chars): <<1020495,0,'Adel_(GA)','',0,1,1>>
'header' changed by user from 'auto' to FALSE
Number of jump points = 1 because 11678 startSize * 10 NJUMPS * 48 threads * 2 = 11210880 >= 1020356 bytes from line 1 to eof
Type codes (jump 00): 114411134411144  Quote rule 0
Sampled 8704 rows at 1 jump points including the very beginning and very end
Mean length: 117.2   Bytes from row 1 to eof: 1020356   Estimated nrow: 8705
StdDev length: 5.4   Min length: 104   Max length: 221
Initial alloc = 9704 (+11%) using bytes/max(mean-2*sd,min)
All rows were sampled since nrow is small so we know nrow=8704 exactly
Type codes: 114411134411144 (after applying colClasses and integer64)
Type codes: 114411134411144 (after applying drop or select, if supplied)
Allocating 15 column slots (15 - 0 dropped)
madvise sequential: Cannot allocate memory
Reading data with 1 jump points and 48 threads
1 jump points read 8704 rowsRead 8704 rows. Exactly what was estimated and allocated up front
   0.000s (  1%) Memory map
   0.000s (  1%) sep, ncol and header detection
   0.008s ( 26%) Column type detection using 8704 sample rows from 1 jump points
   0.000s (  1%) Allocation of 8704 rows x 15 cols (0.001GB) in RAM
   0.000s (  0%) madvise sequential
   0.022s ( 71%) Reading data
   0.031s        Total

#Sometimes throws an error like this
> data <- fread(temp, sep=",",sep2="", header = FALSE, quote="\'", verbose=TRUE)
None of the 1 'na.strings' are numeric (such as '-9999') which is normal and best for performance.
Input contains a \n (or is ""). Taking this to be text input (not a filename)
Detected eol as \n only (no \r afterwards), the UNIX and Mac standard.
Positioned on line 1 starting: <<1020495,0,'Adel_(GA)','',0,1,1>>
Using supplied sep ','
  sep==','(ascii 44)  with 101 lines of 15 fields using quote rule 0
  sep==','(ascii 44)  with 1223929369 lines of 166016304 fields using quote rule 3
Error in fread(temp, sep = ",", sep2 = "", header = FALSE, quote = "'",  : 
  Internal error: first line has field count 15 but expecting 166016304

#Or throws an error like this
> data <- fread(temp, sep=",",sep2="", header = FALSE, quote="\'", verbose=TRUE)
None of the 1 'na.strings' are numeric (such as '-9999') which is normal and best for performance.
Input contains a \n (or is ""). Taking this to be text input (not a filename)
Detected eol as \n only (no \r afterwards), the UNIX and Mac standard.
Positioned on line 1 starting: <<1020495,0,'Adel_(GA)','',0,1,1>>
Using supplied sep ','
  sep==','(ascii 44)  with 101 lines of 15 fields using quote rule 0
  sep==','(ascii 44)  with 34797272 lines of 166023955 fields using quote rule 3
Error in fread(temp, sep = ",", sep2 = "", header = FALSE, quote = "'",  : 
  Internal error: first line has field count 15 but expecting 166023955

> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 25 (Workstation Edition)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] jsonlite_1.3      readr_1.0.0       data.table_1.10.5 doParallel_1.0.10 foreach_1.4.3     iterators_1.0.8  

loaded via a namespace (and not attached):
[1] compiler_3.3.2   R6_2.2.0         assertthat_0.1   tools_3.3.2      tibble_1.2       Rcpp_0.12.10     codetools_0.2-15

**Comment by rexdouglass** [comment] 2017-03-29 16:32
Update: Rolling back to the version on cran resolves the error

remove.packages("data.table")         # First remove the current version
install.packages("data.table")  

#data.table_1.10.4

**Comment by st-pasha** [comment] 2017-07-06 19:04
After running this example 11004 times, I could not reproduce the error. It appears the problem is already fixed in the latest version.

**Closed by st-pasha** 2017-07-06 19:04 UTC
Labels: fread
