### ISSUE TITLE
strip.white trailing [REQUEST]

### ISSUE THREAD

**Issue by masip85** [Rdatatable/data.table#1820] opened 2016-08-21 16:07 UTC
If I have got a header name like "X Y", by default,the result of fread has a header called "X Y". Spaces are not changed by points like read.csv does by default. So after fread I've got to do ...
setnames(DT, make.names(colnames(DT)))
... to fix it. Could it be an option? Does it exist?

data.table package 1.9.6

**Comment by MichaelChirico** [comment] 2016-08-21 16:21
could you please provide the first several lines of the file?

**Comment by masip85** [comment] 2016-08-21 17:33
The file is this one:
 https://data.cityofchicago.org/api/views/r5kz-chrr/rows.csv?accessType=DOWNLOAD

**Comment by masip85** [comment] 2016-08-21 19:51
I'm sorry, is read.csv which does that by default, but no fread. Let me edit it, and I will change it to request.

**Comment by MichaelChirico** [comment] 2016-08-22 15:49
Please install the development version, which has the new `check.names` argument. I get this from your file:

```
names(fread("~/Downloads/Business_Licenses.csv", check.names = TRUE))
#  [1] "ID"                                "LICENSE.ID"                       
#  [3] "ACCOUNT.NUMBER"                    "SITE.NUMBER"                      
#  [5] "LEGAL.NAME"                        "DOING.BUSINESS.AS.NAME"           
#  [7] "ADDRESS"                           "CITY"                             
#  [9] "STATE"                             "ZIP.CODE"                         
# [11] "WARD"                              "PRECINCT"                         
# [13] "WARD.PRECINCT"                     "POLICE.DISTRICT"                  
# [15] "LICENSE.CODE"                      "LICENSE.DESCRIPTION"              
# [17] "LICENSE.NUMBER"                    "APPLICATION.TYPE"                 
# [19] "APPLICATION.CREATED.DATE"          "APPLICATION.REQUIREMENTS.COMPLETE"
# [21] "PAYMENT.DATE"                      "CONDITIONAL.APPROVAL"             
# [23] "LICENSE.TERM.START.DATE"           "LICENSE.TERM.EXPIRATION.DATE"     
# [25] "LICENSE.APPROVED.FOR.ISSUANCE"     "DATE.ISSUED"                      
# [27] "LICENSE.STATUS"                    "LICENSE.STATUS.CHANGE.DATE"       
# [29] "SSA"                               "LATITUDE"                         
# [31] "LONGITUDE"                         "LOCATION"  
```

Development version can be installed with

    install.packages("data.table", type = "source", repos = "http://Rdatatable.github.io/data.table")

**Comment by MichaelChirico** [comment] 2016-08-22 15:51
@arunsrinivasan duplicate of #1027

**Comment by arunsrinivasan** [comment] 2016-08-26 16:21
`check.names` argument has been added to `fread` since v1.9.6. Set it to `TRUE`.

**Closed by arunsrinivasan** 2016-08-26 16:21 UTC

**Comment by MichaelChirico** [comment] 2016-08-26 17:07
@arunsrinivasan the `check.names` in 1.9.6 doesn't incorporate David Arenburg's improvement which fixes this issue... anyway, it is indeed fixed on development.

**Comment by masip85** [comment] 2016-10-10 07:25
Right. Thanks,
