### ISSUE TITLE
Error: `length of 'dimnames' [1] not equal to array extent` when subsetting rows of type `period`

### ISSUE THREAD

**Issue by anasem** [Rdatatable/data.table#5469] opened 2022-09-17 16:28 UTC
Sorry if this has been reported before, I searched the issues but could not find anything.

`#` [`Minimal reproducible example`](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example); please be sure to set `verbose=TRUE` where possible!

```R
library(data.table)
library(lubridate)

dt2 <- data.table(dur = c(period(10), period(5), period(3), period(100)))

dt2[1,]
dt2[1:3,]
# Error in dimnames(x) <- dn : 
#   length of 'dimnames' [1] not equal to array extent 

# This works
dt2[1:4,]

# This also works but have strange output
dt2[, dur]

```

`#` `Output of sessionInfo()`
```
# R version 4.2.1 (2022-06-23)
# Platform: x86_64-pc-linux-gnu (64-bit)
# Running under: Manjaro Linux
# 
# Matrix products: default
# BLAS/LAPACK: /opt/intel/oneapi/mkl/2022.1.0/lib/intel64/libmkl_gf_lp64.so.2
# 
# locale:
#  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8    
#  [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
#  [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
# 
# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
# [1] lubridate_1.8.0   data.table_1.14.2 nvimcom_0.9-132   colorout_1.2-2   
# 
# loaded via a namespace (and not attached):
# [1] compiler_4.2.1 generics_0.1.3 tools_4.2.1   
```

**Comment by MichaelChirico** [comment] 2022-09-19 07:02
I believe it's a duplicate of #4315

**Closed by MichaelChirico** 2022-09-19 07:02 UTC
