### ISSUE TITLE
Shift needs to consider the time variable 

### ISSUE THREAD

**Issue by dazhwu** [Rdatatable/data.table#5259] opened 2021-11-11 18:18 UTC
Consider the following code:

```r
library(data.table)

DT = data.table(year=c(2010, 2010, 2009, 2011,2011,2011), id=c(1,2,3,1,2,3), value=c(2,5,6,8,2,6))
print(DT)

# year id value
# 1: 2010 1 2
# 2: 2010 2 5
# 3: 2009 3 6
# 4: 2011 1 8
# 5: 2011 2 2
# 6: 2011 3 6

DT[, lag1 := shift(value, 1), by=.(id)]
print(DT)

# year id value lag1
# 1: 2010 1 2 NA
# 2: 2010 2 5 NA
# 3: 2009 3 6 NA
# 4: 2011 1 8 2
# 5: 2011 2 2 5
# 6: 2011 3 6 6
```

regarding the last record, its lag1 is supposed to be NA, because there is no data for year 2010 for that particular id.

The following code will produce the result correctly:
```r
temp=copy(DT)
temp[, `:=`(year=year+1, lag1=value)]
temp=temp[, .(id, year, lag1)]

DT=merge(DT, temp, by=c("id", "year"), all.x=TRUE)
setorder(DT, id, year)
print(DT)

# id year value lag1
# 1: 1 2010 2 NA
# 2: 1 2011 8 2
# 3: 2 2010 5 NA
# 4: 2 2011 2 5
# 5: 3 2009 6 NA
# 6: 3 2011 6 NA
```
But it is not very handy.

**Comment by ben-schwen** [comment] 2021-11-11 20:07
I cannot really see a feature request, bug or documentation error here. What you want to achieve can be achieved without a merge using

```r
DT = data.table(year=c(2010, 2010, 2009, 2011,2011,2011), id=c(1,2,3,1,2,3), value=c(2,5,6,8,2,6))
DT
#>    year id value
#> 1: 2010  1     2
#> 2: 2010  2     5
#> 3: 2009  3     6
#> 4: 2011  1     8
#> 5: 2011  2     2
#> 6: 2011  3     6
setorder(DT, id, year)

DT[, c("lag_year", "lag1") := shift(.(year, value), 1), by=id]
DT[(year - lag_year > 1), lag1 := NA]
DT
#>    year id value lag_year lag1
#> 1: 2010  1     2       NA   NA
#> 2: 2011  1     8     2010    2
#> 3: 2010  2     5       NA   NA
#> 4: 2011  2     2     2010    5
#> 5: 2009  3     6       NA   NA
#> 6: 2011  3     6     2009   NA
DT[, lag_year := NULL]
```

**Comment by dazhwu** [comment] 2021-11-11 23:43
Thank you.

**Comment by jangorecki** [comment] 2021-11-12 10:49
Sounds like duplicate of https://github.com/Rdatatable/data.table/issues/3241

**Closed by jangorecki** 2021-11-12 10:49 UTC
