### ISSUE TITLE
[Request] Warn when as.data.table encounters POSIXct/POSIXlt

### ISSUE THREAD

**Issue by TimeLordmbw** [Rdatatable/data.table#1289] opened 2015-08-25 18:47 UTC
A warning generated by as.data.table upon encountering POSIXlt formatting would have saved me several minutes. A FAQ entry relating to this might be useful to some, as well.

Background: I recently converted a data frame containing a date/time column to a data table (using as.data.table) in order to generate a grouped mean. The data frame silently converts, but then when trying to generate the means (using DT[, lapply(.SD,mean), "Key_column"]), I get the dreaded (by me) error "GForce mean can only be applied to columns, not .SD or similar." After narrowing down the problem to a single column, I find that manipulating it yields the fairly cryptic (to me) warning: "In is.na(secs) : is.na() applied to non-(list or vector) of type 'NULL'". Once I figured it out (via stackoverflow), it isn't too difficult to work around, it just took a little while to find the problem.

**Comment by arunsrinivasan** [comment] 2015-08-25 21:28
Duplicate of #646. We haven't gotten to it yet. I'd be glad to review PRs.

**Closed by arunsrinivasan** 2015-08-25 21:28 UTC

**Comment by arunsrinivasan** [comment] 2016-03-05 00:45
#646 is fixed now.. POSIXlt columns when present returns a warning followed by conversion to POSIXct.
