### ISSUE TITLE
[question, feature]column types determined by fread and read.table are different

### ISSUE THREAD

**Issue by r-learner** [Rdatatable/data.table#1168] opened 2015-06-03 20:06 UTC
I am new to data.table and fread. I used read.table before, but it is slow. I am trying to use fread, but I wish it could detect the column type more robustly. Below is a very dirty data column (in reality you may not have such a column), which is numeric in some sense.
```R
> library(data.table)
> system("cat foo2.csv")
"var 1"
"     -20000.09   "
"500         "
   +10.
     -20000.09
-20000.09
     500.
500.0
1.
.1
0.1
+500
-500
> dt <- read.table("foo2.csv", header=TRUE)
> sapply(dt, class)
    var.1
"numeric"
> dt
       var.1
1  -20000.09
2     500.00
3      10.00
4  -20000.09
5  -20000.09
6     500.00
7     500.00
8       1.00
9       0.10
10      0.10
11    500.00
12   -500.00
> dt <- fread("foo2.csv", header=TRUE)
> sapply(dt, class)
      var 1
"character"
> dt
                var 1
 1:      -20000.09
 2:      500
 3:              +10.
 4:         -20000.09
 5:   -20000.09
 6:              500.
 7:    500.0
 8:                1.
 9:                .1
10:               0.1
11:              +500
12:              -500
>
```
It seems that read.table did a better job than fread in the case.  What options can I add to fread to let it act as read.table if fread provides the opitons?

I know the fread function uses first 5, middle 5, and last 5 rows to determine the column type, but in my case, it is more reasonable to define the column is numeric. In my opinion, the left/right spaces from columns make troubles, it seems that fread should trim left/right spaces in each column, since these spaces make no sense in data, and no contributions to understand data.

**Comment by arunsrinivasan** [comment] 2015-09-17 19:21
Quoted columns aren't checked/converted (yet). But I find `1.` to be very odd. I can think of many other fringe cases like that, e.g., `1..`, `1  .` `,1` etc.. I don't think `fread()` needs to read such strange files

**Comment by arunsrinivasan** [comment] 2016-03-06 16:48
Also duplicate of #572.

**Closed by arunsrinivasan** 2016-03-06 16:48 UTC
Labels: fread
