### ISSUE TITLE
one column being needed both in grouping and in j

### ISSUE THREAD

**Issue by ieiwk** [Rdatatable/data.table#2379] opened 2017-09-23 11:29 UTC
Dear,

data.table is cool. I am learning using it.

Here is a situiation I found no quick solution:
there is one column for which I want to use its sub-string in _by_, while in _j_ I want to access its other parts.

Please help. Thanks a lot!

**Comment by MichaelChirico** [comment] 2017-09-23 11:32
look into .BY. please use the issue tracker for package bugs/feature
requests instead of tutorial help -- stackoverflow will be happy to help as
well as much faster.

cheers!!

**Comment by ieiwk** [comment] 2017-09-23 11:37
Thanks! But .BY is only the sub-string I used to group, while in _j_ I need to access parts other than that sub-string...

**Comment by ieiwk** [comment] 2017-09-23 11:38
Also for the issue tracker, am I using it already and correctly?

**Comment by renkun-ken** [comment] 2017-09-23 13:24
Duplicate of #1427

**Comment by ieiwk** [comment] 2017-09-23 13:52
OK, now I have figured it out. I can use _.I_ in _j_.

**Closed** 2017-09-27 02:22 UTC
