### ISSUE TITLE
Columns of `i` cannot be found when using `by` and joining

### ISSUE THREAD

**Issue by sritchie73** [Rdatatable/data.table#2581] opened 2018-01-21 11:04 UTC
A simple example:

```{r}
dt_left <- data.table(id=1:5, letters=letters[1:5])
dt_right <- data.table(id=1:7, values=rnorm(7), group=sample(c("A", "B"), 7, TRUE))
```

Accessing the "values" column works when joining and `by` is not specified:

```{r}
dt_left[dt_right, on=.(id), j=.(sum(values))]
#           V1
# 1: 0.2588653
```

Any value in `by` means I can now no longer access any columns of `dt_right` in `j`: 

```{r}
# cannot find group column from dt_right:
dt_left[dt_right, on=.(id), j=.(sum(values)), by=.(group)] 
 
# cannot find "values" column, "letters" is from dt_left:
dt_left[dt_right, on=.(id), j=.(sum(values)), by=.(letters)] 
```

**Comment by MichaelChirico** [comment] 2018-01-22 02:51
Have you read:

https://stackoverflow.com/questions/27004002/eachi-in-data-table/27004566#27004566

**Comment by sritchie73** [comment] 2018-01-22 03:44
I've seen that before, but I don't see how it impacts the problem above.

**Comment by franknarf1** [comment] 2018-01-22 21:17
Dupe of https://github.com/Rdatatable/data.table/issues/733 ?

**Comment by sritchie73** [comment] 2018-01-23 04:10
@franknarf1 you're correct. Good to have confirmation this is intentional behaviour/a yet to be implemented feature, and not just a fundamental error in my mental model of how data.table works.

**Closed** 2018-01-27 01:57 UTC
