### ISSUE TITLE
can enable reading from a connection?

### ISSUE THREAD

**Issue by ieiwk** [Rdatatable/data.table#4921] opened 2021-03-04 03:00 UTC
Hi,

I wonder if reading from a connection can be enabled.

Thanks.

**Comment by ben-schwen** [comment] 2021-03-04 11:12
Thanks for the request! Duplicate of #561 

Please feel free to add support on that main issue, or reopen this if I'm in error in assigning the duplicate label

**Closed by ben-schwen** 2021-03-04 11:12 UTC
Labels: duplicate

**Comment by ieiwk** [comment] 2021-03-05 02:00
thanks for redirection!

**Comment by MichaelChirico** [comment] 2021-03-05 07:18
Thanks Ben!
