### ISSUE TITLE
[R-Forge #1984] Functional Queries

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#641] opened 2014-06-08 13:16 UTC
Submitted by: Yike Lu; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=1984&group_id=240&atid=978)

Add a function, perhaps dtquery=function(DT, ...) DT[...]

I just checked, and this syntax indeed works (it was a very easy function program). This would allow higher order abstractions as part of the standard implementation.

**Comment by jangorecki** [comment] 2015-07-20 00:49
Are `...` essential here?
It could be simply done by
```r
dtquery = data.table:::`[.data.table`
```
In the worst case some `if(missing(` for each `[.data.table` arg.

**Comment by MichaelChirico** [comment] 2019-08-19 15:47
I'm not sure there's any demand for this?

Seems most suited to `%>%` chains, so perhaps it could be added in `dtplyr` instead?

**Comment by jangorecki** [comment] 2019-11-01 10:59
something similar just spotted in the wild: https://stackoverflow.com/a/58652478/2490497

**Comment by dcaseykc** [comment] 2020-11-02 23:09
Having an exported version of `[.data.table` (via dtquery) would be helpful for [attempts to extend data.table](https://stackoverflow.com/questions/64269066/how-to-adjust-j-in-data-table-without-breaking-data-tables-custom-evaluatio) without running afoul of warnings about using `:::` in packages.

**Comment by avimallu** [comment] 2021-05-11 10:26
@jangorecki, this will be closed with #4304, or is it completely different? This SO examples linked seem to point to it serving the same purpose.

**Comment by jangorecki** [comment] 2021-05-11 10:44
not really

**Comment by MichaelChirico** [comment] 2021-05-20 18:39
IINM this is duplicate of #4872 which now has much more traffic; closing this one

**Closed by MichaelChirico** 2021-05-20 18:39 UTC
Labels: duplicate, feature request
