### ISSUE TITLE
by= ignored if there is no j expression

### ISSUE THREAD

**Issue by st-pasha** [Rdatatable/data.table#3263] opened 2019-01-09 19:20 UTC
```R
> DT = data.table(A=c(1,2,1,2,1,2), B=c(1,2,1,1,2,2))
> DT[, , by=A+B]  # result ignores the by= clause
   A B
1: 1 1
2: 2 2
3: 1 1
4: 2 1
5: 1 2
6: 2 2
> DT[, .(A, B), by=A+B]  # this is correct, DT[,,by=A+B] expected to be same as this
   A + B A B
1:     2 1 1
2:     2 1 1
3:     4 2 2
4:     4 2 2
5:     3 2 1
6:     3 1 2
```

**Comment by franknarf1** [comment] 2019-01-09 20:03
Related https://github.com/Rdatatable/data.table/issues/1269#issuecomment-131181704 and later comments

**Comment by MichaelChirico** [comment] 2019-01-09 23:40
Not sure I follow your reasoning for your second example... is that for convenience? easy to imagine I have some complicated expression `by = f(x1, .., xn)` and don't really care about the inputs to `f`.

**Comment by MichaelChirico** [comment] 2019-01-10 01:42
definitely agreed, and in fact I think this is natural syntax for just
returning the groups. but in that case this issue is a duplicate of the
issue Frank referenced IIUC. the novelty here was your second example which
I don't quite follow

**Comment by st-pasha** [comment] 2019-01-10 02:10
But the second example already does the right thing: `DT[, .(A,B), by=A+B]` means group the data.table by expression `A+B`, then select columns `A` and `B`. And that's exactly what it does, also adding the group-by column `A+B` at the front.

**Comment by mattdowle** [comment] 2019-01-10 02:41
Please use dev not release when reporting bugs.
```R
> DT = data.table(A=c(1,2,1,2,1,2), B=c(1,2,1,1,2,2))
> DT[, , by=A+B] 
...
Warning message:
In `[.data.table`(DT, , , by = A + B) :
  i and j are both missing so ignoring the other arguments
>
```

**Comment by MichaelChirico** [comment] 2019-01-10 02:44
@st-pasha sorry I see the confusion, I was referring to your comment:

> this is correct, `DT[,,by=A+B]` expected to be same as this

**Comment by mattdowle** [comment] 2019-01-11 14:59
Closing because the warning is there and that was the focus of this issue.
Can follow up in #3262 perhaps.

**Closed by mattdowle** 2019-01-11 14:59 UTC
Labels: bug
