### ISSUE TITLE
Online vignettes don't match Rmd files

### ISSUE THREAD

**Issue by OfekShilon** [Rdatatable/data.table#5582] opened 2023-01-23 14:24 UTC
[Online vignettes at CRAN](https://cran.r-project.org/web/packages/data.table/vignettes/) list their date as 2022-11-15, but the contents seem severely outdated.

As a concrete example [faq 1.5](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-faq.html#i-assigned-a-variable-mycol-x-but-then-dt-mycol-returns-x.-how-do-i-get-it-to-look-up-the-column-name-contained-in-the-mycol-variable) lists the option `WhenJisSymbolThenCallingScope`, which was [removed in v1.10.2](https://github.com/Rdatatable/data.table/blob/master/NEWS.md?plain=1#L2098)  (31 Jan 2017 !) 

When I build the package locally the html contents are up-to-date.

**Comment by tdhock** [comment] 2023-01-24 22:01
This seems like a duplicate of https://github.com/Rdatatable/data.table/issues/5538 which is a confusion about recent patch releases to CRAN (which were hot fixes and not supposed to provide new features/vignettes). Please close if that is the case.

**Comment by OfekShilon** [comment] 2023-01-25 12:45
@tdhock the recent patches and the last major version did include valid Rmd files, it seems the *online* vignettes are just not built from them.  Based on the specific `WhenJisSymbolThenCallingScope` example, seems the last time the online vignettes were built was <=2016. 
Am I missing something?

**Comment by MichaelChirico** [comment] 2024-07-16 00:18
I no longer see `WhenJisSymbolThenCallingScope` in the CRAN vignette, so I assume this was fixed by a subsequent CRAN release. Please open a new issue if you find any more outdated info in the vignettes.

**Closed by MichaelChirico** 2024-07-16 00:18 UTC
