### ISSUE TITLE
Typo: error using "on"

### ISSUE THREAD

**Issue by asantucci** [Rdatatable/data.table#1756] opened 2016-06-28 00:48 UTC
require(data.table)
dt2 <- dt1 <- data.table(x=1)
dt1[dt2, on = 1]

Error in `[.data.table`(dt1, dt2, on = 1) : 
  'on' argument should be a named atomic vector **oc** column names indicating which columns in 'i' should be joined with which columns in 'x'.

I think **oc** should be **of**?

Thanks for letting me ask a bunch of questions today, it was great to meet you both at the useR conference.

**Comment by jangorecki** [comment] 2016-06-28 10:09
Thanks for reporting. It seems to be already fixed in [latest devel](https://github.com/Rdatatable/data.table/blob/master/R/data.table.R#L578), please re-open if you are able to reproduce it on latest devel.

**Closed by jangorecki** 2016-06-28 10:09 UTC
