### ISSUE TITLE
rmarkdown_1.0.9016 breaks printing behavour of data.tables (:=)

### ISSUE THREAD

**Issue by and3k** [Rdatatable/data.table#1869] opened 2016-10-07 08:09 UTC
Hi,

I upgraded to the the RStudio beta release which includes rmarkdown_1.0.9016, an now the assign operator (:=) causes in the data.table to be printed.

```
require(data.table)              # print?
DT = data.table(x=1:3, y=4:6)    # no
DT                               # yes
DT[, z := 7:9]                   # no <--- is printed!!!
print(DT[, z := 10:12])          # yes
if (1 < 2) DT[, a := 1L]         # no <--- is printed!!!
DT                               # yes
```

Thanks,

Bela

**Comment by shrektan** [comment] 2016-10-08 05:12
I can reproduce this.

**Comment by MichaelChirico** [comment] 2016-10-08 06:08
same problem on R console (i.e., from the command line)?

if not, this is an rmarkdown problem, not `data.table`.

(and actually, thinking more, this problem beset my own recent
presentations as well)

**Comment by shrektan** [comment] 2016-10-08 07:43
@MichaelChirico No, it occurs only when rendering a `rnw` or a `rmd` file, as long as the `rmarkdown` package was loaded. 

Considering it only occurs on the dev version of `rmarkdown` being loaded, I will agree with you that it should be a problem on `rmarkdown`. I will file an issue there then. 

Thanks.

**Comment by jangorecki** [comment] 2019-03-05 15:06
I am not able to reproduce this on rmarkdown 1.10 and recent data.table. It looks like it was fixed in rmarkdown. Closing

**Closed by jangorecki** 2019-03-05 15:06 UTC
