### ISSUE TITLE
Wierd .N problem

### ISSUE THREAD

**Issue by xinyangshen** [Rdatatable/data.table#1261] opened 2015-08-11 19:56 UTC
I am using data.table 1.9.4. Please see the below R output. Please note that the second to last statement " data[category == "yes", .N]" should produce answer 1 NOT 0. Very strange. Is this a bug or something I did is wrong?

> data <- data.table(query ="test 1")
> data <- rbind(data, data.table(query ="test 2"))
> data <- rbind(data, data.table(query ="test 3"))
> data[, category := ""]
> 
> data[category == "", .N]
[1] 3
> data[category == "yes", .N]
[1] 0
> data[,.N, by=category]
   category N
1:          3
> 
> data[query == "test 1"]$category <- "yes"
> 
> data[category == "", .N]
[1] 2
> data[category == "yes", .N]
[1] 0
> data[,.N, by=category]
   category N
1:      yes 1
2:             2

**Comment by arunsrinivasan** [comment] 2015-08-11 20:00
Was a bug due to auto indexing (new feature in v1.9.4). Fixed in devel. 

Please read the README.md file for bugs fixed and features implemented, and also test on devel version and make sure it's reproducible on devel.

**Closed by arunsrinivasan** 2015-08-11 20:00 UTC
