### ISSUE TITLE
fifelse performance for int, lgl and num on small sets

### ISSUE THREAD

**Issue by D-Se** [Rdatatable/data.table#5637] opened 2023-05-14 07:14 UTC
OpenMP [pragma](https://github.com/Rdatatable/data.table/blob/master/src/fifelse.c#L139) may affect performance for small integers, logicals and numerics. Simply adding a  `bool openmp = len0 > 10000` achieves some 5x on my machine. Tests seem to pass fine.
```
    if (openmp) {
#pragma omp parallel for num_threads(getDTthreads(len0, true))
      for (int64_t i=0; i<len0; ++i) {
        pans[i] = pl[i]==0 ?
        (na_b ? na : pb[i & bmask]) :
        pl[i]==1 ?
        (na_a ? na : pa[i & amask]) :
        (na_n ? na : pna[i & nmask]);
      }
    } else {
      for (int64_t i=0; i<len0; ++i) {
        pans[i] = pl[i]==0 ?
        (na_b ? na : pb[i & bmask]) :
        pl[i]==1 ?
        (na_a ? na : pa[i & amask]) :
        (na_n ? na : pna[i & nmask]);
      }
    }
```
See below (log-scale) benchmark for more types, threads and vector recycling. Here `ask` [(source)](https://github.com/D-Se/ask/blob/main/src/ifelse.c#L44-L72) uses the `openmp` boolean.
![fifelse](https://github.com/Rdatatable/data.table/assets/59521296/f3ca9ac5-f360-4b54-84aa-1abe43108602)

Do others also experience this speedup, perhaps at values other than 10k?

If so, perhaps a wider investigation of [uses of pragma](https://github.com/search?q=repo%3ARdatatable%2Fdata.table%20%23pragma&type=code) in `data.table` is useful?

**Comment by jangorecki** [comment] 2023-05-14 14:26
There is a mechanism to disable multithreading for small input handled inside getDTthreads. You should also tell us what is your machine, if it's windows I wouldn't care that much, as it is known to be less optimal in use of openmp, and causes more problems in general. If you are on Linux then compiler version and openmp version could be useful info as well.

**Comment by ben-schwen** [comment] 2023-05-23 09:30
Since both `kit:iff` and `fifelse` were implemented by @2005m, I wonder what are cases where `kit` might be faster since the benchmarks for both look quite similar.

**Comment by jangorecki** [comment] 2023-10-01 03:16
As mentioned before, there is a mechanism to escape openmp if input is small. It is handled in getDTthreads. If it doesn't work for you, then reproducible example would be useful. Closing for now but happy to reopen when we have an example.

**Closed by jangorecki** 2023-10-01 03:16 UTC
Labels: benchmark, performance, openmp
