### ISSUE TITLE
adding get messes up .SD

### ISSUE THREAD

**Issue by eantonya** [Rdatatable/data.table#3044] opened 2018-09-12 16:26 UTC
```
d = data.table(a = 1, b = 2, c = 3)

d[, {get('b'); c; names(.SD)}, .SDcols = 'b']
[1] "b" "c"

# Expected output
# d[, {b; c; names(.SD)}, .SDcols = 'b']
[1] "b"
```

Some lexical parsing of the i-expression goes awry when there is `get` in the expression.

**Comment by franknarf1** [comment] 2018-09-12 16:45
You mentioned a similar-looking example here: https://github.com/Rdatatable/data.table/issues/1744#issuecomment-255465301 

> ```
> dt = data.table(a = 1, b = 2, c = 3)
> 
> dt[, {list(a, get('b')); names(.SD)}, .SDcols = 'c']
> #[1] "a" "c"
> ```
> 

Maybe not a dupe. (I don't know the internals well enough to guess.)

**Comment by eantonya** [comment] 2018-09-12 16:48
haha, good point - I guess I keep running into this

**Comment by MichaelChirico** [comment] 2018-09-12 17:00
also potential overlap: #2647 #2036 #1548

**Comment by MichaelChirico** [comment] 2019-09-02 17:34
Closed in https://github.com/Rdatatable/data.table/pull/3771

Should add it to the NEWS?

**Comment by jangorecki** [comment] 2019-09-02 17:39
@MichaelChirico ideally PR having unit test from this issue, and mention NEWS. Unit test just to prevent regression in future, which could eventually be not covered by existing #3771 unit tests.

**Comment by MichaelChirico** [comment] 2019-09-02 17:54
Hard to imagine how it's different from test 2090.1

**Comment by jangorecki** [comment] 2019-09-02 18:01
@MichaelChirico fine them

**Closed by jangorecki** 2019-09-02 18:01 UTC
Labels: bug
