### ISSUE TITLE
cannot install data.table under R 3.5.1

### ISSUE THREAD

**Issue by Shicheng-Guo** [Rdatatable/data.table#3320] opened 2019-01-27 02:10 UTC
forder.c: In function ‘range_str’:
forder.c:296: error: expected end of line before ‘update’
make: *** [forder.o] Error 1
ERROR: compilation failed for package ‘data.table’
* removing ‘/home/local/MFLDCLIN/guosa/R/x86_64-redhat-linux-gnu-library/3.5/data.table’
Warning message:
In install.packages("data.table_1.12.0.tar.gz") :
  installation of package ‘data.table_1.12.0.tar.gz’ had non-zero exit status

`#` `Output of sessionInfo()`
R version 3.5.1 (2018-07-02)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS release 6.10 (Final)

Matrix products: default
BLAS: /usr/lib64/R/lib/libRblas.so
LAPACK: /usr/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1

**Comment by jangorecki** [comment] 2019-01-27 03:50
Thank you for reporting. This issue is a duplicate of recently reported https://github.com/Rdatatable/data.table/issues/3291. Please provide there information about compiler version you are using.

**Closed by jangorecki** 2019-01-27 03:50 UTC
