### ISSUE TITLE
robust encoding in fread (like 'fread("iconv -f ISO-8859-1 -t UTF-8 mytextfile.txt")') 

### ISSUE THREAD

**Issue by andreasio** [Rdatatable/data.table#1748] opened 2016-06-22 09:15 UTC
Since https://github.com/Rdatatable/data.table/issues/563 is closed, I am adding this as a feature request.

fread still causes trouble on most of the files I work with (danish windows files). E.g. I have an iso-8850-1 windows file, that I can't fread correctly on linux. This workaround (https://github.com/Rdatatable/data.table/issues/563#issuecomment-112423962 works). And read.csv works (i.e. produces the correct øæå letters, instead of e.g. \xe6), but fread(... encoding = "Latin-1") does not.

Sincerely

**Comment by arunsrinivasan** [comment] 2016-06-22 23:41
Please provide a reproducible example. 

Possible duplicate of melt(dt, measure.vars = patterns("^x", "^y"))

**Comment by andreasio** [comment] 2016-06-24 19:39
```
path <- "http://is.gd/0UMAfv"
testdata <- fread(path)
```

now when you do `testdate$` rstudio will respond with this message, the moment you enter the `$` sign:

> Error in tolower(completions) : invalid multibyte string 1

`names(testdata)` returns this:

>  names(testdata)

```
[1] "F\xe6rdig"           "Forventet udl\xe6rt" "Afslut.\xe5rsag"     "Virk. navn"         
[5] "Lsted_id"  
```
None of theese issues happen if I perform them on windows, or if I save the file and do

`fread("iconv -f ISO-8859-1 -t UTF-8 filename")`

Hope this helps

Sincerely

**Comment by jangorecki** [comment] 2016-06-24 20:44
@andreasio is it what you expect?
```r
path <- "http://is.gd/0UMAfv"
testdata <- fread(path, encoding="Latin-1")
names(testdata)
#[1] "Færdig"           "Forventet udlært" "Afslut.årsag"     "Virk. navn"       "Lsted_id"   
```

**Comment by andreasio** [comment] 2016-06-24 21:58
Yes Thats what i expect, but on my linux Box Thats not what Happens?

**Comment by andreasio** [comment] 2016-06-24 23:40
in 1.9.7 it works as expected. Thanks.

**Closed** 2016-06-25 01:09 UTC
Labels: duplicate, fread, not reproducible
