### ISSUE TITLE
zero-length 'cols' in na.omit.data.table() results in empty table

### ISSUE THREAD

**Issue by tdeenes** [Rdatatable/data.table#2514] opened 2017-12-12 13:02 UTC
The documentation of na.omit.data.table does not provide any hint what happens if 'cols' is a zero-length vector. 

Consider the following snippet:
`na.omit(data.table::data.table(x = c(NA, TRUE, FALSE)), cols = character())`

This results in:
`# Empty data.table (0 rows) of 1 col: x`

My intuition would be that the correct result is the raw input. Of course I might be wrong, and the result is intentionally an empty table. However, it would be nice to document this behaviour.

**Comment by jangorecki** [comment] 2020-04-07 07:50
@tdeenes I agree with your intuition, and that seems to be the current behaviour, so it has been fixed sometime in the past. I will push test for that.

**Comment by mattdowle** [comment] 2021-08-20 20:50
I reproduced using v1.10.4-3 (Oct 2017) and confirmed it was fixed in v1.11.0 (May 2018).
I can't see a tests for that case, so Jan's PR to add the test looks good.

**Closed** 2021-08-20 21:11 UTC
