### ISSUE TITLE
[Request] Add ability to truncate character columns in print.data.table()

### ISSUE THREAD

**Issue by ben519** [Rdatatable/data.table#3112] opened 2018-10-17 19:37 UTC
Printing data.tables in the console is something I do *a lot*. Often times my data has messy character columns that make a printed table ugly/hard to read due to text wrapping. Consider this example,

```
dt <- data.table(
  Id = 1:5,
  CompanyA = c("Foo", "Bar", "Company XYZ", "Magnolia Nursing Care LLC (Formerly Pontchartrain Nursing Co.)", "ABC")
)
dt[, c("CompanyB", "CompanyC", "CompanyD") := CompanyA]
print(dt)
```
<img width="1084" alt="screen shot 2018-10-17 at 2 33 46 pm" src="https://user-images.githubusercontent.com/723099/47111641-adff3880-d219-11e8-9a78-29aa780effd1.png">

So, I frequently use stringr's `str_trunc()` method to clean this up. For example,

```
print(dt[, list(
  Id, 
  CompanyA = stringr::str_trunc(CompanyA, width = 20),
  CompanyB = stringr::str_trunc(CompanyB, width = 20),
  CompanyC = stringr::str_trunc(CompanyC, width = 20),
  CompanyD = stringr::str_trunc(CompanyD, width = 20)
)])
```

<img width="613" alt="screen shot 2018-10-17 at 2 34 59 pm" src="https://user-images.githubusercontent.com/723099/47111706-d850f600-d219-11e8-91b2-1dd62e373ec8.png">

For me it'd be convenient to have an argument like `print(x, ..., truncchars = NULL)` where one could specify an integer for `truncchars` and the result is that every character column in `dt` would be truncated with ellipses.

**Comment by MichaelChirico** [comment] 2018-10-17 23:03
duplicate of #1523

**Closed by MichaelChirico** 2018-10-17 23:03 UTC
