### ISSUE TITLE
Wrong units displayed in data.table with POSIXct arithmetic

### ISSUE THREAD

**Issue by boethian** [Rdatatable/data.table#761] opened 2014-08-09 00:57 UTC
Recently posted on StackOverflow because didn't know how to report bug report / make feature request here. 

http://stackoverflow.com/questions/25214170/wrong-units-displayed-in-data-table-with-posixct-arithmetic

Problem reproduced here for completeness, I can take down SO "question" if this bug is deemed legitimate here:

When durations are computed in data.table (v1.9.2), the wrong units can be printed with POSIXct arithmetic. It seems the first units are chosen.

```
require("data.table")
dt <- data.table(id=c(1,1,2,2), 
                  event=rep(c("start", "end"), times=2), 
                  time=c(as.POSIXct(c("2014-01-31 06:05:30", 
                                      "2014-01-31 06:45:30", 
                                      "2014-01-31 08:10:00", 
                                      "2014-01-31 09:30:00"))))
dt$time[2] - dt$time[1]  # in minutes
dt$time[4] - dt$time[3]  # in hours
dt[ , max(time) - min(time), by=id]  # wrong units printed for id 2
```

I realize that one of these is the correct way to do it to get expected behavior, but wanted to report this behavior. Not sure if it is really a data.table problem or POSIXct problem. 

```
dt[ , difftime(max(time), min(time), units="mins"), by=id]  # both mins
dt[ , difftime(max(time), min(time), units="hours"), by=id]  # both hours
```

**Comment by MichaelChirico** [comment] 2016-08-02 00:56
Was just trying to figure out if I couldn't fix this, but it seems the mistake is done entirely in C (everything's fine up until `.Call(Cdogroups, ...)` AFAICT), so it's above my weight class for now...

**Comment by MichaelChirico** [comment] 2018-04-16 12:55
Some more details copied as this re-surfaced for me:

```
library(data.table)
DT = data.table(
  a = c(1, 1, 2, 2),
  b = structure(
    c(0, 10, 0, 100000000), 
    class = c('POSIXct', 'POSIXt')
  )
)
DT[ , diff(b), keyby = a]
#    a            V1
# 1: 1   10.000 secs
# 2: 2 1157.407 secs
```

The problem is that `diff.POSIXt` silently invokes `-.POSIXt`, which chooses units automatically given its inputs.

These units are ignore on group wrapup:

```
DT[ , {
  x = diff(b)
  dput(x)
  x
}, keyby = a]
# structure(10, units = "secs", class = "difftime")
# structure(1157.40740740741, units = "days", class = "difftime")
#    a            V1
# 1: 1   10.000 secs
# 2: 2 1157.407 secs
```

**Comment by mattdowle** [comment] 2019-09-11 22:14
Closed by #3837.
("Closes #n and #m" doesn't close #m. Have to use "closes" separately before each issue number.)

**Closed by mattdowle** 2019-09-11 22:14 UTC
Labels: High, bug

**Comment by MichaelChirico** [comment] 2019-09-11 23:11
oh really? I believe that works in the commit message... or maybe that's just gitlab?

**Comment by mattdowle** [comment] 2019-09-11 23:33
Yep. I don't know about gitlab or the commit message (I don't think so), but this one did not close this one.  Before merge you can see if the merge is going to close it or not via a hyperlink / tooltip that appears in the linked PR on the issue labeled "will be closed by" (or similar).

**Comment by MichaelChirico** [comment] 2019-09-11 23:38
OK. something to raise with GitHub

**Comment by mattdowle** [comment] 2019-09-12 00:17
I did look once and it has been raised already.  Now that Microsoft bought GitHub for $7bn, perhaps things like that will get fixed faster and better.
Here's an image showing the tooltip I referred to ... the faint underline under the word close and then hover over it to see a pop-up.
![image](https://user-images.githubusercontent.com/2779998/64744242-db02ac80-d4b7-11e9-86f2-1e9cc15e5221.png)
