### ISSUE TITLE
progress indicator/bar for "by" operations

### ISSUE THREAD

**Issue by eantonya** [Rdatatable/data.table#3060] opened 2018-09-21 15:00 UTC
I frequently run `by` operations that take minutes and sometimes hours to complete. To deal with the uncertainty of what's going on, I often resort to printing `.BY` in the i-expression:

```
dt = data.table(a = 1:5)
dt[, {print(.BY)
      Sys.sleep(10)
      5}
   , by = a]
```

Would be great to have an automatic progress bar for these, similar to `fread`, if the expected run time is greater than e.g. 30s. Expected run time can be estimated from actual average time spent running the i-expression for each `by` item so far * number of remaining `by` items.

**Comment by franknarf1** [comment] 2018-09-21 17:53
Dupe of closed https://github.com/Rdatatable/data.table/issues/1409 

I manually add progress-printers when I see an operation going slowly, but it'd be nice if it were automatic whenever time > 30 s as you suggest.

**Comment by mattdowle** [comment] 2018-09-22 02:30
Related: #3050

**Comment by jangorecki** [comment] 2018-09-22 06:06
@franknarf1 agree with Frank, but lets print it only for `interactive()`.

**Comment by eantonya** [comment] 2018-09-25 21:00
I've been thinking about this and ideally I'd like to see the following information:

- number of groups processed
- total number of groups or groups remaining
- time elapsed
- total predicted time or time remaining
- maybe current group (but I'm not sure how you'd do this without creating a mess)

**Comment by Kodiologist** [comment] 2019-10-01 14:51
I too would like this as an opt-in feature of data.table. In the meantime, here's a code snippet to manually add a progress bar with a percentage:

```
bar = txtProgressBar(style = 3, min = 0,
    max = nrow(unique(d[, GROUP_EXPRESSION))))
d[, by = GROUP_EXPRESSION,
   {setTxtProgressBar(bar, .GRP)
    J_EXPRESSION}]
close(bar)
```

**Comment by jangorecki** [comment] 2020-06-27 21:24
> if the expected run time is greater than e.g. 30s. Expected run time can be estimated from actual average time spent running the i-expression for each by item so far * number of remaining by items.

`i` is not run for each item in `by`, even if it would, then still such estimation would be quite inaccurate because it doesn't say anything about `j`, to make that automatically we would have to measure time of iterations over progressing groups evaluated in `j`, and then decide to print at some threshold. This unfortunatelly would impose an overhead, it may be better to enable this feature explicitly rather than automatically.

**Comment by MichaelChirico** [comment] 2020-06-28 00:38
the same can be said of the progress bar for fread/fwrite right? at least w.r.t. the overhead concern

**Comment by Kodiologist** [comment] 2020-06-28 01:30
You could use `pbapply` as a dependency, since it already implements time estimation. In my example above, you'd replace `txtProgressBar` with `startpb` and `setTxtProgressBar` with `setpb`.

**Comment by jangorecki** [comment] 2020-06-28 01:42
Time estimation, once we start to evaluate `j`, is not something we should be worried about. Previous comment was about time estimation before we start evaluating `j`. Recent PR by @MichaelChirico provides efficient way to know how many groups we have being inside `j`, so `.GRP/.NGRP` is not a problem. Problem is that to handle that automatically, when time is longer than a threshold, we have to sum timings allways, for all iterations, and this will add overhead. Just R C API impose quite big overhead there already so it doesn't look fine for me to add that one, by default.

**Comment by Kodiologist** [comment] 2020-06-28 12:18
Having to turn it on explicitly with an argument, like `progress = TRUE`, makes sense to me.

**Comment by joshhwuu** [comment] 2024-07-15 19:22
What would be the best way to opt-in to this feature? I was wondering what something like `showProgress = TRUE` would look like within the square bracket syntax.

**Comment by Kodiologist** [comment] 2024-07-15 20:48
I imagine a typical call would look like `dt[, by = ..., progress = TRUE, ...]`, where the last `...` is `j`.

**Closed** 2024-07-29 20:02 UTC
Labels: feature request, top request
