### ISSUE TITLE
Feature request - support reference semantics for column selection

### ISSUE THREAD

**Issue by mik3y64** [Rdatatable/data.table#4111] opened 2019-12-14 04:41 UTC
When manipulating big data, data.table supports reference semantics which allows to delete columns of a data.table by reference. There is no direct way for column selection.

```r
dat <- data.table(mtcars)
colnames(dat[ , setdiff(colnames(dat), c("mpg", "wt", "disp")) := NULL])
# [1] "mpg"  "disp" "wt"
```

It would be nice to have the opposite of `... := NULL` where data.table can select columns by reference semantics internally.

```r
dat[ , c("mpg", "wt", "disp") := KEEP]
# or
dat[ , !c("mpg", "wt", "disp") := NULL]
# or
dat[ , -c("mpg", "wt", "disp") := NULL]
```

**Comment by MichaelChirico** [comment] 2019-12-14 04:56
thanks for the request! I think it's a duplicate of #4031 
please follow up there with any additional feedback

**Closed by MichaelChirico** 2019-12-14 04:56 UTC
Labels: duplicate
