### ISSUE TITLE
Plot in data.table by group is inconsistent with in terminal

### ISSUE THREAD

**Issue by renkun-ken** [Rdatatable/data.table#3120] opened 2018-10-19 14:55 UTC
I'm not sure if I should file this issue here or at https://github.com/rstudio/rstudio/issues/3708.

> The graphics produced by calling `plot` in data.table by group is inconsistent with that produced in terminal.
> 
> ```r
> library(data.table)
> dt <- data.table(group = rep(c("A", "B", "C"), each = 10), x = 1:30)
> 
> par(mfrow = c(1, 3))
> dt[, plot(x, main = group), keyby = group]
> ```
> 
> The resulted graphics in RStudio Plots pane is as follows:
> 
> <img width="886" alt="image" src="https://user-images.githubusercontent.com/4662568/47216412-7342ff00-d3d7-11e8-8953-0e32cb7ed76f.png">
> 
> The graphics produced in terminal is correct:
> 
> <img width="775" alt="image" src="https://user-images.githubusercontent.com/4662568/47216489-aab1ab80-d3d7-11e8-9d99-bca4c58cbf59.png">
> 
> However, if the plot window created from R terminal is resized, the plot title becomes incorrect, same with RStudio Server.
> 
> One walk around is always copy the symbol used in `by=`:
> 
> ```r
> library(data.table)
> dt <- data.table(group = rep(c("A", "B", "C"), each = 10), x = 1:30)
> 
> par(mfrow = c(1, 3))
> dt[, plot(x, main = group[]), keyby = group]
> ```
> This issue is related to how data.table modifies group symbols in place. I'm not sure if RStudio could do anything about it or if an issue should be raised at R or data.table.

Is there anything that can be done in `data.table` so that resizing a plot that uses group symbols does not lead to duplicate values like the plot titles. Or should this be considered as a issue of R and it'd be better resolved in R internals somehow?

**Comment by MichaelChirico** [comment] 2018-10-19 15:19
closing as a duplicate of #1524

https://stackoverflow.com/q/28400446/3576984

**Comment by renkun-ken** [comment] 2018-10-19 16:32
As I mentioned in the post, I tried the same plot in R terminal, and the plot appears correct at first but when I resize the plot, it becomes exactly like what appears in RStudio. Then it is a base R issue in refreshing graphics when resized.

**Comment by MichaelChirico** [comment] 2018-10-19 17:01
sorry, admit I didn't read close enough first pass... still could you add this to the other issue?

**Comment by franknarf1** [comment] 2018-10-19 18:44
@MichaelChirico Regarding it not-being Rstudio-dependent -- ditto for #2050 (where your last comment similarly says this). 

Are new comments under closed issue #1524 (which really was RStudio-dependent, judging by Kevin Ushey's response...?) the best place for that... seems like it'll just invite further confusion.

**Comment by MichaelChirico** [comment] 2018-10-19 18:50
Hmm good point. didn't notice on mobile earlier...

**Comment by MichaelChirico** [comment] 2018-10-19 18:50
Last one was closed by @jangorecki as non-reproducible in R console, but now seems reproducible in R console...

**Comment by jangorecki** [comment] 2018-10-20 08:43
Yes, I haven't tried resizing

**Comment by MichaelChirico** [comment] 2020-01-31 16:43
Noting an update after investigation on RStudio side by Kevin Ushey https://github.com/rstudio/rstudio/issues/3708:

> The issue is perhaps more clear with this code:
> 
> ```r
> library(data.table)
> dt <- data.table(group = rep(c("A", "B", "C"), each = 1), x = 1:3)
> dt[, .Internal(inspect(group)), keyby = group]
> #> @7ffb15bc4d90 16 STRSXP g0c1 [NAM(1)] (len=1, tl=0)
> #>   @7ffb18587eb8 09 CHARSXP g0c1 [MARK,gp=0x61] [ASCII] [cached] "A"
> #> @7ffb15bc4d90 16 STRSXP g0c1 [NAM(1)] (len=1, tl=0)
> #>   @7ffb18174920 09 CHARSXP g0c1 [MARK,gp=0x61] [ASCII] [cached] "B"
> #> @7ffb15bc4d90 16 STRSXP g0c1 [NAM(1)] (len=1, tl=0)
> #>   @7ffb149946b8 09 CHARSXP g0c1 [MARK,gp=0x61] [ASCII] [cached] "C"
> #>    group V1
> #> 1:     A  A
> #> 2:     B  B
> #> 3:     C  C
> ```
> 
> Created on 2018-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)
> 
> Note that each STRSXP has the same address. I'm guessing that STRSXP is being stored and used as a reference for the plot title, but by the time it's referenced for plot generation, it points to the CHARSXP containing "C".
> 
> Given that, there is a simple workaround:
> 
> ```r
> library(data.table)
> dt <- data.table(group = rep(c("A", "B", "C"), each = 1), x = 1:3)
> 
> par(mfrow = c(1, 3))
> dt[, plot(x, main = copy(group)), keyby = group]
> ```
> 
> ie, just use `copy()` to ensure that a copy is made as needed.



> The issue is perhaps more clear with this code:
> 
> ```r
> library(data.table)
> dt <- data.table(group = rep(c("A", "B", "C"), each = 1), x = 1:3)
> dt[, .Internal(inspect(group)), keyby = group]
> #> @7ffb15bc4d90 16 STRSXP g0c1 [NAM(1)] (len=1, tl=0)
> #>   @7ffb18587eb8 09 CHARSXP g0c1 [MARK,gp=0x61] [ASCII] [cached] "A"
> #> @7ffb15bc4d90 16 STRSXP g0c1 [NAM(1)] (len=1, tl=0)
> #>   @7ffb18174920 09 CHARSXP g0c1 [MARK,gp=0x61] [ASCII] [cached] "B"
> #> @7ffb15bc4d90 16 STRSXP g0c1 [NAM(1)] (len=1, tl=0)
> #>   @7ffb149946b8 09 CHARSXP g0c1 [MARK,gp=0x61] [ASCII] [cached] "C"
> #>    group V1
> #> 1:     A  A
> #> 2:     B  B
> #> 3:     C  C
> ```
> 
> Created on 2018-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)
> 
> Note that each STRSXP has the same address. I'm guessing that STRSXP is being stored and used as a reference for the plot title, but by the time it's referenced for plot generation, it points to the CHARSXP containing "C".
> 
> Given that, there is a simple workaround:
> 
> ```r
> library(data.table)
> dt <- data.table(group = rep(c("A", "B", "C"), each = 1), x = 1:3)
> 
> par(mfrow = c(1, 3))
> dt[, plot(x, main = copy(group)), keyby = group]
> ```
> 
> ie, just use `copy()` to ensure that a copy is made as needed.

**Comment by jangorecki** [comment] 2020-04-06 15:50
closing as duplicate of #507

**Closed by jangorecki** 2020-04-06 15:50 UTC
Labels: duplicate
