### ISSUE TITLE
Strange behavior taking diff(date)

### ISSUE THREAD

**Issue by bjorn81** [Rdatatable/data.table#2090] opened 2017-03-30 10:16 UTC
I'm taking the diff of a column which is of class "POSIXct" "POSIXt". The results is returned in unit of days, but for days where the difference is 1 day, the result is actually the difference in seconds, even as it says date. Sorry for not giving a reproducible example.
`nps.change <- ovoDT[customer_ref %in% repeat.customers, 
                    .(diff = diff(nps), days_between = diff(theDate), .N, 
                      first = min(theDate), last = max(theDate)), 
                    by = customer_ref][order(N)]
nps.change`

Notice the difference of 86400.0000 days:

       customer_ref diff  days_between customer_ref N      first       last
    1:    100417711    0 24192000 days    100417711 5 2015-08-25 2016-06-13
    2:    100417711    0  1123200 days    100417711 5 2015-08-25 2016-06-13
    3:    100417711    0        0 days    100417711 5 2015-08-25 2016-06-13
    4:    100417711    0        0 days    100417711 5 2015-08-25 2016-06-13
    5:    100677081    0    86400 days    100677081 5 2016-01-26 2016-01-27

**Comment by jangorecki** [comment] 2017-03-30 10:56
Duplicate of #761

**Closed by jangorecki** 2017-03-30 10:56 UTC
