### ISSUE TITLE
`.I` could work in `by=`

### ISSUE THREAD

**Issue by sritchie73** [Rdatatable/data.table#3119] opened 2018-10-19 10:51 UTC
Sometimes calculations do not vectorise properly, in which case it is useful to group computation by each row.

Here's an example:

```
bim <- data.table(rsid=c("rs1", "rs2", "rs3"), chr=1, pos=1:3, 
                             A1=c("A", "T", "CG"), A2=c("G", "C", "A"))

# Give each variant a unique id based on chromosome, position, and alphabetically sorted alleles
# so they can be reliably matched across datasets with different allele orderings in the A1 and 
# A2 columns:
bim[, new_id := paste(chr, pos, paste(sort(c(A1, A2)), collapse=":"), sep=":"), 
          by = seq_len(nrow(bim))]
bim

   rsid chr pos A1 A2   new_id
1:  rs1   1   1  A  G  1:1:A:G
2:  rs2   1   2  T  C  1:2:C:T
3:  rs3   1   3 CG  A 1:3:A:CG
```

Here the `sort(c(A1, A2))` step in `j` does not work properly unless you group the calculations by each row.  Rather than writing `by = seq_len(nrow(DT))` it would be more convenient if you could simply use `by = .I`.

Note `by = .I` currently runs, but does no grouping:

```
bim[, new_id := paste(chr, pos, paste(sort(c(A1, A2)), collapse=":"), sep=":"), by = .I]
bim

   rsid chr pos A1 A2           new_id
1:  rs1   1   1  A  G 1:1:A:A:C:CG:G:T
2:  rs2   1   2  T  C 1:2:A:A:C:CG:G:T
3:  rs3   1   3 CG  A 1:3:A:A:C:CG:G:T
```

**Comment by MichaelChirico** [comment] 2018-10-19 11:41
Duplicate of #1732 (sorry I know this one's hard to search for)

**Closed by MichaelChirico** 2018-10-19 11:41 UTC
