### ISSUE TITLE
[R-Forge #2044] Fuzzy matching for character keys

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#636] opened 2014-06-08 13:16 UTC
Submitted by: Chris Neff; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2044&group_id=240&atid=978)

How hard would it be to allow SQL like matching on character keys? Something like

dt[J("foo-%")]

giving you all rows that have a key starting with "foo-".  I could do it with grep but if there is someway to take advantage of the sorted nature of keys I would think it would be a speed up.

**Comment by franknarf1** [comment] 2017-01-27 16:17
One example [from SO](http://stackoverflow.com/q/41897703): 

> Replace all of a string based on its start
>
> [...] to change for example "Golden State WarriorsÂ (1)Â" for GSW [...]

**Comment by MichaelChirico** [comment] 2019-05-09 14:49
Seems duplicate of #1431 and that one has a bit more fleshed out discussion; closing this one

**Closed by MichaelChirico** 2019-05-09 14:49 UTC
Labels: Medium, feature request
