### ISSUE TITLE
missing vignette

### ISSUE THREAD

**Issue by waynelapierre** [Rdatatable/data.table#5732] opened 2023-11-07 21:24 UTC
Where is the “Joins and rolling joins” vignette mentioned in the "Introduction to data.table" vignette?
https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html

**Comment by jangorecki** [comment] 2023-11-07 22:25
closing as duplicate of #2181

**Closed by jangorecki** 2023-11-07 22:25 UTC
Labels: duplicate, question, documentation
