### ISSUE TITLE
chaining DT using function which should return invisible result

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1081] opened 2015-03-15 14:14 UTC
The same way as `:=` makes results invisible I would like to use my function to results invisibly (e.g. writing to database).
Currently my `dt[,invisible(.SD)]` makes always return visible object, which results below.
`.SD` only represents some transformation:
```r
library(data.table)
dt <- data.table(a=1:2,b=letters[1:2])
f <- function(x) invisible(x)
dt[,f(.SD)] # visible result

# nice workaround can be made by:
library(magrittr)
dt[, .SD] %>% invisible # suppress any previous function results visibility
dt[, .SD] %>% f # invisible only because `f`
```
but the nice workaround require additional dependency in the scripts, maybe there is some trick to make it in data.table?

**Comment by arunsrinivasan** [comment] 2015-03-15 14:37
duplicate of #482. I don't think this is possible.

**Comment by jangorecki** [comment] 2015-03-15 15:20
maybe a simple feature:
```r
# add to `[.data.table`
`[.data.table` <- function(...){
  on.exit({
    if(getOption("datatable.inv",FALSE)){
      # do_ the same what `:=`
      options("datatable.inv"=FALSE)
  })
  # ...
}
# usage
f <- function(x){
  options("datatable.inv"=TRUE)
  x
}
dt[, f(.SD)]
```

**Comment by arunsrinivasan** [comment] 2015-03-15 15:29
As I wrote under #482,

> I've added the label 'won't fix' for now. As it's a problem with the way base R forces visibility on `[`.

Even if there was a fix, it'd be dirty, and I don't think it's worth it.

**Closed by arunsrinivasan** 2015-03-15 15:29 UTC
