### ISSUE TITLE
fread() na.strings argument does not prevent column conversion to character

### ISSUE THREAD

**Issue by rnorberg** [Rdatatable/data.table#729] opened 2014-07-11 20:11 UTC
df <- data.frame(x=c(1:10, 'NULL', 12:40))
    write.csv(df, 'tmp.csv', row.names=F)
    dt <- fread('tmp.csv', na.strings='NULL')
    sapply(dt, class)

This may be on purpose, but I think since 'NULL' is specified as an na.string, the column should be read in as numeric.

**Comment by kykuo** [comment] 2015-02-02 22:25
Related: https://github.com/Rdatatable/data.table/issues/504

Is this being looked at and would its resolution involve tweaking the underlying C code?

**Comment by arunsrinivasan** [comment] 2015-03-16 18:17
Thanks for the report, but as you point out it's a duplicate of #504. We'll try and take a look when possible.

**Closed by arunsrinivasan** 2015-03-16 18:17 UTC
Labels: feature request
