### ISSUE TITLE
[Feature request] Allow on to work with intermediate/calculated columns

### ISSUE THREAD

**Issue by Gayyam** [Rdatatable/data.table#3367] opened 2019-02-07 08:10 UTC
Would it be possible to allow using data.table like this - 

    library(data.table)
    set.seed(1)
    dates <- seq(from = as.Date('2019-01-01'), to = as.Date('2019-12-31'), by = '1 day')
    DT1 <- data.table(
      Dates = dates, DateAttr = sample(letters, length(dates), replace = TRUE)
    )
    DT2 <- data.table(Month = 1:12, MonthAttr = sample(letters, 12, replace = TRUE))
    DT1[DT2, on = c(month(dates) = Month), MonthAttr:=i.MonthAttr] # Would it be possible to support syntax like this?
    DT1[, Month:=month(Dates)][
      DT2, on = 'Month', MonthAttr:=i.MonthAttr
    ][, Month:=NULL][] # What I currently use

**Comment by MichaelChirico** [comment] 2019-02-07 08:17
I believe this is a duplicate of #1639, please re-open of not and add your support there (through reactions) if so

**Closed by MichaelChirico** 2019-02-07 08:17 UTC

**Comment by Gayyam** [comment] 2019-02-07 08:21
Thanks, yes. Sorry for the duplicate. Voted (reacted) to issue #1639.
