### ISSUE TITLE
`for` works, `by` fails

### ISSUE THREAD

**Issue by bhagwataditya** [Rdatatable/data.table#6177] opened 2024-06-11 08:27 UTC
Data
```
    plotdt <- data.table( x = c(1, 2), 
                          y = c(1, 2), 
                      color = c('#DAF5F9', '#00BBDC') )
```

For works, by fails
```
    plot(1, type = 'n', xlab = '', ylab = '', xlim = c(0,3), ylim = c(-3,0), axes = 0)  # axes = 1
    for (j in 1:nrow(plotdt)){
        plotdt[j][ , polygon(x = c(x-1,x,x    ), y = -c(y-1,y-1,y  ), col = color )  ] 
    }
    plotdt[    , polygon(x = c(x-1,x,x    ), y = -c(y-1,y-1,y  ), col = color ) , by = x ]     
```
![image](https://github.com/Rdatatable/data.table/assets/5953568/6246920c-0d06-487f-8ae5-cd1f8b2d3045)
![image](https://github.com/Rdatatable/data.table/assets/5953568/3d0fdbc1-c634-4413-aa52-d0b0dcb5d4ab)

And apart from that, thankyou very much dear data.table developers, I'm a big big fan : )

Aditya

**Comment by MichaelChirico** [comment] 2024-06-11 13:27
what plotting device are you using?

**Comment by MichaelChirico** [comment] 2024-06-11 15:23
Duplicate of #1524

**Closed by MichaelChirico** 2024-06-11 15:23 UTC

**Comment by bhagwataditya** [comment] 2024-06-12 11:49
Aaah, thankyou very much for the feedback!
Very reassuring to know that this is an RStudio thing, and data.table itself is actually doing absolutely fine.
Which means I can keep loooooving data.table the way I do, knowing that it has really never failed me, also not this time : )
