### ISSUE TITLE
Add `setcolnames()` as an alias for `setnames()`

### ISSUE THREAD

**Issue by dvg-p4** [Rdatatable/data.table#5640] opened 2023-05-19 20:31 UTC
### Rationale:

`colnames()` on a data.frame/.table returns the same thing as `names()`, and IMO is clearer style. `setcolnames()` would follow this convention, would parallel `setcolorder()`, and AFAICT would not conflict with function names from any other common packages. Of course you'd want to leave `setnames()` as a synonym for backwards-compatibility (and for fewer keystrokes for those who disagree with me on style).

**Comment by Nj221102** [comment] 2024-03-13 11:40
Hi I want to work on this , what i can understand is that this issue require us to make an alias for the function `setnames()` named `setcolnames()` which will make it similar to what happens with `names()` and `colnames()` in r- base.

Is this  method `setcolnames <- data.table::setnames` of setting alias good enough or  might have to use some other method for this ?

**Comment by ben-schwen** [comment] 2024-03-13 12:09
We use `=` for assignment and `<-` only when its absolutely necessary, e.g. S3generics or assignments inside if etc.

The alias should be added to the `setnames` function since this is the common way we do aliases (e.g. search for `[A-z".<-]* = [A-z".<-]* = function` in our codebase). Moreover, it should be exported and added to the documentation.

**Comment by MichaelChirico** [comment] 2024-03-13 15:55
Implementation here is trivial. Just add `setcolnames = setnames = .`, `export(setcolnames)` in NAMESPACE, and `\alias{setcolnames}` and usage in `?setnames`, write NEWS and a test.

The reason this is pending is uncertainty about whether we want to export another function that's just a duplicate of an existing function. Personally I'm indifferent, so need to check if @tdhock or @jangorecki are opposed.

**Comment by Nj221102** [comment] 2024-03-13 16:07
> Implementation here is trivial. Just add `setcolnames = setnames = .`, `export(setcolnames)` in NAMESPACE, and `\alias{setcolnames}` and usage in `?setnames`, write NEWS and a test.
> 
> The reason this is pending is uncertainty about whether we want to export another function that's just a duplicate of an existing function. Personally I'm indifferent, so need to check if @tdhock or @jangorecki are opposed.

I am done with changes and there is no `setnames.rd`  instead it is documented as a subset of `setattr ` in `setattr.rd` should i write about the alias there, and should i make PR or wait for the confirmation.

**Comment by MichaelChirico** [comment] 2024-03-13 16:13
Yes, it should be documented alongside `setnames()`. Since you've already written the changes, it can't hurt to write the PR. Thanks!

**Comment by tdhock** [comment] 2024-03-14 17:41
closing because we don't want to encourage a proliferation of aliases (there should be one way to do every operation, preferably)

**Closed** 2024-03-14 17:40 UTC
Labels: feature request
