### ISSUE TITLE
.I behavior in by

### ISSUE THREAD

**Issue by maxmoro** [Rdatatable/data.table#1544] opened 2016-02-23 21:30 UTC
This code

```
library(data.table)
t1=data.table(a=c(1,2,3),b=c(7,8,9))
t1[,':='(c=list(c(a,b))),by=t1[,.I]]
t1
```

Has the output I need. Basically column C is a list with vectors created from A and B within same Row

```
   a b   c
1: 1 7 1,7
2: 2 8 2,8
3: 3 9 3,9
```

But, if I write it in this way that is more clear to read:

```
library(data.table)
t1=data.table(a=c(1,2,3),b=c(7,8,9))
t1[,':='(c=list(c(a,b))),by=.I]
t1
```

It doesn't work:

```
   a b           c
1: 1 7 1,2,3,7,8,9
2: 2 8 1,2,3,7,8,9
3: 3 9 1,2,3,7,8,9
```

Why? 
`.I` should help to group by Row number, but it is not.
Is this a bug or is intended to work in this way?

Thanks
Max

**Comment by franknarf1** [comment] 2016-02-23 21:35
In github posts, you can write blocks of codes (over multiple lines) by indenting each line four spaces. No need for backticks when doing that.

Currently, `.I` does not work in `by`; maybe it should throw an error there? I usually do `by=seq(nrow(DT))`, though it's not ideal.

**Comment by maxmoro** [comment] 2016-02-23 21:50
Thank you for the block code tip :)
No error is returned, it just works like there is no `by`
I like the suggestion you are offering, I'll update my code, so is more readable.

Anyway, it would be great to have the `by=.I` implemented!
Thanks
Max

**Comment by arunsrinivasan** [comment] 2016-02-23 22:21
Thanks for following up, @franknarf1

**Comment by MichaelChirico** [comment] 2016-02-23 23:59
@franknarf1 I find whole section blocking easier on GitHub (precede and follow code blocks with a line of three backticks

```
```
some_code
```
```

**Comment by jangorecki** [comment] 2019-05-19 15:42
Looks like a duplicate of https://github.com/Rdatatable/data.table/issues/1544 please re-open if not

**Closed by jangorecki** 2019-05-19 15:42 UTC
Labels: Enhancement, Medium, duplicate, feature request
