### ISSUE TITLE
fread ignores empty field with spaces

### ISSUE THREAD

**Issue by renkun-ken** [Rdatatable/data.table#4698] opened 2020-09-07 04:56 UTC
Many commands print a table to the console. In my case it is `gcloud` from Google Cloud.

```
$ gcloud compute instances list
NAME                                  ZONE          MACHINE_TYPE    PREEMPTIBLE  INTERNAL_IP   EXTERNAL_IP     STATUS
abc-def-ghij-20200907-123513-xxxxxxx  asia-east1-a  n2-highmem-8                 xx.xxx.x.xx   xx.xxx.xxx.xx   RUNNING
abc-def-ghij-20200907-123513-xxxxxxx  asia-east1-a  n2-highmem-8                 xx.xxx.x.xxx  xx.xxx.xxx.xx   RUNNING
```

Directly calling `fread(cmd =)` will not get correct result.

```
                                   NAME         ZONE MACHINE_TYPE  PREEMPTIBLE   INTERNAL_IP EXTERNAL_IP STATUS
                                 <char>       <char>       <char>       <char>        <char>      <char> <lgcl>
1: abc-def-ghij-20200907-123513-xxxxxxx asia-east1-a n2-highmem-8  xx.xxx.x.xx xx.xxx.xxx.xx     RUNNING     NA
2: abc-def-ghij-20200907-123513-xxxxxxx asia-east1-a n2-highmem-8 xx.xxx.x.xxx xx.xxx.xxx.xx     RUNNING     NA
```

The following code is a minimal reprex of the problem:

```
library(data.table)
fread(text = "
col1   col2   col3
test1            1
test2     1      2
test3     2      3
", fill = TRUE)
```

```
     col1  col2  col3
   <char> <int> <int>
1:  test1     1    NA
2:  test2     1     2
3:  test3     2     3
```

**Comment by MichaelChirico** [comment] 2020-09-07 13:58
IINM this is actually a fixed-width file, you can check here for input methods:

https://stackoverflow.com/a/34190156/3576984

Closing as duplicate of https://github.com/Rdatatable/data.table/issues/1345 for now, feel free to reopen

**Closed by MichaelChirico** 2020-09-07 13:58 UTC
Labels: fread
