### ISSUE TITLE
1.15.0 release

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#5823] opened 2023-12-10 18:44 UTC
Recently submitted patch release 1.14.10 looks very healthy: https://cran.r-project.org/web/checks/check_results_data.table.html
Seems like we will not need a follow up patch on a patch release.

Therefore we can move to preparing current master for CRAN release as 1.15.0.
Current master looks healthy enough: https://rdatatable.gitlab.io/data.table/web/checks/check_results_data.table.html
(single failing test is due to #5484, not relevant for CRAN)

There are couple pending issues on this milestone that yet have to be resolved: [1.15.0](https://github.com/Rdatatable/data.table/milestone/29)

~~The most severe one is attempted to by addressed in #5133, but PR is not yet complete. **You are invited to take it over.**~~

**Comment by eddelbuettel** [comment] 2023-12-10 20:32
@jangorecki You likely meant 1.14.10 above.

**Comment by MichaelChirico** [comment] 2024-01-05 12:02
@TysonStanley FYI all issues are finished. Please first monitor the revdeps analysis for the gshift fix just now to show up, then we can start the release process (🎉 )

cc @jangorecki @tdhock in case there's anything else to keep in mind before pushing to CRAN

**Comment by jangorecki** [comment] 2024-01-05 14:36
I run master on GLCI now (normally we would need to wait till 4am UTC) and it looks very good: https://rdatatable.gitlab.io/data.table/web/checks/check_results_data.table.html

**Comment by TysonStanley** [comment] 2024-01-06 15:36
Awesome, will start the process today. Very impressive work, so many improvements so quickly. Will let you know if anything comes up in the process.

**Comment by eddelbuettel** [comment] 2024-01-06 15:39
(I had been tagged by @tdhock earlier about an old issue with the renaming of the C level-callable function which may cough up in rev.deps.  If so we should be able to turn `dtts` (which calls this) around with a change quickly too.  (But for the record, I think the renaming is not great, but hey your project your rules -- just piping in as a happy user).)

**Comment by TysonStanley** [comment] 2024-01-07 08:31
All release checks have been run with no issues to report. Will submit the package tomorrow unless there are any concerns from the group (e.g., lingering revdep issues).

**Comment by ben-schwen** [comment] 2024-01-07 18:35
> All release checks have been run with no issues to report. Will submit the package tomorrow unless there are any concerns from the group (e.g., lingering revdep issues).

Unfortunately there are two revdeps affected by e665d2a89c3c8a81ccafd20f0fa7cd96bb905afd.
I'm working on a fix for that.

**Comment by TysonStanley** [comment] 2024-01-07 18:36
> > All release checks have been run with no issues to report. Will submit the package tomorrow unless there are any concerns from the group (e.g., lingering revdep issues).
> 
> Unfortunately there are two revdeps affected by [e665d2a](https://github.com/Rdatatable/data.table/commit/e665d2a89c3c8a81ccafd20f0fa7cd96bb905afd). I'm working on a fix for that.

Thanks for the heads up. Let me know when it looks good.

**Comment by tdhock** [comment] 2024-01-08 18:46
looks like those two revdeps (dtplyr and ahw) are fixed in the most recent check.

**Comment by tdhock** [comment] 2024-01-08 20:53
One more thing which I would like to do before CRAN submission: update role to aut for Jan, Michael, and myself, to be consistent with governance. https://github.com/Rdatatable/data.table/pull/5899
```
Committer
    Definition: permission to commit to, and merge PRs into, master branch.
...
    How this role is recognized: credited via role="aut" in DESCRIPTION (so they appear in Author list on CRAN), and added to 
https://github.com/orgs/Rdatatable/teams/maintainers which gives permission to merge PRs into master branch.
```

**Comment by grantmcdermott** [comment] 2024-01-12 18:54
Refreshing this thread like a Taylor Swift fan waiting for new tickets to drop ;-)

Looking forward to this long-awaited release!

**Comment by TysonStanley** [comment] 2024-01-15 07:20
Version 1.15.0 submitted to CRAN. Auto-processed tests look good. Will update here as I hear back from CRAN.

**Comment by al-obrien** [comment] 2024-01-15 17:47
Very excited about this!

**Comment by eddelbuettel** [comment] 2024-01-15 18:55
I see it in 'waiting' which usually means CRAN wants something from you:  https://cran.r-project.org/incoming/waiting/

**Comment by TysonStanley** [comment] 2024-01-15 18:57
> I see it in 'waiting' which usually means CRAN wants something from you:  https://cran.r-project.org/incoming/waiting/
> 
> 

Yeah, they emailed this morning. Will be sending them the requested information soon.

**Comment by TysonStanley** [comment] 2024-01-15 19:16
@tdhock did we contact maintainers for `RcmdrPlugin.RiskDemo`, `aorsf`, `deepdive`, or `nflplotR` for revdeps? CRAN is picking up these are impacted and a quick search of our issues isn't showing me anything on these. Apologies if I missed them somewhere.

**Comment by TysonStanley** [comment] 2024-01-15 19:16
All of the others caught by CRAN were contacted as early as Nov 2022.

**Comment by MichaelChirico** [comment] 2024-01-16 03:01
FWIW I don't reproduce any issues with `aorsf`, `deepdive`, or `nflplotR`.

`RcmdrPlugin.RiskDemo` has the known issue (#5534) with colliding export from blanket `import()`:

```
  Warning: replacing previous import ‘zoo::yearmon’ by ‘data.table::yearmon’ when loading ‘RcmdrPlugin.RiskDemo’
  Warning: replacing previous import ‘zoo::yearqtr’ by ‘data.table::yearqtr’ when loading ‘RcmdrPlugin.RiskDemo’
```

@tdhock it looks like this was missed because Suggested dependency package `tkrplot` did not install, so no `R CMD check` results:

https://rcdata.nau.edu/genomic-ml/data.table-revdeps/analyze/2024-01-15/RcmdrPlugin.RiskDemo.txt

I ran into that issue while reproducing, I needed to run `apt-get install tk-dev`.

**Comment by TysonStanley** [comment] 2024-01-16 03:15
Was running those myself and seeing some false positives too. Thanks for contacting the maintainer. Has any seen a general guideline for how many days of notice that CRAN wants to see?

**Comment by eddelbuettel** [comment] 2024-01-16 04:06
Two weeks is common methinks (as CRAN does).  I have four with the recent BH update (but then CRAN closed during those over Christmas). I think "it depends" also on the severity the change you request from another package.

**Comment by TysonStanley** [comment] 2024-01-16 04:44
The change for `RcmdrPlugin.RiskDemo` is definitely a straightforward one so we will wait either: maintainer makes adjustment in dev or 2 weeks, whichever comes first. 

I did get an error for `nflplotR` but it looked unrelated to `data.table`. 

```
Running examples in ‘nflplotR-Ex.R’ failed
    The error most likely occurred in:
    
    > ### Name: gt_render_image
    > ### Title: Render 'gt' Table to Temporary png File
    > ### Aliases: gt_render_image
    > 
    > ### ** Examples
    > 
    > ## Don't show: 
    > if (identical(Sys.getenv("_R_CHECK_CONNECTIONS_LEFT_OPEN_"), "false")) (if (getRversion() >= "3.4") withAutoprint else force)({ # examplesIf
    + ## End(Don't show)
    + tbl <- gt::gt_preview(mtcars)
    + gt_render_image(tbl)
    + ## Don't show: 
    + }) # examplesIf
    > tbl <- gt::gt_preview(mtcars)
    > gt_render_image(tbl)
    Execution halted
```

Searching the code for `gt_render_image()` didn't imply `data.table` was related (in fact, they only use data.table a few times in their package [here](https://github.com/nflverse/nflplotR/blob/9302ad61ea24b2e4f9138fe9177f2ddc6cd6ab67/R/nfl_team_factors.R#L70)). Unless you all see something I don't, I think this is a false positive.

**Comment by jangorecki** [comment] 2024-01-16 06:28
Suggested deps are excluded from CRAN check so if that is a suggested dep then I am not sure if we have to worry that much regarding CRAN submission

**Comment by TysonStanley** [comment] 2024-01-16 07:02
> Suggested deps are excluded from CRAN check so if that is a suggested dep then I am not sure if we have to worry that much regarding CRAN submission

These are all imports, unfortunately. It was CRAN that provided these since we didn't see them in our checks. I agree with Michael that a few look like false positives, except for the one Michael contacted. I said as much to CRAN and told them we would resubmit.

**Comment by MichaelChirico** [comment] 2024-01-16 07:11
> maintainer makes adjustment

The easiest fix is this:

```diff
-import(data.table,except=c(last,between,first))
+import(data.table,except=c(last,between,first,yearmon,yearqtr))
```

I've just confirmed that will work even when `yearmon,yearqtr` are not exported by data.table yet. Let me follow up with the author.

**Comment by jangorecki** [comment] 2024-01-16 07:46
Moreover, if zoo was imported after DT then there is in risk of breaking anything.

**Comment by tdhock** [comment] 2024-01-16 18:18
sorry for the failure of the revdep check system to identify this regression, I have noted the issue and I will work on a fix https://github.com/tdhock/data.table-revdeps/issues/1

**Comment by tdhock** [comment] 2024-01-16 23:01
revdep check system will now at least report which dependent packages failed to install at the "prepare package for lazy loading" phase of installation. There are currently 29 which I am investigating (all of which could reveal more revdep issues, but probably unlikely).

**Comment by jangorecki** [comment] 2024-01-26 09:31
What's the status?

**Comment by TysonStanley** [comment] 2024-01-26 21:04
@MichaelChirico have you heard back on the developer of `RcmdrPlugin.RiskDemo`?

**Comment by TysonStanley** [comment] 2024-01-26 21:05
Planning to release tomorrow but would like to know what the status of that is.

**Comment by MichaelChirico** [comment] 2024-01-26 21:19
haven't heard anything. given the triviality of the required fix, and that it's provided already, I wouldn't hesitate to submit as of now

**Comment by TysonStanley** [comment] 2024-01-26 21:21
Have time set aside to submit tomorrow, will updated the group on it. Believe this is the last detail we needed to cross off.

**Comment by eddelbuettel** [comment] 2024-01-30 11:34
Congratulations on shipping to CRAN and validating the new process!

![image](https://github.com/Rdatatable/data.table/assets/673121/65d4b7b6-d2e1-4e24-b102-124045198e95)

**Comment by TysonStanley** [comment] 2024-01-30 16:24
Oh darn, missed that update in the resubmission. Will note that for future resubs

**Comment by TysonStanley** [comment] 2024-01-30 16:52
Note the release changes and tag for 1.15.0 made #5925

**Closed by TysonStanley** 2024-01-30 16:52 UTC
Labels: CRAN
