### ISSUE TITLE
fwrite to excel csv

### ISSUE THREAD

**Issue by hope-data-science** [Rdatatable/data.table#4267] opened 2020-03-01 04:47 UTC
`fwrite` is fast, but as an Excel user, sometimes the encoding is causing me much trouble. There is such a case, when I write files using `fwrite`, it is fast can could be read correctly in R, but not in Excel (the Chinese characters are in messy codes). But when I use `readr::write_excel_csv`, I get the correct format. Is there an option in `fwrite` to write Excel readable csv? 

Thanks.

**Comment by shrektan** [comment] 2020-03-01 05:06
fwrite only writes native encoding at present...

**Comment by MichaelChirico** [comment] 2020-03-01 05:13
I believe this is a duplicate of #1770 -- please express your support there!

Feel free to re-open if you think the duplication was applied in error 👍

**Comment by shrektan** [comment] 2020-10-23 19:05
Recently, I find this particular useful for me and is missing in data.table. This issue is actually a little bit different from #1770. #1770 is about UTF8 and this is about adding a BOM to UTF8 csv file.

I'm reopening this and going to implement this in the near future.

(a simple proto function about adding the BOM)

```r
rewrite_csv_with_bom <- function(path, open = TRUE) {
  # here the open argument must be empty otherwise the content will
  # be converted to native encoding
  # In addition, the encoding must be UTF-8-BOM so that the BOM will
  # be removed (so that it's always safe to add a new BOM later)
  con <- file(path, encoding = 'UTF-8-BOM')
  content <- tryCatch(
    readLines(con), finally = close(con)
  )
  con <- file(path, open = 'wb')
  on.exit(close(con), add = TRUE)
  # we must write the binary to avoid the complexity with R's own internal
  # character handlings
  writeBin(as.raw(c(0xef, 0xbb, 0xbf)), con, useBytes = TRUE)
  writeLines(enc2utf8(content), con, useBytes = TRUE)
  invisible(path)
}
```

**Comment by shrektan** [comment] 2020-10-28 01:56
Sorry, just realized that PR #3580 has already resolved the BOM issues. What we miss here is the ability to write UTF-8 csv files on Windows. On other OS, using `fwrite(..., bom=TRUE)` is enough.

**Closed by shrektan** 2020-10-28 01:56 UTC
Labels: fwrite
