### ISSUE TITLE
R encountered a fatal error when reading a gzip file

### ISSUE THREAD

**Issue by raingstar** [Rdatatable/data.table#2119] opened 2017-04-18 20:52 UTC
```
library(data.table)
data.table 1.10.5 IN DEVELOPMENT built 2017-04-18 19:00:23 UTC
  The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
  Documentation: ?data.table, example(data.table) and browseVignettes("data.table")
  Release notes, videos and slides: http://r-datatable.com

data<-fread('gunzip -c /Users/knie/tmp/Modell/Model_01_29_table.gz', header=TRUE)
R encountered a fatal error, the session was terminated.
```

**Comment by st-pasha** [comment] 2017-04-19 21:52
Could you post the output when running fread with option `verbose=TRUE` ?
Or share the data file `Model_01_29_table.gz` ?

**Comment by raingstar** [comment] 2017-04-20 18:59
<img width="1410" alt="screen shot 2017-04-20 at 11 57 20 am" src="https://cloud.githubusercontent.com/assets/21976032/25247774/c2b1026a-25c0-11e7-8e7f-ef317b3e25af.png">
Can't post the output as it causes R to restart.

**Comment by MichaelChirico** [comment] 2017-04-20 19:08
run this from the R GUI or the command line. Rstudio suppresses helpful
information in cases like this

**Comment by raingstar** [comment] 2017-04-20 19:53
> library(data.table)
data.table 1.10.5 IN DEVELOPMENT built 2017-04-20 06:04:11 UTC
  The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
  Documentation: ?data.table, example(data.table) and browseVignettes("data.table")
  Release notes, videos and slides: http://r-datatable.com
> data<-fread('gunzip -c /Users/knie/tmp/Modell/Model_01_29_table.gz', header=TRUE,verbose = TRUE)
Input contains no \n. Taking this to be a filename to open
Parameter NAstrings == <<NA>>
None of the 1 na.strings are numeric (such as '-9999').
`filename` argument given, attempting to open a file with such name
File opened, size 0.649690 GB.
Memory mapping ... ok
Detected eol as \n only (no \r afterwards), the UNIX and Mac standard.
Positioned on line 1 starting: <<ty	is_live_yn	auct_end_dt	site>>
Detecting sep ...
  sep==','(ascii 44)  with 1 lines of 2 fields using quote rule 0
  sep=='\t'  with 100 lines of 58 fields using quote rule 0
Detected 58 columns on line 1. This line is either column names or first data row (first 30 chars): <<ty	is_live_yn	auct_end_dt	site>>
'header' changed by user from 'auto' to true
Number of sampling jump points = 101 because 697598466 bytes from row 1 to eof / (2 * 22054 jump0size) == 15815
Type codes (jump 000)    : 2552552224445555555444424455522222222222222222222222222222  Quote rule 0
Type codes (jump 100)    : 2552552224445555555444424455522222222222222222222222222222  Quote rule 0
=====
 Sampled 10051 rows (handled \n inside quoted fields) at 101 jump points including middle and very end
 Bytes from first data row on line 2 to the end of last row: 697598466
 Line length: mean=221.96 sd=21.36 min=166 max=330
 Estimated nrow: 697598466 / 221.96 = 3142888
 Initial alloc = 3892132 rows (3142888 + 23%) using bytes/max(mean-2*sd,min) clamped between [1.1*estn, 2.0*estn]
=====
After 0 type and 0 drop user overrides : 2552552224445555555444424455522222222222222222222222222222
Allocating 58 column slots (58 - 0 dropped)
Reading 672 chunks of 0.990MB (4676 rows) using 8 threads

 *** caught segfault ***
address 0x200000000, cause 'memory not mapped'

Traceback:
 1: fread("gunzip -c /Users/knie/tmp/Modell/Model_01_29_table.gz",     header = TRUE, verbose = TRUE)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

**Comment by MichaelChirico** [comment] 2017-04-20 19:57
If you just run `fread` on the `gunzip`'d file, do you get the same error?

**Comment by raingstar** [comment] 2017-04-20 20:01
data<-fread('/Users/knie/tmp/Modell/Model_01_29_table.gz', header=TRUE,verbose = TRUE)
Input contains no \n. Taking this to be a filename to open
Parameter NAstrings == <<NA>>
None of the 1 na.strings are numeric (such as '-9999').
`filename` argument given, attempting to open a file with such name
File opened, size 0.113498 GB.
Memory mapping ... ok
Detected eol as \r only (no \n or \r afterwards). An old Mac 9 standard, discontinued in 2002 according to Wikipedia.
Positioned on line 1 starting: <<>>
Detecting sep ...
  sep==','(ascii 44)  with 3 lines of 2 fields using quote rule 0
  sep==';'(ascii 59)  with 4 lines of 2 fields using quote rule 0
Detected 2 columns on line 3. This line is either column names or first data row (first 30 chars): <<fI? fc??/??hjY???$???d??_??4>>
'header' changed by user from 'auto' to true
Number of sampling jump points = 101 because 121866075 bytes from row 1 to eof / (2 * 24466 jump0size) == 2490
Error in fread("/Users/knie/tmp/Modell/Model_01_29_table.gz", header = TRUE,  : 
  Line has too few fields when detecting types. Use fill=TRUE to pad with NA. Expecting 2 fields but found 1: << V?FI?5)???>>

**Comment by st-pasha** [comment] 2017-07-07 06:47
@raingstar Could you please check whether the issue still remains in the latest dev version of data.table? If yes, could you manually unzip the file and check whether there is still an error if you try to specify `nrows=10`, `=100`, `=1000`... Is it possible to manually trim the file down in a text editor, so that it still exhibits the "crash" behavior but is small enough to be shared on GitHub.

**Comment by st-pasha** [comment] 2018-05-07 19:00
Closing, `fread` has moved leaps and bounds since the version that OP was using. In addition, since there is no data available to reproduce the problem, I don't see how this can be resolved in any way...

**Closed by st-pasha** 2018-05-07 19:00 UTC
Labels: fread, not reproducible, seg.fault
