### ISSUE TITLE
Backward incompatibility due to #5112 breaking reverse dependencies

### ISSUE THREAD

**Issue by hsbadr** [Rdatatable/data.table#5208] opened 2021-10-11 17:18 UTC
[bugfix for melt when measure.vars is a named list of length=1 #5112](https://github.com/Rdatatable/data.table/pull/5112) made a backwards-incompatible change that takes value column names from `measure.vars` list names, instead of `value.name` argument, in order to make the behavior of `melt()` consistent with the documentation (specifically, for `measure.vars`).

https://github.com/Rdatatable/data.table/blob/96cdef6d03f3fb296778cc7a5550f704d011e083/R/fmelt.R#L217

The above line is now applied if `length(measure.vars) == 1L`  too where `value.name` can be overridden, which breaks some reverse dependencies as they don't find the expected column name (if  relying on using `value.name`) in the output of `melt()`.

So, it's required to contact the maintainers of the reverse dependencies and ask them to change their code (either unlist `measure.vars` or set the names of the list correctly) and run R checks with the development version of `data.table`.

**Comment by tdhock** [comment] 2021-10-11 17:44
iml package has already been fixed, https://github.com/Rdatatable/data.table/pull/5201#issuecomment-939244202

**Comment by mattdowle** [comment] 2021-10-11 19:56
aRbs: same error on CRAN too, not due to data.table-dev
CornerstoneR:  known #5126, not melt related
getDTeval: known #5127, not melt related
iml: known melt related
LMMstar: same error on CRAN too, not due to data.table-dev
maditr: known #5128, not melt related
mlr3proba: same error on CRAN too, not due to data.table-dev
mlr3viz: same error on CRAN too, not due to data.table-dev
NADIA: `nomatch= must be either NA or NULL`, data.table-dev related but not melt, I'll look. Error on CRAN is a different one.
rio: similar multiple error on CRAN too, not due to data.table-dev
SpaDES.core: `error in evaluating the argument 'simGraph' in selecting a method for function '.depsLoadOrder': error in evaluating the argument 'simEdgeList' in selecting a method for function '.depsPruneEdges': INTEGER() can only be applied to a 'integer', not a 'character'` looks data.table-dev related but not sure whether melt related or not.
txshift: same error on CRAN too, not due to data.table-dev
VIM: Another `nomatch= must be either NA or NULL`. data.table-dev but not mult.
LexisNexisTools: Same warning on CRAN too, not due to data.table-dev
sitree: Same warning on CRAN too, not due to data.table-dev
twang: Same warning on CRAN too, not due to data.table-dev

So it is only `iml`. Happy days! I'll look at the 3 datatable-dev ones (NADIA, SpaDES.core and VIM) and once confirmed not melt related, will close this one.

**Comment by mattdowle** [comment] 2021-10-12 08:15
#5214 and #5216 resolve NADIA, SpaDES.core and VIM, unrelated to melt.

**Closed by mattdowle** 2021-10-12 08:15 UTC
