### ISSUE TITLE
If .SDcols is given and j is missing, interpret this to be j=.SD

### ISSUE THREAD

**Issue by rsaporta** [Rdatatable/data.table#1149] opened 2015-05-14 06:52 UTC
To make for cleaner code, 

    # instead of 
    DT[, .SD, .SDcols=colNames]
    DT[, colNames, with=FALSE]

    # We could allow for 
    DT[.SDcols=colNames]

Slightly related to #64

**Comment by eantonya** [comment] 2015-05-14 15:23
I think this makes perfect sense, since `j` conceptually defaults `.SD`.

**Comment by jangorecki** [comment] 2015-05-14 15:30
a little bit related to #1105 which simply states the same what Rick asks here but for `keyby` argument.

**Comment by eantonya** [comment] 2015-05-14 15:38
@jangorecki +1, also makes a lot of sense

**Comment by jangorecki** [comment] 2015-05-14 15:45
more than a sense, it makes chaining much cleaner.
`dt1[ setkeyv(dt2[...], k), j ][...]` turns into `dt1[ dt2[...][keyby=k], j ][...]`

a side advantage having that in `[` is that it automatically allows to measure timing of setting key using my [data.table query](https://github.com/jangorecki/dtq) package.

**Comment by arunsrinivasan** [comment] 2015-05-15 06:49
duplicate of #553

**Comment by rsaporta** [comment] 2015-05-15 08:09
whoops! I thought I had suggested previously.  Clearly I did not search well enough.   Do you want to close out the other issue and keep this one open, since this has a bit more chatter?

**Closed** 2016-09-30 00:13 UTC
Labels: feature request, Low

**Comment by mattdowle** [comment] 2016-09-30 00:33
Hi @rsaporta. With the new commit just now for auto `with=FALSE` and the migration option for `DT[,colNames]`,  I figured that covers the need for `DT[.SDcols=colNames]` so closed this one.  Please check/test though and definitely reopen if I missed something.  (Hope all's good with you.)
