### ISSUE TITLE
[R-Forge #4650] DT[!(x==.)] must be equal to DT[x != .]

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#368] opened 2014-06-08 13:11 UTC
Submitted by: Matt Dowle; Assigned to: Eduard Antonyan; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=4650&group_id=240&atid=978)

As highlighted here :

http://stackoverflow.com/questions/16239153/indexing-dtx-and-dtx-gives-different-results-in-data-table

Related discussion here:

http://stackoverflow.com/questions/16221742/subsetting-a-data-table-by-a-column-without-losing-nas

**Comment by franknarf1** [comment] 2016-11-11 15:45
Fwiw, folks are still getting confused by this: http://stackoverflow.com/q/40542397/

If there's a rationale for how it works now, maybe it could be added to the FAQ..? Current behavior in 1.9.7:

    library(data.table)
    DT = data.table(a = c(1, NA))

    DT[ a != 1 ]
    # Empty data.table (0 rows) of 1 col: a

    DT[ !.(1), on="a" ]
    #     a
    # 1: NA

    fsetdiff(DT, data.table(a = 1))
    #     a
    # 1: NA

So the dropping of NAs only happens in the first case.

**Comment by jangorecki** [comment] 2016-11-11 19:27
Thanks for raising this. The problem is that we would get the row full of NAs, which is pointless and sub-efficient. Just comparing to data.frame on better example we can see that value in `v` is missing so we get quite useless results anyway:
```r
library(data.table)
DT=data.table(a=c(1, NA), v=c(3.2,3.3))
DT[ a != 1 ]
#Empty data.table (0 rows) of 2 cols: a,v
DF=as.data.frame(DT)
DF[DF$a!=1,]
#    a  v
#NA NA NA
```
Re-opening for now just to rethink this later.

**Comment by franknarf1** [comment] 2016-11-11 19:33
> The problem is that we would get the row full of NAs

I'm not sure I follow. With your example, the anti-join gives

    > DT[ !.(1), on="a" ]
        a   v
    1: NA 3.3

So it doesn't seem like it has to behave like a DF and give a row of NAs.

**Comment by jangorecki** [comment] 2016-11-11 19:39
Yes, I'm aware of not-join and `!=` difference, that is why better to rethink if keeping consistency to data.frame here is worth. If you join to NA it will keep value of `v`
```r
merge(DF, data.frame(a=NA), by="a")
#   a   v
#1 NA 3.3
```

**Comment by eantonya** [comment] 2016-11-11 19:59
@franknarf1 If `DT[a != 1]` returns the `NA` row, then so should `DT[a == 1]`, which would then result in an "inconsistency" with the regular join. You can't have it both ways here I'm afraid.

**Comment by franknarf1** [comment] 2016-11-11 20:33
@eantonya Yeah, as you know, my initial thought was that those two should be (set) complementary. 

I think you are arguing based on how NAs appear in `a == 1` vs `a != 1` in R (that is, they appear the same), but data.table doesn't actually build those vectors when it's using indices to handle `i`, instead doing a "bmerge", right? That was my impression, anyways; I don't actually know anything about the implementation. If that's the case, in principle, data.table could deviate from R here if it wanted to, I guess.

Anyway, I was bringing it up again because I think new users (as well as old users like me) can get confused by it, so maybe a FAQ entry would help (assuming there's a coherent rationale). The question being...

> Why doesn't `DT[ col != value ]` show me rows where the column `col` is missing?

It might not be frequent enough for a FAQ, though. Just a thought.

**Comment by eantonya** [comment] 2016-11-11 21:24
@franknarf1 Ok, I don't think how any of this is implemented matters.

Sure, that a reasonable question. But please note that `NA` doesn't just mean "missing". It can also mean apples or unicorns.

The answer is you **have to** either keep `NA`'s in both `DT[col == value]` **and** `DT[col != value]` comparisons (like `data.frame` has chosen to do, albeit poorly), or remove them from both comparisons. You can't consistently keep it in one but not the other.

`data.table` chooses to remove from both, because that seems to fit better with the common user usage pattern.

**Comment by jangorecki** [comment] 2024-03-13 11:05
Current behavior is desired one. Closing as not actionable.

**Closed by jangorecki** 2024-03-13 11:05 UTC
Labels: feature request, consistency
