### ISSUE TITLE
Difference vs. data.frame with handling logical column selection

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#2178] opened 2017-05-24 20:23 UTC
Just noting for the record the following; I assume this will be a won't-fix-type issue. 

`[.data.frame` recycles a logical vector in `j`; it appears `[.data.table` "fills" with `FALSE`:

```
DF = data.frame(a = 1, b = 2, c = 3, d = 4, e = 5)
DF[ , c(TRUE, FALSE)]
#   a c e
# 1 1 3 5

library(data.table)
setDT(DF)
DF[ , c(TRUE, FALSE)]
#    a
# 1: 1
```

IMO there should be an error/warning in this case -- logical indexing in `j` is really designed to work when there are `ncol(x)` items passed.

**Comment by mattdowle** [comment] 2017-06-03 02:26
Yes agreed:  an error unless it is `ncol(DT)` length.  Not even recycling a singleton in this case.  The reason being to avoid confusion in the case of a 2-column `DT` where `DT[,TRUE]` would be recycled but the user probably would have preferred an error that `j` wasn't the correct length.

**Comment by jangorecki** [comment] 2020-01-13 04:28
closing as duplicate of #4115

**Closed by jangorecki** 2020-01-13 04:28 UTC
