### ISSUE TITLE
Rolling regression 

### ISSUE THREAD

**Issue by waynelapierre** [Rdatatable/data.table#4075] opened 2019-11-24 02:39 UTC
Just curious when will the rolling regression functionalities be added to data.table. I am totally using data.table for my data wrangling tasks and really hope I can do rolling regression in data.table.

**Comment by jangorecki** [comment] 2019-11-24 02:54
Yes, it is going to be added, someday, as mentioned in https://github.com/Rdatatable/data.table/issues/2778
There is a long list of rolling functions to implement, efficient implementation of those is usually tricky, even more tricky in plain C. Rolling regression will be a little bit different because currently rolling functions takes atomic vector on input. You are welcome to propose an API for a rolling regression.

**Comment by waynelapierre** [comment] 2019-11-24 03:01
I am currently using the package rollRegres for rolling regressions, maybe you could borrow some ideas from it?

**Comment by jangorecki** [comment] 2019-11-24 03:08
I just found it and it looks very neat, pretty lightweight. It also seems to be feature rich.

**Comment by MichaelChirico** [comment] 2019-11-24 03:33
have you tried frollapply?

as for an optimized rolling regression, if I'm not mistaken there is a formula from linear algebra for updating a linear regression when adding/subtracting one observation, but I'm not sure what linear algebra facilities are available in standard C libraries

**Comment by jangorecki** [comment] 2019-11-24 03:37
@MichaelChirico frollapply won't yet work for regression, see https://github.com/Rdatatable/data.table/issues/2778#issuecomment-546805235, still waiting for feedback. When supported in frollapply, it will be much slower than `rollRegres`, but at least it will very flexible and a little bit more lightweight.

**Comment by smingerson** [comment] 2019-11-24 16:17
The rollRegres package has been removed from CRAN for misrepresentation of authorship.

**Comment by jangorecki** [comment] 2019-11-24 16:44
GitHub version already fixes that so probably sooner or later will come back to CRAN.

**Comment by smingerson** [comment] 2019-11-24 16:47
Great! I swear I looked for a Github page before mentioning it, but I simply must be blind. Found it now.

**Comment by waynelapierre** [comment] 2019-11-24 16:50
I believe the rolling regression function is highly demanded by finance guys like me. I hope to see this functionality added soon. Fingers crossed...

**Comment by waynelapierre** [comment] 2019-11-24 17:19
By the way, the r package roll also has a roll_lm function. Maybe you could borrow some ideas from it.

**Comment by jangorecki** [comment] 2020-03-03 04:54
I briefly went through https://cran.r-project.org/web/packages/rollRegres/vignettes/Comparisons.html and I am now not sure if we really want to have it in data.table. I agree it is highly demanded feature, but not sure if it is really necessary to have it in DT. @mattdowle what is your opinion on that?

**Comment by mattdowle** [comment] 2020-03-03 07:31
I haven't clicked any links or looked at any details, but yes if I understand correctly, if rollRegress can be used with data.table, then that's ideal and there's no need to build it into data.table. 
@waynelapierre You stated you're already using `rollRegress`. Is the problem merely its removal from CRAN, or were there any other problems/inefficiencies using it together with data.table? If the later, Please provide much more detail by way of example code and benchmarks.

**Comment by MichaelChirico** [comment] 2020-06-29 05:33
Seems `rollRegress` is back on CRAN. My understanding is it's using some pretty smart stuff already to do the rolling regression efficiently.

Unless there's something specific & substantial to be gained by including this level of sophistication in `data.table` directly, I would push to add FRs & bugfixes to `rollRegress` instead.

**Comment by jangorecki** [comment] 2020-08-25 07:40
Closing this FR. So far we are not really convinced to have that in scope. I remember I had to convince Matt to have even rolling mean :) We can always re-open in future, so feedback on that FR is still welcome here in this closed issue.

**Closed by jangorecki** 2020-08-25 07:40 UTC
Labels: feature request

**Comment by jangorecki** [comment] 2022-10-07 17:03
This can be achieved using `by.column=FALSE` https://github.com/Rdatatable/data.table/issues/4887 but it obviously will not be super fast.

**Comment by jangorecki** [comment] 2025-08-26 08:22
Whoever is interested in this feature please upvote the first post.
As of now it is out of scope but many upvotes could possibly put it into the scope, although I don't this it would get implemented anytime soon.
Few other rolling functions are on the way.
