### ISSUE TITLE
operations in one data.table will cause changes to all variables this data.table has been assigned to (without making a new copy)

### ISSUE THREAD

**Issue by schoolkid** [Rdatatable/data.table#3847] opened 2019-09-09 07:39 UTC
Issue: Since data.table operator := and other data.table-specific operations (e.g. setnames() ) make changes without creating a new copy, changes to a data table in one variable will apply to all variables this data.table has been assigned to (instead of making a new copy). 

Is there a way to assign a data.table variable to another variable while data.table operations exerted on one variable doesn't apply to the other one?  

Examples: 
```
> x <- data.table(a=c(1,2,3,4,5), b=c(1,2,3,4,5), c=c(1,2,3,4,5))
> x <- data.table(a=c(1,2,3,4,5), b=c(1,2,3,4,5), c=c(1,2,3,4,5))
> y <- x
> ls <- list(rex=x, rex2=x)
> ls
$rex
   a b c
1: 1 1 1
2: 2 2 2
3: 3 3 3
4: 4 4 4
5: 5 5 5

$rex2
   a b c
1: 1 1 1
2: 2 2 2
3: 3 3 3
4: 4 4 4
5: 5 5 5

> x
   a b c
1: 1 1 1
2: 2 2 2
3: 3 3 3
4: 4 4 4
5: 5 5 5
> y
   a b c
1: 1 1 1
2: 2 2 2
3: 3 3 3
4: 4 4 4
5: 5 5 5
> tracemem(x)
[1] "<0x125153000>"
> tracemem(y)
[1] "<0x125153000>"
> tracemem(ls)
[1] "<0x1172fc148>"

```
 Now if I make some changes to x, y and ls all have the same changes as x 
```
> x[, c("a","b"):=lapply(.SD, function(x){x <- x+3}), .SDcol=c("a","b")] 
> x
   a b c
1: 4 4 1
2: 5 5 2
3: 6 6 3
4: 7 7 4
5: 8 8 5
> ls
$rex
   a b c
1: 4 4 1
2: 5 5 2
3: 6 6 3
4: 7 7 4
5: 8 8 5

$rex2
   a b c
1: 4 4 1
2: 5 5 2
3: 6 6 3
4: 7 7 4
5: 8 8 5

> y
   a b c
1: 4 4 1
2: 5 5 2
3: 6 6 3
4: 7 7 4
5: 8 8 5
> tracemem(x)
[1] "<0x125153000>"
> tracemem(y)
[1] "<0x125153000>"
> tracemem(ls)
[1] "<0x1172fc148>"
```

Adding columns to one variable using := will apply to all other variables without creating a copy
```
> y[,d:=c(5,5,5,5,5)] 
> tracemem(x)
[1] "<0x125153000>"
> tracemem(y)
[1] "<0x125153000>"
> tracemem(ls)
[1] "<0x1172fc148>"
```

However, adding variables without using := will create a copy 
```
> y1<-y
> y2<-y
> tracemem(y)
[1] "<0x125153000>"
> tracemem(y1)
[1] "<0x125153000>"
> tracemem(y2)
[1] "<0x125153000>"
> y1$e <- c(6,6,6,6,6)
tracemem[0x125153000 -> 0x117503548]: 
tracemem[0x117503548 -> 0x117503598]: copy $<-.data.table $<- 
> y2[,"e"] <-c(6,6,6,6,6)
tracemem[0x125153000 -> 0x11ef03758]: 
> tracemem(y)
[1] "<0x125153000>"
> tracemem(y1)
[1] "<0x1226bb600>"
> tracemem(y2)
[1] "<0x117e56000>"
```

Changing column names of one data.table using setnames() will cause changes in other variables without making a new copy 
```
> x <- data.table(a=c(1,2,3,4,5), b=c(1,2,3,4,5), c=c(1,2,3,4,5))
> y <- x
> tracemem(x)
[1] "<0x12230b800>"
> tracemem(y)
[1] "<0x12230b800>"
> setnames(y, old = c("a","b","c"), new  = c("aa","bb","cc"))
> tracemem(x)
[1] "<0x12230b800>"
> tracemem(y)
[1] "<0x12230b800>"
```

but changing column names with other data.frame related methods will create a new copy so changes in one variable do not affect others
```
> colnames(y)[1:3] <-c("aaa","bbb","ccc")   # this
tracemem[0x12230b800 -> 0x1198af2f8]: 
tracemem[0x1198af2f8 -> 0x1198af3e8]: 
tracemem[0x1198af3e8 -> 0x1198af438]: colnames<- 
> tracemem(x)
[1] "<0x12230b800>"
> tracemem(y)
[1] "<0x1198af488>"
```
or 
```
> x <- data.table(a=c(1,2,3,4,5), b=c(1,2,3,4,5), c=c(1,2,3,4,5))
> y <- x
> tracemem(x)
[1] "<0x1227b2600>"
> tracemem(y)
[1] "<0x1227b2600>"
> x <- plyr::rename(x, c("a" = "aaa"))
tracemem[0x1227b2600 -> 0x11cb70778]: <Anonymous> 
```

**Comment by MichaelChirico** [comment] 2019-09-09 07:58
Hi @schoolkid thanks for your interest in `data.table`. This is indeed a fundamental feature of `data.table` and so we've tried our best to document it pretty extensively.

In a word, you want to make `y = copy(x)`.

Check out the FAQ: https://cran.r-project.org/web/packages/data.table/vignettes/datatable-faq.html

And also this canonical SO Q&A: https://stackoverflow.com/questions/10225098/understanding-exactly-when-a-data-table-is-a-reference-to-vs-a-copy-of-another

Please follow up on StackOverflow if there's anything else we can help with. I'm closing this since it's a known and documented part of `data.table` and the issue tracker is for unknown/unexpected behavior/bugs/feature requests; if you're struggling with `data.table`, be sure to check out the other vignettes & [top SO Q&A](https://stackoverflow.com/questions/tagged/data.table?tab=Votes)

**Closed by MichaelChirico** 2019-09-09 07:58 UTC
