### ISSUE TITLE
dcast.data.table drop factors

### ISSUE THREAD

**Issue by daynefiler** [Rdatatable/data.table#1032] opened 2015-01-30 20:12 UTC
dcast.data.table does not provide the same drop = FALSE functionality for factors as dcast.data.frame. When using dcast.data.table any levels not represented in the factor do not get empty columns, as they would with dcast.data.frame.

**Comment by arunsrinivasan** [comment] 2015-01-30 21:35
Thanks for the report. But it is duplicate of #893. Fixed in devel.

PS: it always helps to have a minimal reproducible example. Also, it'd be much helpful if you have a look at [these simple list of points on filing issues](https://github.com/Rdatatable/data.table/blob/master/Contributing.md).

**Closed by arunsrinivasan** 2015-01-30 21:35 UTC
