### ISSUE TITLE
fread - to skip comment lines scattered across a file instead of failing to read

### ISSUE THREAD

**Issue by raimisr** [Rdatatable/data.table#2483] opened 2017-11-14 09:33 UTC
In data.table 1.10.4 I need to import a file with comment lines beginning with "#", which are scattered across the file, but fread() fails with the message `"Expected sep ('	') but new line or EOF ends field 1 on line 349515 when reading data: ..."` when `fill = FALSE` (default parameter). I need to set `fill = TRUE` , thus importing all comment lines with missing columns set to empty values and then to use grep to get rid of them by searching "^#". Is it possible that in case `fill = FALSE` , fread() would discard the rows which fail to meet column number criteria issuing some message instead of failing to read the file - what use of failing to read? By the way, excel opens this file without complain.

**Comment by MichaelChirico** [comment] 2017-11-14 09:49
Duplicate of #856. This is somewhere in the middle of my priority list to give a go.

**Closed by MichaelChirico** 2017-11-14 09:49 UTC
