### ISSUE TITLE
Compatibility with the future native pipe

### ISSUE THREAD

**Issue by eliocamp** [Rdatatable/data.table#4872] opened 2021-01-13 00:06 UTC
Right now, r-devel is implementing a native pipe that is incompatible with chaining in data.table. Using [the proposed `d => ` syntax](https://twitter.com/eddelbuettel/status/1349087820783243266) I get an error using [this](https://github.com/wch/r-source/commit/263d6bcf0ba5f2a87d6ba24a795125e19359c675) R version

```r
library(data.table)
data <- CJ(group1 = letters[1:5], group2 = letters[10:14])

data[, x := rnorm(.N)] |> 
  d => d[, mean(x), by = group1]
#> Error: function '[' not supported in RHS call of a pipe
```

If "[" won't be supported as the RHS of a pipe, then no syntax transformation can  make data.table compatible with the `|>` pipe, if I understand correctly. 

I see two ways of addressing this. 

On the one side, we could talk with r-core to present this issue and see if they can change their implementation to make it work. 

Another option would be to create a functional alias to `data.table:::"[.data.table"`, lets say `dt()`. This, for example, seems to work. 

```r
dt <- data.table:::"[.data.table"

data[, x := rnorm(.N)] |> 
   dt(, mean(x), by = group1)
#>    group1          V1
#> 1:      a  0.58876302
#> 2:      b -0.24705765
#> 3:      c  0.07676786
#> 4:      d -0.33047608
#> 5:      e  0.54832829
```

(in fact, it also works with `dt <- base::"["`)

Personally, I don't mind that notation at all. It is true that if such a simple fix resolves the issue, then each user could do it in their own scripts, but I think it might be preferable if data.table provided a standardised alias so that other people's code stays readable. For the record, I don't like `dt` very much, it's just the first thing that came in mind.

**Comment by MichaelChirico** [comment] 2021-01-13 01:23
is this the same as #1984?

**Comment by eliocamp** [comment] 2021-01-13 02:08
Have you linked to the right issue? That's about exporting a data table using fwrite.

**Comment by jangorecki** [comment] 2021-01-13 08:45
This is base R limitation not related to data.table
```r
toupper(letters) |> x => x[1:5]
#Error: function '[' not supported in RHS call of a pipe
```
For me it almost classify as a bug. In case it is not going to be fixed in R-devel then this issue #641 should take care of it.

**Comment by tdeenes** [comment] 2021-01-13 09:17
This is deliberately so. [Special symbols](https://github.com/r-devel/r-svn/blob/5613a5973a066b16f279fc5fabfbf720a3b0cb10/src/main/names.c#L1007) are not allowed in the RHS of a pipe, see [here](https://github.com/r-devel/r-svn/blob/14ab52630535eeba15a866a5b8678f53a7527bf3/src/main/gram.c#L3415).

Nevertheless, only the name of the symbol is checked, so a workaround is to assign a new symbol to the given primitive function. E.g.:
```r
1:4 |> `+`(3)   # error 
add <- `+`
1:4 |> add(3) # OK

extract <- `[`
data.table(x = letters) |> extract(j = x)  # OK
```

**Comment by eliocamp** [comment] 2021-01-13 13:11
Yes, #641 should solve it. IMHO, `dtquery()` is too long a name, though. Especially with the goal of using the pipe in mind. 

```r
mtcars |> 
   dtquery(mpg > 10) |> 
   dtquery(, disp2 := disp/wt) |> 
   dtquery(, .(hp = mean(hp)), by = cyl)
```

To me, that code feel horrible to write and distracting to read, but it's purely a personal matter.

Of course, since we are not talking about cache invalidation, the difficult thing here is naming the thing.

**Comment by jangorecki** [comment] 2021-01-13 14:31
Agree, maybe `sb` from square bracket?

**Comment by eliocamp** [comment] 2021-01-13 15:05
```r
mtcars |> 
  sb(mpg > 10) |> 
  sb(, disp2 := disp/wt) |> 
  sb(, .(hp = mean(hp)), by = cyl)
```



data.table symbols start with dot, perhaps something like that? It might be consistent.. It would also evoke a bit of the `%>% .[]` notation. `.S` (for "Square"?) 

```r
mtcars |> 
  .S(mpg > 10) |> 
  .S(, disp2 := disp/wt) |> 
  .S(, .(hp = mean(hp)), by = cyl)
```

Also, `.t`? because it kinda looks like `.[`

```r
mtcars |> 
  .t(mpg > 10) |> 
  .t(, disp2 := disp/wt) |> 
  .t(, .(hp = mean(hp)), by = cyl)
```

**Comment by grantmcdermott** [comment] 2021-04-29 21:26
Adding my 2 cents:

I really like the idea of a dot prefix, but would go for `.d()`. Fast to type and the most common letter assignment ("d") for a data frame-like object.

Failing that, I would stick to well-known data.table naming conventions, which makes `.DT()` the next obvious candidate IMO.

**Comment by kaboc7** [comment] 2021-05-18 22:40
I personally like the idea of `.S` ("Square") for square brackets but would prefer `.s` (lowercase) because it is easier to type. Because this is intended to be used with the pipe, I think that it should not only be as easier to type as possible but also as short as possible (possibly not more than 2 characters).  This is just my opinion.

Also, I noticed that the following expression does not print anything (even if the last function call is `print()`);
but, the output gets printed if the row with assignment ( `.s(, b := -a)` ) is removed. 

```
.s <- data.table:::`[.data.table`

y <- list(a = 1:5)

setDT(y) |>
    .s(, b := -a) |>
    print()
```
I also tried the next chunk of code but it did not work either. I thought that it would have behaved like `setDT(y)[, b := -a][]` but it did not print anything.

```
setDT(y) |>
    .s(, b := -a) |>
    .s()
```

**Comment by grantmcdermott** [comment] 2021-05-19 21:02
Personally, I'm not so keen on either of `.t()` or `.s()`/`.S()`.

For `.t()`, I think it goes against the mnemonic that data.table uses for its other special operators. `.SD`, `.GRP`, etc. are all based on an abbreviation heuristic rather than the "shape" of the operator. I also think it's too close to the base transpose function, which is where my brain automatically goes when I see `t`... and invites unexpected behaviour in the case of a simple typo. (C.f. `DT |> .t()` vs `DT |> t()`). 

(`dt()` would be even worse ofc because that creates a namespace conflict with a base R function.)

Similarly, `.s()`/`.S()` is too close to `.SD` and `.SDcols` in my view, without being at all related to the underlying functionality.

Taking a step back, IMO the point of this symbol should be to encapsulate a data.table. I know I've already said this, but I genuinely think that `.DT()` is the obvious solution here. It's the widely used shorthand for constructed data.tables already, used throughout the docs, and should be very intuitive enough for newcomers as well. (Although, I'll readily accept `.d()` or `.D` too ;-)

**Comment by philippechataignon** [comment] 2021-05-19 21:34
Personnaly `.dt()` is my preference.

**Comment by hadley** [comment] 2021-05-19 21:50
(FWIW the tidyverse team are planning to work with R core to figure out a placeholder syntax (or equivalent) for the base pipe that there's some hope that 4.2 might allow you do to `dt|> .[i]` (or similar))

**Comment by MichaelChirico** [comment] 2021-05-19 22:38
that sounds great @hadley -- is there a bugzilla/r-devel thread we could use to track progress here to help gauge whether short-term investment in a wrapper is worthwhile?

**Comment by hadley** [comment] 2021-05-19 22:49
Not that I know of, sorry.

**Comment by moodymudskipper** [comment] 2021-05-19 23:13
If such a function is implemented it would be nice to have it work with non data.table data frames and return an output of the original class. I suppose we could make a case to always return a data.table but I like personally the idea of not forcing the user into data.table world if they only need one call (that'd be similar to https://github.com/moodymudskipper/withDT). 

I also wonder if it makes sense to modify by reference using the pipe, maybe it should always copy?

**Comment by MichaelChirico** [comment] 2021-05-20 00:20
@moodymudskipper I don't think we're planning on maintaining any more complicated interface than a simple wrapper for convenience:

```
<foo> = `[.data.table` = function(...) {...}
```

**Comment by eliocamp** [comment] 2021-05-20 01:58
My sense is that iif there is some guarantee that 4.2.0 will support `dt |> .[]`, then there's not much point in introducing a wrapper that could be easily be created by an user on a per-script basis. In the meantime, data.table's documentation could just suggest users to add the wrapper themselves.

**Comment by hadley** [comment] 2021-05-20 11:47
I don't have 4.1.0 handy, but I'd think that this would work:

```R
mtcars |> 
   `[`(mpg > 10) |> 
   `[`(, disp2 := disp/wt) |> 
   `[`(, .(hp = mean(hp)), by = cyl)
```

Given `` `[` `` is three characters, for a shortcut to make sense it would need to be either one or two characters. And of course that's easy to make yourself:

```R
X <- `[`
mtcars |> 
  X(mpg > 10) |> 
  X(, disp2 := disp/wt) |> 
  X(, .(hp = mean(hp)), by = cyl)
```

(I'm not proposing `X` as a name, just using it as an example.)

There's no guarantee that 4.2.0 will have a placeholder syntax, but it's something that I hope we can persuade R core is useful and important. One of the main objections is that `.` is a very small symbol and easy to miss.

**Comment by vincentarelbundock** [comment] 2021-05-20 11:57
Unfortunately, your example does not work (on my machine at least):

``` r
library(data.table)
```

``` r
as.data.table(mtcars) |> 
   `[`(mpg > 10) |> 
   `[`(, disp2 := disp/wt) |> 
   `[`(, .(hp = mean(hp)), by = cyl)
#> Error: function '[' not supported in RHS call of a pipe
```

I need to do something like this instead:

``` r
as.data.table(mtcars) |>
(`[`)(mpg > 10) |>
(`[`)(, disp2 := disp / wt) |>
(`[`)(, .(hp = mean(hp)), by = cyl)
#>    cyl        hp
#> 1:   6 122.28571
#> 2:   4  82.63636
#> 3:   8 209.21429
```

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                                      
#>  version  R version 4.1.0 Patched (2021-05-18 r80324)
#>  os       macOS Big Sur 10.16                        
#>  system   x86_64, darwin17.0                         
#>  ui       X11                                        
#>  language (EN)                                       
#>  collate  en_CA.UTF-8                                
#>  ctype    en_CA.UTF-8                                
#>  tz       America/Toronto                            
#>  date     2021-05-20                                 
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package        * version date       lib source             
#>  backports        1.2.0   2020-11-02 [1] CRAN (R 4.1.0)     
#>  cli              2.5.0   2021-04-26 [1] standard (@2.5.0)  
#>  crayon           1.4.1   2021-02-08 [1] standard (@1.4.1)  
#>  data.table     * 1.14.0  2021-02-21 [1] standard (@1.14.0) 
#>  digest           0.6.27  2020-10-24 [1] CRAN (R 4.1.0)     
#>  ellipsis         0.3.2   2021-04-29 [1] standard (@0.3.2)  
#>  evaluate         0.14    2019-05-28 [1] CRAN (R 4.1.0)     
#>  fansi            0.4.1   2020-01-08 [1] CRAN (R 4.1.0)     
#>  fs               1.5.0   2020-07-31 [1] CRAN (R 4.1.0)     
#>  glue             1.4.2   2020-08-27 [1] CRAN (R 4.1.0)     
#>  htmltools        0.5.1.1 2021-01-22 [1] standard (@0.5.1.1)
#>  knitr            1.30    2020-09-22 [1] CRAN (R 4.1.0)     
#>  languageserver * 0.3.8   2020-12-01 [1] CRAN (R 4.1.0)     
#>  lifecycle        1.0.0   2021-02-15 [1] standard (@1.0.0)  
#>  magrittr         2.0.1   2020-11-17 [1] CRAN (R 4.1.0)     
#>  pillar           1.6.1   2021-05-16 [1] standard (@1.6.1)  
#>  pkgconfig        2.0.3   2019-09-22 [1] CRAN (R 4.1.0)     
#>  purrr            0.3.4   2020-04-17 [1] CRAN (R 4.1.0)     
#>  R.cache          0.14.0  2019-12-06 [1] CRAN (R 4.1.0)     
#>  R.methodsS3      1.8.1   2020-08-26 [1] CRAN (R 4.1.0)     
#>  R.oo             1.24.0  2020-08-26 [1] CRAN (R 4.1.0)     
#>  R.utils          2.10.1  2020-08-26 [1] CRAN (R 4.1.0)     
#>  R6               2.5.0   2020-10-28 [1] CRAN (R 4.1.0)     
#>  reprex           2.0.0   2021-04-02 [1] standard (@2.0.0)  
#>  rlang            0.4.11  2021-04-30 [1] standard (@0.4.11) 
#>  rmarkdown        2.8     2021-05-07 [1] standard (@2.8)    
#>  sessioninfo      1.1.1   2018-11-05 [1] CRAN (R 4.1.0)     
#>  stringi          1.5.3   2020-09-09 [1] CRAN (R 4.1.0)     
#>  stringr          1.4.0   2019-02-10 [1] CRAN (R 4.1.0)     
#>  styler           1.3.2   2020-02-23 [1] CRAN (R 4.1.0)     
#>  tibble           3.1.2   2021-05-16 [1] standard (@3.1.2)  
#>  utf8             1.1.4   2018-05-24 [1] CRAN (R 4.1.0)     
#>  vctrs            0.3.8   2021-04-29 [1] standard (@0.3.8)  
#>  withr            2.3.0   2020-09-22 [1] CRAN (R 4.1.0)     
#>  xfun             0.23    2021-05-15 [1] standard (@0.23)   
#>  xml2             1.3.2   2020-04-23 [1] CRAN (R 4.1.0)     
#>  yaml             2.2.1   2020-02-01 [1] CRAN (R 4.1.0)     
#> 
#> [1] /Library/Frameworks/R.framework/Versions/4.1/Resources/library
```

</details>

**Comment by eddelbuettel** [comment] 2021-05-21 23:18
Under 4.1.0 the first example fails:

```r
> mtcars |> 
+    `[`(mpg > 10) |> 
+    `[`(, disp2 := disp/wt) |> 
+    `[`(, .(hp = mean(hp)), by = cyl)
Error: function '[' not supported in RHS call of a pipe
> 
```

The second one works if and only if `mtcars` was made into a `data.table` object:

```r
> X <- `[`
> mtcars |> 
+   X(mpg > 10) |> 
+   X(, disp2 := disp/wt) |> 
+   X(, .(hp = mean(hp)), by = cyl)
   cyl       hp
1:   6 122.2857
2:   4  82.6364
3:   8 209.2143
> 
```

It is of course nothing but sugar over existing syntax:   

```r
> mtcars[mpg > 10][, .(hp = mean(hp)), by = cyl]
   cyl       hp
1:   6 122.2857
2:   4  82.6364
3:   8 209.2143
> 
```

**Closed** 2021-08-19 20:13 UTC
Labels: feature request
