### ISSUE TITLE
Column subset GForce optimization not applied

### ISSUE THREAD

**Issue by kdkavanagh** [Rdatatable/data.table#4014] opened 2019-10-30 21:33 UTC
According to issue #523, I'd expect subsetting a single column to row .N to be GForce optimized, however it does not appear to be and has a material impact on performance.  Using tail to achieve the same result provides a GForce optimization.  Note that this only seems to appear with col[.N], not col[1].  Data.table version is 1.12.2

```
> grps=updates[,list(
+     count=.N,
+     endTime=timestamp[.N]
+     
+ ),by=list(Symbol, grp)]
Detected that j uses these columns: timestamp
Finding groups using forderv ... 1.942s elapsed (14.5s cpu) 
Finding group sizes from the positions (can be avoided to save RAM) ... 0.106s elapsed (0.092s cpu) 
Getting back original order ... 0.770s elapsed (1.823s cpu) 
lapply optimization is on, j unchanged as 'list(.N, timestamp[.N])'
GForce is on, left j unchanged
Old mean optimization is on, left j unchanged.
Making each group and running j (GForce FALSE) ... 





> grps=updates[,list(
+     count=.N,
+     endTime=tail(timstamp,1)
+     
+ ),by=list(Symbol, grp)]
Detected that j uses these columns: timestamp
Finding groups using forderv ... 1.589s elapsed (11.2s cpu) 
Finding group sizes from the positions (can be avoided to save RAM) ... 0.158s elapsed (0.118s cpu) 
Getting back original order ... 1.491s elapsed (3.390s cpu) 
lapply optimization is on, j unchanged as 'list(.N, tail(timestamp, 1))'
GForce optimized j to 'list(.N, gtail(timestamp, 1))'
Making each group and running j (GForce TRUE) ... 2.532s elapsed (5.011s cpu) 
```

**Comment by ben-schwen** [comment] 2021-10-14 18:35
Although this issue was first, it seems to be more a less a duplicate of #4809 where a broader discussion took place.

Please feel free to add support on that main issue, or reopen this if I'm in error in assigning the duplicate label

**Closed by ben-schwen** 2021-10-14 18:35 UTC
