### ISSUE TITLE
as.data.table(dfidx) fails

### ISSUE THREAD

**Issue by RicoDiel** [Rdatatable/data.table#4526] opened 2020-06-04 13:50 UTC
The class `dfidx` (from the package `dfidx`) exists. Here the idea is to glue and idx `data.frame` to another `data.frame`, and when working with the desired `data.frame`, the idx object always is glued to it. This is for example used in the `mlogit()` package. Conversion of this type to `data.table` fails.

```
library(mlogit)
data("TravelMode",package="AER") 
Mtravel <- dfidx(data     = TravelMode,         
                       shape    = "long",           
                       choice   = "choice",         
                       chid.var = "individual",     
                       alt.var  = "mode")
DTtravel <- as.data.table(Mtravel)
```
Gives the following error message:
```
Error in .subset2(x, i, exact = exact) : 
  attempt to select less than one element in get1index
```

The `mlogit` package requires such an object to carry out the desired regression. dfidx objects also come with their own '['. 
More on this here:
https://cran.microsoft.com/web/packages/dfidx/vignettes/dfidx.html#more_advanced_use_of_dfidx

One could always use `dcast()` and `melt()` to change `data.table`s from wide to long etc. and just use dfidx right before the estimation. Another alternative would be to write a function like the following (which of course is terribly inefficient)

```
my.as.dt <- function(x){
  wide = ncol(x) - 1
  long = nrow(x)
  
  DTprep = list()
  for(i in 1:wide){
    DTprep[[i]] = x[1:long, i][1:long]
  }
  
  DT = as.data.table(DTprep)
  colnames(DT) = colnames(x)[1:wide]
  return(DT)
}
```

Another approach would be to use setDT, which also delivers a warning:

```
DT = setDT(Mtravel)
Warning message:
In setDT(Mtravel) :
  Some columns are a multi-column type (such as a matrix column): [8]. setDT will retain these columns as-is but subsequent operations like grouping and joining may fail. Please consider as.data.table() instead which will create a new column for each embedded column.
```

And the following call of that object will deliver an error:

```
DT
Error in `[.data.table`(x, i, , ) : 
  Column 8 ['idx'] is a data.frame or data.table; malformed data.table.
```

Hopefully you can just give `as.data.table()` and `setDT()` the power to overwrite this and drop the idx `data.frame` (potentially with a warning that some commands which require it in the future may fail).

**Comment by MichaelChirico** [comment] 2020-06-06 09:29
I would lean towards closing... I don't think it's `data.table`'s place to offer `as.data.table` methods for all possible input classes from 3rd packages. Maintainers of `dfidx` could offer such method...

In the meantime I would probably just do:

```
setDT(as.data.frame(Mtravel))
```

**Comment by jangorecki** [comment] 2020-06-06 10:27
@MichaelChirico shouldn't `as.data.table` use default method which should behave like `as.data.table(as.data.frame(x))`?

**Comment by MichaelChirico** [comment] 2020-06-06 10:29
Hmm, you raise a good point. Actually `dfidx` inherits from `data.frame`, so should be `data.frame` method is called. But it's not working...

**Comment by jangorecki** [comment] 2020-06-06 10:32
OK, make sense

**Comment by MichaelChirico** [comment] 2020-06-06 10:39
Hmm, actually looking, maybe it's a `data.table` bug.

The issue is that in `as.data.table.list`, we make an edit to `x` as a `list` by changing the `idx` object of the `dfidx`.

Then we try to extract columns again:

```
xi = x[[i]]
```

BUT this is calling `[[.dfidx`, which expects a `dfidx` object, whereas we've already edited the object so we can't rely on that class method to apply anymore. It might make sense to be sure we've dropped classes in `as.data.table.list` before proceeding.

**Comment by MichaelChirico** [comment] 2020-06-06 11:34
#4529 would make it so that `as.data.table([dfidx object])` works without error, but notice that the output is different as compared to `setDT(as.data.frame(x))` because `dfidx` offers a custom `as.data.frame` method -- to align these two, it would be on the `dfidx` maintainer to offer `data.table` method.

**Comment by jangorecki** [comment] 2020-06-06 11:57
AFAIK, @MichaelChirico please correct me if I am wrong, it should be enough if maintainer of `dfidx` would provide `as.list.dfidx` method that would handle preprocessing.

**Comment by MichaelChirico** [comment] 2020-06-06 12:15
that sounds right to me

**Closed** 2021-04-27 19:29 UTC
