### ISSUE TITLE
DT[, .SD] doesn't seem to retain secondary indices

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#1709] opened 2016-05-17 19:42 UTC
``` r
require(data.table)
dt = data.table(x=1:5, y=6:10)
setindex(dt, x)

indices(dt) # [1] "x"
indices(dt[, .SD]) # NULL
```

**Comment by MarkusBonsch** [comment] 2018-02-14 07:54
@arunsrinivasan I think, this is not a bug, but a feature request since it doesn't break anything or lead to incorrect results.

**Comment by jangorecki** [comment] 2024-01-07 10:36
```r
require(data.table)
dt = data.table(x=1:5, y=6:10)
setindex(dt, x)

indices(dt)
#[1] "x"
indices(dt[, .SD])
#[1] "x"
```
it now does retain index.
we can close this issue by adding a unit test

**Closed** 2024-03-19 15:55 UTC
Labels: feature request, performance, beginner-task
