### ISSUE TITLE
Equality of POSIXct type in "i" fails

### ISSUE THREAD

**Issue by davidrosenberg** [Rdatatable/data.table#1008] opened 2015-01-14 20:05 UTC
I have a POSIXct column and I want to select rows for which the entry in that column equals a particular value:
```
a = Sys.time()
d = data.table(t = c(a, a+1))
d[t==a]
```

This gives the following error:
```
Error in UseMethod("as.data.table") : 
  no applicable method for 'as.data.table' applied to an object of class "c('POSIXct', 'POSIXt')"
```
I'm currently using the following workaround:
```
d[t>=a & t<=a]
```
I just got this issue after upgrading to 1.9.4 from 1.9.2 (I think).

**Comment by arunsrinivasan** [comment] 2015-01-14 22:17
Thanks. It'd be very helpful if you could also try it on development versions, in general, before posting issues.

This is a duplicate of https://github.com/Rdatatable/data.table/issues/955 and that has been fixed (IIRC) recently with @jangorecki's `as.data.table.default` function. But we've not added tests yet. Will close that one after that.

**Closed by arunsrinivasan** 2015-01-14 22:17 UTC
