### ISSUE TITLE
melt.data.table Rstudio abort with fatal error [bug]

### ISSUE THREAD

**Issue by ericsgagnon** [Rdatatable/data.table#1076] opened 2015-03-10 19:23 UTC
melt.data.table causes fatal error and abort in Rstudio under certain circumstances. I was unable to reproduce crash with sample code and cannot share my dataset, but I fixed it as below. 

sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: i386-w64-mingw32/i386 (32-bit)

locale:
      [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
      [1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
      [1] car_2.0-25       magrittr_1.5     stringr_0.6.2    data.table_1.9.5 reshape2_1.4.1   plyr_1.8.1       pryr_0.1        

loaded via a namespace (and not attached):
      [1] chron_2.3-45     codetools_0.2-10 grid_3.1.2       lattice_0.20-30  lme4_1.1-7       MASS_7.3-39      Matrix_1.1-5    
[8] mgcv_1.8-4       minqa_1.2.4      nlme_3.1-120     nloptr_1.0.4     nnet_7.3-9       parallel_3.1.2   pbkrtest_0.4-2  
[15] quantreg_5.11    Rcpp_0.11.5      SparseM_1.6      splines_3.1.2    tools_3.1.2   

Problem Code:
prog.long <- melt(na.omit(prog.data),  
                  id.vars       = prog.id.cols, 
                  measure.vars  = na.omit(questions.cfg)[Survey =='Progression', ColumnIndex ], 
                  variable.name = 'question', 
                  value.name    = 'score', 
                  variable.factor = FALSE, 
                  value.factor  = FALSE
)

Fix: wrapped measure.vars expression in unique as below.
prog.long <- melt(na.omit(prog.data),  
                  id.vars       = c("RNID","PeriodID"),#prog.id.cols, 
                  measure.vars  = unique(na.omit(questions.cfg)[Survey =='Progression', ColumnIndex ]), 
                  variable.name = 'question', 
                  value.name    = 'score', 
                  variable.factor = FALSE, 
                  value.factor  = FALSE
)

Notes:
-every column of prog.long is integer
-class(na.omit(questions.cfg)[Survey =='Progression', ColumnIndex ])  returns [1] "integer"
-na.omit(questions.cfg)[Survey =='Progression', ColumnIndex ] produces integer vector with duplicates - output is:
 [1]  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 24 25 40 41 42 43 44 45 46 47 48 49 50 51 52 53 23 26 40 41
[41] 43 45 23 26 27 28 30 31 32 33 34 36 27 28 29 30 31 32 33 34 36 37 39 29 37 39 44 46 47 48 49 50 51 52 53
-the problem code works properly with another data.table with 74 observations of 40 variables, aside from size of the DT, the only difference appears to be the duplicate entries in the measure.vars argument for the problem code.
-issue also occurs if using reshape::melt, so I am uncertain of location of issue.

Thank you,
Eric

**Comment by arunsrinivasan** [comment] 2015-03-10 19:41
Please read the [contribution guidelines](https://github.com/Rdatatable/data.table/blob/master/Contributing.md). It's hard to fix without having a MRE.

**Comment by arunsrinivasan** [comment] 2015-03-10 19:55
> the problem code works properly with another data.table with 74 observations of 40 variables, aside from size of the DT, the only difference appears to be the duplicate entries in the measure.vars argument for the problem code.

This has been fixed very recently. Please upgrade your devel version and try once again.

**Comment by arunsrinivasan** [comment] 2015-03-12 19:46
Closing as fixed in devel. If you still have the issue, please write back with a MRE.

**Closed by arunsrinivasan** 2015-03-12 19:46 UTC
Labels: fixed in devel, Incomplete

**Comment by markriseley** [comment] 2015-04-08 10:12
I am also getting a fatal crash using devel (1.9.5) data.table's melt. It happens in R studio and also crashes in a clean R console session. Everything in the MRE below works fine if I downgrade to CRAN version 1.9.4.

   # melt.data.table error
    library(reshape2)
    library(data.table)
    DT <- data.table(a = "test", b = 20, c = 30)
    meltedDT <- melt(DT, id.vars = "a", measure.vars = c("b","c"))  # fatal R Studio or R console crash
    
    meltedDT <- melt(DT, id.vars = "a", measure.vars = c("b","c"), verbose = FALSE)
    #> Error in melt.data.table(DT, id.vars = "a", measure.vars = "c", verbose = FALSE) : 
    #> Argument 'verbose' should be logical TRUE/FALSE

    DF <- data.frame(a = "test", b = 20, c = 30)
    meltedDF <- melt(DF, id.vars = "a", measure.vars = c("b","c"))   # works

If I downgrade package 'stringr' from devel version to cran version, the error downgrades from a fatal crash to the error "verbose should be logical TRUE/FALSE" but this still isn't working as intended.

devtools::session_info()
Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.1.2 (2014-10-31)
 system   x86_64, mingw32             
 ui       Rgui                        
 language (EN)                        
 collate  English_United Kingdom.1252 
 tz       Europe/London               

Packages -----------------------------------------------------------------------
 package    * version    date       source                                
 chron      * 2.3-45     2014-02-11 CRAN (R 3.1.2)                        
 data.table   1.9.5      2015-04-08 Github (Rdatatable/data.table@6c654e9)
 devtools   * 1.7.0      2015-01-17 CRAN (R 3.1.2)                        
 magrittr   * 1.5        2014-11-22 CRAN (R 3.1.2)                        
 plyr       * 1.8.1      2014-02-26 CRAN (R 3.1.2)                        
 Rcpp       * 0.11.5     2015-03-06 CRAN (R 3.1.3)                        
 reshape2     1.4.1      2014-12-06 CRAN (R 3.1.2)                        
 rstudioapi * 0.2        2014-12-31 CRAN (R 3.1.2)                        
 stringi    * 0.4-1      2014-12-14 CRAN (R 3.1.2)                        
 stringr    * 0.9.0.9000 2015-03-26 Github (hadley/stringr@a0f03f5)

**Comment by jangorecki** [comment] 2015-04-08 10:34
No errors on my dev data.table in RStudio, try your MRE in fresh R session.

**Comment by markriseley** [comment] 2015-04-10 08:17
Stringr seemed to be triggering it but I noticed I didn't have the latest
version of stringi. Once I updated that the problem went away.

Mark as resolved.
