### ISSUE TITLE
utilize index on `!=` operator

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1220] opened 2015-07-13 11:51 UTC
Could not find such issue so creating as FR. Currently the `!=` will not use index.
```r
library(data.table)
dt <- data.table(a=letters[1:3])
set2keyv(dt,"a")
dt[a=="b", verbose=T]
#Using existing index 'a'
#Starting bmerge ...done in 0.001 secs
#   a
#1: b
dt[a!="b", verbose=T]
#   a
#1: a
#2: c
```

**Comment by DavidArenburg** [comment] 2015-07-13 12:11
I don't think it works on any other parameter except `==` (i.e. not just `!=`)

**Comment by jangorecki** [comment] 2015-07-13 12:14
it works for `%in%` :)

**Comment by DavidArenburg** [comment] 2015-07-13 12:17
Oh, ok. I meant something like 

```r
dt <- data.table(a = 1:3)
set2key(dt, a)
dt[a > 2, verbose = TRUE]
#    a
# 1: 3
dt[a < 2, verbose = TRUE]
#    a
# 1: 1
```

**Comment by jangorecki** [comment] 2015-07-13 12:29
Yeah but it should be easily doable for `!=` while binary search works for `i = !"a"`, and not easily doable for `>`/`<` as it is not even handled by binary search

**Comment by arunsrinivasan** [comment] 2015-07-14 09:28
duplicate of https://github.com/Rdatatable/data.table/issues/1068

**Closed by arunsrinivasan** 2015-07-14 09:28 UTC
