### ISSUE TITLE
`by=list(eval(as.name("colA")))` renames column

### ISSUE THREAD

**Issue by danielkrizian** [Rdatatable/data.table#750] opened 2014-08-01 11:22 UTC
Let's define:
`DT = data.table(colA=1:4, colB=5:8, colC=9:12)`

Then
`DT[, sum(colA), by=list(eval(as.name("colA")))]`

```
       as.name  V1
    1:       1   1
    2:       2   2
    3:       3   3
    4:       4   4
```

will rename `"colA"` to `"as.name"`. 
I believe this is unintended?

The example above is simplified, but the goal is to group by more complicated expressions like `by=list(colA,month(colB))`, while refering to column names by using strings (stored as variables)

**Comment by jangorecki** [comment] 2020-03-22 16:45
to be addressed by
```r
DT = data.table(colA=1:4, colB=5:8, colC=9:12)
DT[, sum(colA), by=list(grp_name=grp),
   env=list(grp_name="colA", grp="colA")]
```
closing as duplicate of #2655

**Closed by jangorecki** 2020-03-22 16:45 UTC
