### ISSUE TITLE
Reproducible crash in fread

### ISSUE THREAD

**Issue by qinjs** [Rdatatable/data.table#1464] opened 2015-12-10 06:27 UTC
Reported On here:
http://stackoverflow.com/questions/34194984/fread-crash-when-reading-the-small-txt-file

**Comment by st-pasha** [comment] 2017-07-06 22:39
This is a duplicate of #2194

**Comment by mattdowle** [comment] 2017-08-04 09:19
Thanks @qinjs. Yes as Pasha linked to, file size is a multiple of 4096 and final row ends abruptly without a final newline. Tested your file works now. Not adding the file to test suite as the file size of this one is a bit bigger and this issue is now well covered by the other test files added in this fix.

**Closed** 2017-08-04 09:40 UTC
Labels: duplicate, fread
