### ISSUE TITLE
optimize x[is.na(col1)] with secondary indices as well

### ISSUE THREAD

**Issue by cooldome** [Rdatatable/data.table#889] opened 2014-10-14 20:59 UTC
Title says it all, it will be very preferrable to make is.na() queries using indices, like x[is.na(col3)]

**Comment by arunsrinivasan** [comment] 2015-07-18 23:28
duplicate of https://github.com/Rdatatable/data.table/issues/1068

**Closed by arunsrinivasan** 2015-07-18 23:28 UTC
Labels: feature request
