### ISSUE TITLE
1.13.0 segfault memory not mapped when assigning new value to character column with %in% row selection

### ISSUE THREAD

**Issue by webbp** [Rdatatable/data.table#4728] opened 2020-09-30 15:08 UTC
Example:
download and unzip [bug.tsv.zip](https://github.com/Rdatatable/data.table/files/5306193/bug.tsv.zip)
```
x=fread('bug.tsv')
x[a%in%c('G20','G40'),b:='b']
```
I can reproduce this in Linux, but not Mac, and my current Mac installation of R is not multicore because Apple disabled openmp in their clang, so this bug could be multicore-related. The bug occurs in 1.13.0 and https://github.com/Rdatatable/data.table/commit/db5afd26562c60bbd25eb160bcbae957474f253a but not in 1.12.8. The bug occurs with both OpenBLAS and default blas/lapack libraries, so is not caused by OpenBLAS.
```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so
*** OR ***
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
(bug occurs either way)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] nvimcom_0.9-75    arrow_1.0.1       data.table_1.13.0

loaded via a namespace (and not attached):
 [1] compiler_4.0.2   tidyselect_1.1.0 bit_1.1-15.2     magrittr_1.5     assertthat_0.2.1 R6_2.4.1         tools_4.0.2      glue_1.4.2       Rcpp_1.0.5
[10] bit64_0.9-7      vctrs_0.3.4      ps_1.3.4         rlang_0.4.7      purrr_0.3.4
```
I tried two different blas libraries, but the bug occurs either way:
```
Package: libopenblas-base
Version: 0.2.20+ds-4
Built-Using: lapack (= 3.7.1-3ubuntu2)
*** OR ***
Package: libblas3
Version: 3.7.1-4ubuntu1
Package: liblapack3
Version: 3.7.1-4ubuntu1
(bug occurs either way)
```

**Comment by sindribaldur** [comment] 2020-10-01 15:41
Could not reproduce on Windows 10 + R 4.0.2 + data.table_1.13.0

**Comment by MichaelChirico** [comment] 2020-10-20 02:33
Sorry I'm not reproducing on Linux Mint 19.3 (built on Ubuntu 18.04), neither on 1.13.0 nor on the commit you referenced.

Closing pending some more information. Please try to reproduce the error on a vanilla R session in the terminal (`R --vanilla`). Your `sessionInfo()` lists several other packages. If these are extraneous to the error they should not be in an MRE; if they are essential to the error that would also be helpful to know. Don't hesitate to reopen if there is more info.

**Closed by MichaelChirico** 2020-10-20 02:33 UTC

**Comment by eddelbuettel** [comment] 2020-10-20 02:43
Just FYI on Ubuntu 20.04 with data.table 1.13.2 this works just fine too:

```r
R> library(data.table)
data.table 1.13.2 using 6 threads (see ?getDTthreads).  Latest news: r-datatable.com
R> x=fread('bug.tsv')
R> x[a%in%c('G20','G40'),b:='b']
R> library(data.table)
data.table 1.13.2 using 6 threads (see ?getDTthreads).  Latest news: r-datatable.com
R> x=fread('bug.tsv')
R> x[a%in%c('G20','G40'),b:='b']
R> x
          a    b
     1: G10 <NA>
     2: G10 <NA>
     3: G20    b
     4: G10 <NA>
     5: G30 sale
    ---         
703026: G10 <NA>
703027: G10 <NA>
703028: G10 <NA>
703029: G10 <NA>
703030: G10 <NA>
R> 
```
