### ISSUE TITLE
saving to a list column with recordPlot and by= only stores the data from the final by= group

### ISSUE THREAD

**Issue by franknarf1** [Rdatatable/data.table#2050] opened 2017-03-03 01:20 UTC
I wasn't sure this was a bug and so brought it [to SO first](http://stackoverflow.com/questions/42449257/saving-plots-in-a-data-table-list-column):

    library(data.table)
    DT = CJ(id = 1, id2 = 1:3)[, .(
        d = as.IDate("2017-01-01")+1:10, v = id*10 + id2*1:10
    ), by=.(id, id2)]
    
    plotDT = DT[, {
        par(mfrow = c(uniqueN(id2), 1), mar = c(2,2,.5,2))
        .SD[,{ 
            plot(d, v, type="l")
        }, by=id2]
        .(p = .(recordPlot()))
    }, by=id]
    
    x11()
    plotDT[id == 1L, replayPlot(p[[1]])]

For me, the two plots are different, as shown in the SO post linked above. 

    > sessionInfo()
    R version 3.3.2 (2016-10-31)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 10 x64 (build 14393)

    locale:
    [1] LC_COLLATE=English_United States.1252 
    [2] LC_CTYPE=English_United States.1252   
    [3] LC_MONETARY=English_United States.1252
    [4] LC_NUMERIC=C                          
    [5] LC_TIME=English_United States.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] data.table_1.10.5

    loaded via a namespace (and not attached):
    [1] tools_3.3.2

Another SO post to update when this is fixed: http://stackoverflow.com/q/43536583/

**Comment by renkun-ken** [comment] 2017-09-14 05:41
This is also related to https://support.rstudio.com/hc/en-us/community/posts/115007426427-title-does-not-refresh-in-plot-produced-by-data-table-with-grouping.

**Comment by MichaelChirico** [comment] 2017-09-14 10:59
I believe same problem as here:

https://stackoverflow.com/q/28400446/3576984

It's all on RStudio's end, sadly.

**Comment by jangorecki** [comment] 2020-04-06 15:51
closing as duplicate of #507

**Closed by jangorecki** 2020-04-06 15:51 UTC
Labels: duplicate
