### ISSUE TITLE
Delete all rows based on a where clause

### ISSUE THREAD

**Issue by vikram-rawat** [Rdatatable/data.table#2297] opened 2017-08-11 05:17 UTC
How to delete a data.table rows based on a criteria

library(data.table)
iris %>% setDT
iris[Species=='setosa',]

if I want to delete all the rows with setosa in it. I don't seem to find any answer on google or anywhere. It seems like there is no functionality for doing this. Please add these functionality. it is very very very useful.

**Comment by MichaelChirico** [comment] 2017-08-11 05:25
please continue your searches, e.g.

https://www.google.com/search?q=remove+rows+data.table&oq=remove+rows+data.table&aqs=chrome..69i57j0l5.2470j0j7&sourceid=chrome&ie=UTF-8

See also #365.

**Comment by jangorecki** [comment] 2017-08-11 05:53
duplicate of #635

**Closed by jangorecki** 2017-08-11 05:53 UTC
Labels: duplicate

**Comment by vikram-rawat** [comment] 2017-08-16 15:51
Is there any solution to it.i mean i have searched everything almost

**Comment by jangorecki** [comment] 2017-08-17 15:12
You can assign result of filtering to same variable name `dt <- dt[x == "a"]`. It will require more memory of course, the amount of memory depends on row count of results.
