### ISSUE TITLE
dcast on data.table now returns data.frame, dcast.data.table as expected a data.table

### ISSUE THREAD

**Issue by marvel64** [Rdatatable/data.table#2282] opened 2017-08-04 02:48 UTC
Hi,

This is probably not a bug, but a change I missed or could not find in the News/Issues.

I have a wrapper function that takes a `data.table` object as input and is supposed to return one after this command.

```
myFun = function(dt){
...
dt = dcast(dt, Var1 ~ Var2, value.var = "N")
dt
}
```

This worked well up until ~6 weeks ago; now after a hiatus from this project, this function returns a plain `data.frame` breaking all following code? The easy fix was.

```
myFun = function(dt){
...
dt = dcast.data.table(dt, Var1 ~ Var2, value.var = "N")
dt
}
```

But at some point, that `dcast` alone was sufficient and the extra `data.table` was unnecessary. I assumed an upgrade could be the reason for this change, but I could not find any documentation on that. Would appreciate any insight?

Thanks!

```
R Under development (unstable) (2016-10-22 r71573)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.6

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
data.table_1.10.5
```

**Comment by franknarf1** [comment] 2017-08-04 03:16
Please create and test with a reproducible example before posting, like...

```
library(data.table)
# data.table 1.10.5 IN DEVELOPMENT built 2017-07-12 23:48:57 UTC; travis
f = function(DT) dcast(DT, V1 ~ V2, value.var = "N")
d = data.table(V1 = 1:5, V2 = rep(2:3, 2:3))[, .N, by=.(V1,V2)]
class(f(d))
# [1] "data.table" "data.frame"
```

I'm on...

```
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 14393)
```

Also, maybe you should upgrade to stable R if possible.

**Comment by jangorecki** [comment] 2018-12-17 18:07
not able to reproduce, also provided example is not complete. Closing, please re-open if this is still an issue for you.

**Closed by jangorecki** 2018-12-17 18:07 UTC
