### ISSUE TITLE
cannot install data.table under R 3.5.2

### ISSUE THREAD

**Issue by kzukowski** [Rdatatable/data.table#3403] opened 2019-02-15 08:51 UTC
Its impossible to install data.table on CentOS :/ since few months

> devtools::install_github("Rdatatable/data.table", build_vignettes = FALSE, force=T)
Downloading GitHub repo Rdatatable/data.table@master
✔  checking for file ‘/tmp/RtmpDbQaRj/remotes70c53af8a6f8/Rdatatable-data.table-e223fab/DESCRIPTION’ ...
─  preparing ‘data.table’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘data.table_1.12.1.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'

Installing package into ‘/home/IZ-PIB/kacper.zukowski/R/x86_64-redhat-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package ‘data.table’ ...
** libs
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG   -I/usr/local/include  -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c assign.c -o assign.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG   -I/usr/local/include  -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c between.c -o between.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG   -I/usr/local/include  -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c bmerge.c -o bmerge.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG   -I/usr/local/include  -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c chmatch.c -o chmatch.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG   -I/usr/local/include  -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c dogroups.c -o dogroups.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG   -I/usr/local/include  -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c fastmean.c -o fastmean.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG   -I/usr/local/include  -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c fcast.c -o fcast.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG   -I/usr/local/include  -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c fmelt.c -o fmelt.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG   -I/usr/local/include  -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c forder.c -o forder.o
forder.c: In function ‘range_str’:
forder.c:296: error: expected end of line before ‘update’
make: *** [forder.o] Error 1
ERROR: compilation failed for package ‘data.table’
* removing ‘/home/IZ-PIB/kacper.zukowski/R/x86_64-redhat-linux-gnu-library/3.5/data.table’
Error in i.p(...) :
  (converted from warning) installation of package ‘/tmp/RtmpDbQaRj/file70c5655e3b82/data.table_1.12.1.tar.gz’ had non-zero exit status

**Comment by kzukowski** [comment] 2019-02-15 08:52
both dev and official version

**Comment by jangorecki** [comment] 2019-02-15 09:20
Issues looks to be duplicate of https://github.com/Rdatatable/data.table/issues/3291. Could you please upgrade your compiler? if it won't help please provide comment in linked issue.

**Closed by jangorecki** 2019-02-15 09:20 UTC
Labels: duplicate
