### ISSUE TITLE
dcast error: Value of SET_STRING_ELT() must be a 'CHARSXP' not a 'NULL'

### ISSUE THREAD

**Issue by SantoshSrinivas79** [Rdatatable/data.table#2900] opened 2018-05-24 08:12 UTC
I searched but couldn't find a resolution to this. Here is a reproducible example.

```
require("data.table")

dt <- structure(list(token = c(12964610L, 12963842L, 12962818L, 12961282L, 
12966658L, 12960258L, 12961026L, 12962050L, 12963330L, 12958978L, 
12961794L, 12963586L, 12960770L, 12957954L, 12959234L, 12960002L, 
12965634L, 12957186L, 12956930L, 12959746L, 12964098L, 12961538L, 
12958210L, 12963074L, 12960514L, 12964866L, 12965122L, 12957698L, 
12958722L, 12966914L, 12965890L, 12964354L, 12966402L, 12965378L, 
12959490L, 12956674L, 12966146L, 12958466L, 12956418L), ticker = c("NIFTY18MAY10800CE", 
"NIFTY18MAY10700PE", "NIFTY18MAY10600PE", "NIFTY18MAY10500PE", 
"NIFTY18MAY11000CE", "NIFTY18MAY10400PE", "NIFTY18MAY10500CE", 
"NIFTY18MAY10600CE", "NIFTY18MAY10650PE", "NIFTY18MAY10300CE", 
"NIFTY18MAY10550PE", "NIFTY18MAY10700CE", "NIFTY18MAY10450PE", 
"NIFTY18MAY10200CE", "NIFTY18MAY10300PE", "NIFTY18MAY10400CE", 
"NIFTY18MAY10900CE", "NIFTY18MAY10100PE", "NIFTY18MAY10100CE", 
"NIFTY18MAY10350PE", "NIFTY18MAY10750CE", "NIFTY18MAY10550CE", 
"NIFTY18MAY10200PE", "NIFTY18MAY10650CE", "NIFTY18MAY10450CE", 
"NIFTY18MAY10800PE", "NIFTY18MAY10850CE", "NIFTY18MAY10150PE", 
"NIFTY18MAY10250PE", "NIFTY18MAY11000PE", "NIFTY18MAY10900PE", 
"NIFTY18MAY10750PE", "NIFTY18MAY10950PE", "NIFTY18MAY10850PE", 
"NIFTY18MAY10350CE", "NIFTY18MAY10050PE", "NIFTY18MAY10950CE", 
"NIFTY18MAY10250CE", "NIFTY18MAY10050CE"), expiry = structure(c(17682, 
17682, 17682, 17682, 17682, 17682, 17682, 17682, 17682, 17682, 
17682, 17682, 17682, 17682, 17682, 17682, 17682, 17682, 17682, 
17682, 17682, 17682, 17682, 17682, 17682, 17682, 17682, 17682, 
17682, 17682, 17682, 17682, 17682, 17682, 17682, 17682, 17682, 
17682, 17682), class = "Date"), strike = c(10800, 10700, 10600, 
10500, 11000, 10400, 10500, 10600, 10650, 10300, 10550, 10700, 
10450, 10200, 10300, 10400, 10900, 10100, 10100, 10350, 10750, 
10550, 10200, 10650, 10450, 10800, 10850, 10150, 10250, 11000, 
10900, 10750, 10950, 10850, 10350, 10050, 10950, 10250, 10050
), ltp = c(1.75, 209, 125.4, 64.3, 1.2, 29.9, 52.9, 18.15, 166.2, 
200.2, 90, 4.85, 43.2, 292.4, 14, 115.25, 1.5, 4.1, 383.3, 19.6, 
2.75, 31.5, 7.2, 9.55, 79.15, 305.7, 1.6, 5.45, 9.5, 512, 406.25, 
261.1, 453.85, 378.4, 151.75, 3.4, 1.35, 230, 620), type = c("CE", 
"PE", "PE", "PE", "CE", "PE", "CE", "CE", "PE", "CE", "PE", "CE", 
"PE", "CE", "PE", "CE", "CE", "PE", "CE", "PE", "CE", "CE", "PE", 
"CE", "CE", "PE", "CE", "PE", "PE", "PE", "PE", "PE", "PE", "PE", 
"CE", "PE", "CE", "CE", "CE"), lot = c("75", "75", "75", "75", 
"75", "75", "75", "75", "75", "75", "75", "75", "75", "75", "75", 
"75", "75", "75", "75", "75", "75", "75", "75", "75", "75", "75", 
"75", "75", "75", "75", "75", "75", "75", "75", "75", "75", "75", 
"75", "75"), underlying = c(10490.95, 10490.95, 10490.95, 10490.95, 
10490.95, 10490.95, 10490.95, 10490.95, 10490.95, 10490.95, 10490.95, 
10490.95, 10490.95, 10490.95, 10490.95, 10490.95, 10490.95, 10490.95, 
10490.95, 10490.95, 10490.95, 10490.95, 10490.95, 10490.95, 10490.95, 
10490.95, 10490.95, 10490.95, 10490.95, 10490.95, 10490.95, 10490.95, 
10490.95, 10490.95, 10490.95, 10490.95, 10490.95, 10490.95, 10490.95
)), .Names = c("token", "ticker", "expiry", "strike", "ltp", 
"type", "lot", "underlying"), row.names = c(NA, -39L), class = c("data.table", 
"data.frame"))

dcast(dt, formula = expiry+strike+lot+underlying ~ type, fun = list(mean, first, first), value.var = list("ltp","token","ticker"), drop =TRUE)
```

However, the below works!

```
dcast(dt, formula = expiry+strike+lot+underlying ~ type, fun = list(mean, first), value.var = list("ltp","token"), drop =TRUE)
```

```
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.10.4-3

loaded via a namespace (and not attached):
[1] compiler_3.4.1 tools_3.4.1
```

**Comment by franknarf1** [comment] 2018-05-24 09:50
`first` is not a good function for fun.aggregate, since `first(c())` is zero-length NULL and dcast wants length of 1. I don't really know why your second version (with only 2/3 of the funs/value.vars) works, but you can change the original to something like...

```
dcast(dt, formula = expiry+strike+lot+underlying ~ type, fun = list(mean, function(x) x[1], function(x) x[1]), value.var = list("ltp","token","ticker"), drop =TRUE)
```

**Comment by MichaelChirico** [comment] 2018-05-24 09:53
To me, that sounds like a bug of `first`, then, no?

`first` is a typical aggregation function; its behavior on zero-length input should match that of other aggregators.

**Comment by jangorecki** [comment] 2018-05-25 01:52
also after using `structure` to create data.table you should call `setDT`.

**Comment by MichaelChirico** [comment] 2019-08-18 10:08
I'm not getting any error on current master so I'm closing. @SantoshSrinivas79 please close if the issue is still affecting you

**Closed by MichaelChirico** 2019-08-18 10:08 UTC
