### ISSUE TITLE
fread doen't work for .txt.gz but it does for the same file with .csv.gz extension

### ISSUE THREAD

**Issue by rodo-nunez** [Rdatatable/data.table#3136] opened 2018-11-06 02:42 UTC
Hello!

I tried to read a .txt.gz file with `fread` using the new feature for reading .gz files (#717 ), but I got a warning and a 0 row table. But **when I manually change the extension from .txt.gz to .csv.gz I have no problem** and I obtain the dataset that I have compressed. 

I think this could be a bug. For now I changed the name of my files using batch, but it would be nice if `fread` was less strict with the extensions. 

I was using version 1.11.8

Example:

`   data = fread(input = "file.txt.gz",
               nrows = 100,
               colClasses = 'character',
               fill=TRUE)  `

` 
Taking input= as a system command ('file.txt.gz') and a variable has been used in the expression passed to 'input='. Please use fread(cmd=...). There is a security concern if you are creating an app, and the app could have a malicious user, and the app is not running in a secure envionment; e.g. the app is running as root. Please read item 5 in the NEWS file for v1.11.6 for more information and for the option to suppress this message.
"files" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
Warning messages:
1: running command 'C:\Windows\system32\cmd.exe /c (file.txt.gz) > C:\Documents\file.txt.gz' had status 1 
2: In (if (.Platform$OS.type == "unix") system else shell)(paste0("(",  :
  '(file.txt.gz) > C:\Users\rununez\AppData\Local\Temp\RtmpGaf6n4\file393417ff2352' execution failed with error code 1
3: In fread(input = "file.txt.gz", nrows = 100, colClasses = "character", fill = TRUE) :
  File 'C:\Users\rununez\AppData\Local\Temp\RtmpGaf6n4\file393417ff2352' has size 0. Returning a NULL data.table.
`

This is the output I obtain when I print the resulting dataset:

`
data 
`
`
Null data.table (0 rows and 0 cols)
`

Manually changing the file name to "file.csv,gz" (and changing the input variable accordingly) solves the problem

`
 data = fread(input = "file.csv.gz",
               nrows = 100,
               colClasses = 'character',
               fill=TRUE)  `

**Comment by rodo-nunez** [comment] 2018-11-22 01:46
After a while, I tried this again and it worked. Maybe I was just dumb and tried to open a “file.csv.gz” with a file = “file.txt.gz” xD. Maybe there should be an error message saying that there is no file with that name. So I think it is not a bug, but an improvement idea for the error message.

**Comment by tm-89** [comment] 2019-05-27 13:39
Just came across the same mistake. Turned out I used the wrong path and the file simply didn't exist. The error/warning message sounds very misleading and it would be helpful to tell the user that the file simply doesn't exist.

**Comment by NoushinN** [comment] 2020-04-02 16:17
One solution that's worked for me with this error is manually importing the dataset from the files console, pictures below:

![image](https://user-images.githubusercontent.com/37668936/78272527-7abe7100-74c2-11ea-9f5b-bf16eef3f52d.png)

![image](https://user-images.githubusercontent.com/37668936/78272302-3337e500-74c2-11ea-90c8-39bded7073b4.png)

**Comment by jangorecki** [comment] 2020-04-05 10:29
I tried the same command
```r
data = fread(input = "file.txt.gz", nrows = 100, colClasses = 'character', fill=TRUE)
```
and getting meaningful error now

- linux
```
#Error in fread(input = "file.txt.gz", nrows = 100, colClasses = "character",  : 
#  File 'file.txt.gz' does not exist or is non-readable. getwd()=='/home/me'
```

- windows
```
Error in fread(input = "file.txt.gz", nrows = 100, colClasses = "character",  :
  File 'file.txt.gz' does not exist or is non-readable. getwd()=='C:/'
```

It seems that the issue is fixed then, closing.

**Comment by mattdowle** [comment] 2021-05-18 21:52
I installed v1.11.8 and could not reproduce this problem. Well, I could, but not as described. [Aside: to install v1.11.8 on Linux with recent versions of `gcc`, it is necessary to add `-fcommon` to `CFLAGS` in `~/.R/Makevars` to work around the multiple-definition linker errors.]

By tracing the R code of `fread()` in that version (1.11.8) I established that the reported error `Taking input= as a system command ... and a variable has been used` only occurs if `input=` is a variable, not a literal string as presented in the report. I think the report was modified from what was actually running. This theory seems confirmed by the English "and changing the input variable accordingly" later in the original report above.   That's why adding the reported test verbatim in https://github.com/Rdatatable/data.table/pull/4356 wasn't sufficient.

So my guess is that was actually run was :

```
var = "file.txt.gz "   # note the space
fread(var)             # note the other arguments reported were a red herring
fread(input=var)       # or naming input= is the same

Taking input= as a system command ('file.txt.gz ') and a variable has been used in the expression passed to
`input=`. Please use fread(cmd=...). There is a security concern if you are creating an app, and the app could
have a malicious user, and the app is not running in a secure environment; e.g. the app is running as root.
Please read item 5 in the NEWS file for v1.11.6 for more information and for the option to suppress this
message.
sh: 1: file.txt.gz: not found
Null data.table (0 rows and 0 cols)
Warning messages:
1: In (if (.Platform$OS.type == "unix") system else shell)(paste0("(",  :
  error in running command
2: In fread(var) :
  File '/tmp/RtmpL2RYEQ/file3099d2cc80e09' has size 0. Returning a NULL data.table.
```
I'm guessing that the space in the file name was also removed from the error message by the OP manually when they pasted the error message and then changed the filename in it to something generic rather than their actual filename; i.e. note the actual error message reproduced here contains a space in this part: `('file.txt.gz ')`.

I'm pretty sure that's what happened, and this is reproducible in current dev too.

Perhaps adding `Taking input= as a system command [because it contains one or more spaces]` would improve the message. I'll add that and close. Please reopen if I've got anything wrong, or anything else could be done better.

**Closed** 2021-05-18 23:14 UTC
Labels: fread
