### ISSUE TITLE
'by' operations much slower when verbose=TRUE

### ISSUE THREAD

**Issue by joshhwuu** [Rdatatable/data.table#6286] opened 2024-07-16 22:25 UTC
Seen when benchmarking #6228 , seems that by operations run _much_ slower with `verbose=TRUE`

```R
dt = data.table(a = 1:1000000)
system.time(copy(dt)[, 1, by = a])
#   user  system elapsed 
#  0.263   0.001   0.202

system.time(copy(dt)[, 1, by = a, verbose=TRUE])
#   user  system elapsed 
#  1.375   1.505   2.820
```

My initial guess for the culprits are the numerous calls to `clock()` when `verbose=TRUE`

`#` `Output of sessionInfo()`
```
R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/Vancouver
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.15.99 testthat_3.2.1.1   devtools_2.4.5     usethis_2.2.3     

loaded via a namespace (and not attached):
 [1] miniUI_0.1.1.1    compiler_4.4.1    brio_1.1.5        promises_1.3.0   
 [5] Rcpp_1.0.12       stringr_1.5.1     callr_3.7.6       later_1.3.2      
 [9] fastmap_1.2.0     mime_0.12         R6_2.5.1          htmlwidgets_1.6.4
[13] desc_1.4.3        profvis_0.3.8     rprojroot_2.0.4   shiny_1.8.1.1    
[17] rlang_1.1.4       cachem_1.1.0      stringi_1.8.4     httpuv_1.6.15    
[21] fs_1.6.4          pkgload_1.3.4     memoise_2.0.1     cli_3.6.2        
[25] withr_3.0.0       magrittr_2.0.3    ps_1.7.6          processx_3.8.4   
[29] digest_0.6.35     rstudioapi_0.16.0 xtable_1.8-4      remotes_2.5.0    
[33] lifecycle_1.0.4   vctrs_0.6.5       glue_1.7.0        urlchecker_1.0.1 
[37] sessioninfo_1.2.2 pkgbuild_1.4.4    purrr_1.0.2       tools_4.4.1      
[41] ellipsis_0.3.2    htmltools_0.5.8.1

```

**Comment by joshhwuu** [comment] 2024-07-16 22:47
Investigating:

I replaced all calls to `clock()` with `wallclock`, and it seems that the performance improved dramatically:

```R
# with wallclock()
system.time(copy(dt)[, 1, by = a, verbose=TRUE])
# Detected that j uses these columns: <none>
# Finding groups using forderv ... forder.c received 1000000 rows and 1 columns
# 0.008s elapsed (0.007s cpu) 
# Finding group sizes from the positions (can be avoided to save RAM) ... 0.005s elapsed (0.041s cpu) 
# Optimization is on but left j unchanged (single plain symbol): '1'
# Making each group and running j (GForce FALSE) ... 
#   memcpy contiguous groups took 0.031s for 1000000 groups
#   eval(j) took 0.028s for 1000000 calls
# 0.274s elapsed (0.273s cpu) 
#    user  system elapsed 
#   0.322   0.020   0.289

# with clock() ie current
system.time(copy(dt)[, 1, by = a, verbose=TRUE])
# Detected that j uses these columns: <none>
# Finding groups using forderv ... forder.c received 1000000 rows and 1 columns
# 0.008s elapsed (0.024s cpu) 
# Finding group sizes from the positions (can be avoided to save RAM) ... 0.005s elapsed (0.043s cpu) 
# Optimization is on but left j unchanged (single plain symbol): '1'
# Making each group and running j (GForce FALSE) ... 
#   memcpy contiguous groups took 0.453s for 1000000 groups
#   eval(j) took 0.438s for 1000000 calls
# 1.955s elapsed (0.509s cpu) 
#    user  system elapsed 
#   0.577   1.446   1.969
```

Can anyone comment on the difference between using `clock()` and `wallclock()`? If there aren't any issues with `wallclock()` I'll file a PR to refactor the current calls.

**Comment by Anirban166** [comment] 2024-07-16 22:50
Can reproduce. Adding a zero adds to a more noticeable difference:
```r
library(data.table) # 1.15.99
dt = data.table(a = 1:10000000)
system.time(copy(dt)[, 1, by = a])
#   user  system elapsed 
#  1.924   0.039   1.849 
system.time(copy(dt)[, 1, by = a, verbose=TRUE])
# Detected that j uses these columns: <none>
# Finding groups using forderv ... forder.c received 10000000 rows and 1 columns
# 0.069s elapsed (0.155s cpu) 
# Finding group sizes from the positions (can be avoided to save RAM) ... 0.034s elapsed (0.032s cpu)
# Optimization is on but left j unchanged (single plain symbol): '1'
# Making each group and running j (GForce FALSE) ... 
#   memcpy contiguous groups took 4.140s for 10000000 groups
#   eval(j) took 4.099s for 10000000 calls
# 18.0s elapsed (6.423s cpu) 
#   user  system elapsed 
#  6.611  11.598  18.096 
```

**Comment by joshhwuu** [comment] 2024-07-16 23:08
Interesting, this doesn't happen with 1.15.4
I'll see if I can find the reason
```R
library(data.table) # 1.15.4
dt = data.table(a = 1:10000000)
system.time(copy(dt)[, 1, by = a, verbose=TRUE])
# Detected that j uses these columns: <none>
# Finding groups using forderv ... forder.c received 10000000 rows and 1 columns
# 0.370s elapsed (0.020s cpu) 
# Finding group sizes from the positions (can be avoided to save RAM) ... 0.050s elapsed # (0.050s cpu) 
# Optimization is on but left j unchanged (single plain symbol): '1'
# Making each group and running j (GForce FALSE) ... 
#   memcpy contiguous groups took 0.258s for 10000000 groups
#   eval(j) took 0.234s for 10000000 calls
# 2.230s elapsed (2.150s cpu) 
#    user  system elapsed 
#    2.23    0.06    2.67
```

**Comment by Anirban166** [comment] 2024-07-16 23:17
> Can anyone comment on the difference between using `clock()` and `wallclock()`?

I reckon `clock()` is used for profiling CPU time and likely ends up making more system calls in the process (has been found to be slower before, for e.g. [this comment](https://github.com/Rdatatable/data.table/blob/a01f00f7438daf4612280d6886e6929fa8c8f76e/inst/tests/benchmark.Rraw#L109))

`wallclock()` does seem to have a simpler [implementation](https://github.com/Rdatatable/data.table/blob/a01f00f7438daf4612280d6886e6929fa8c8f76e/src/fread.c#L384), so in theory the overhead difference could be true.

> Interesting, this doesn't happen with 1.15.4
I'll see if I can find the reason

Good find! Seems like a potential performance regression sneaked in.

**Comment by joshhwuu** [comment] 2024-07-16 23:33
NVM, it seems that this only affects non-Windows. AFAIK there are slight implementation differences between `clock()`s in Linux and Windows. I just tried to recreate this on Windows R with 1.15.99, but there is no issue:

```R
library(data.table)
# data.table 1.15.99 IN DEVELOPMENT built 2024-07-16 23:30:59 UTC; joshu using 8 threads (see ?getDTthreads).  Latest news: r-datatable.com
dt = data.table(a = 1:1000000)
system.time(copy(dt)[, 1, by = a])
#    user  system elapsed 
#    0.17    0.00    0.17 
system.time(copy(dt)[, 1, by = a, verbose=TRUE])
# Detected that j uses these columns: <none>
# Finding groups using forderv ... forder.c received 1000000 rows and 1 columns
# 0.020s elapsed (0.000s cpu) 
# Finding group sizes from the positions (can be avoided to save RAM) ... 0.000s elapsed (0.000s cpu) 
# Optimization is on but left j unchanged (single plain symbol): '1'
# Making each group and running j (GForce FALSE) ... 
#   memcpy contiguous groups took 0.029s for 1000000 groups
#   eval(j) took 0.022s for 1000000 calls
# 0.230s elapsed (0.220s cpu) 
#    user  system elapsed 
#    0.22    0.03    0.27 
```

**Comment by tdhock** [comment] 2024-07-17 00:53
I don't think anybody cares about performance when verbose=TRUE, since it is for debugging

**Comment by joshhwuu** [comment] 2024-07-17 01:01
> I don't think anybody cares about performance when verbose=TRUE, since it is for debugging

Hm, I can understand that but switching to `wallclock()` is trivial as it is already implemented and gives us consistent performance over different platforms. Additionally, IMO a performance difference of over 10x seems a little egregious, even for a debug mode

**Comment by tdhock** [comment] 2024-07-17 01:17
ok if you want to make the change, then make sure to add an atime performance test

**Comment by tdhock** [comment] 2024-07-17 11:51
https://github.com/Rdatatable/data.table/wiki/Performance-testing

**Comment by jangorecki** [comment] 2024-07-21 14:19
For verbose=T we sometimes add extra forder calls (or potentially other heavy calls) just to report more information to the console. I would say this is acceptable. For performance verbose needs to be F.

**Comment by aitap** [comment] 2024-08-25 08:47
Since the values of `wallclock()` are frequently subtracted to obtain durations, can we use `clock_gettime(CLOCK_MONOTONIC)` instead of `CLOCK_REALTIME`? Subtracting wall-clock values [may cause some confusing bugs](https://rachelbythebay.com/w/2023/01/29/bash/) if the system time is adjusted in the background. [POSIX requires both `CLOCK_REALTIME` and `CLOCK_MONOTONIC`](https://pubs.opengroup.org/onlinepubs/9799919799/functions/clock_getres.html).

Empirically, on `amd64` Linux, both `CLOCK_REALTIME` and `CLOCK_MONOTONIC` use the [vDSO](https://www.man7.org/linux/man-pages/man7/vdso.7.html) and thus avoid the system call penalty, but `clock()` is required to measure the _CPU_ time, so uses `CLOCK_PROCESS_CPUTIME_ID` and costs an extra system call, as does `getrusage`.

**Comment by MichaelChirico** [comment] 2024-09-03 05:25
Thanks for pointing out `CLOCK_MONOTONIC`!

`wallclock()` (according to a comment that's unfortunately been lost) is adapted from R's own `currentTime()`, which uses `CLOCK_REALTIME`:

https://github.com/Rdatatable/data.table/commit/0b3cd65381656330b66c5670c2c044f76e2ac03f#diff-4052380a202e1373dcfdfa2fff9850d61b26758fc0475260b2871e70f0d153a1R129

https://github.com/r-devel/r-svn/blob/4778112deccaf909e93a0bec77d6c5ccd0e9155f/src/main/times.c#L105

`CLOCK_REALTIME` has always been used (13 years) since `currentTime()` was implemented, I don't see any discussion of the issue you raise on r-devel or bugzilla either:

https://github.com/r-devel/r-svn/commit/8cf61368e822be6224e9c36f166d1818fd68aa28
https://github.com/search?q=repo%3AMichaelChirico%2Fr-mailing-list-archive%20%22CLOCK_REALTIME%22&type=code
[long bugzilla link](https://bugs.r-project.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=CONFIRMED&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&component=Accuracy&component=Add-ons&component=Analyses&component=Documentation&component=Graphics&component=I%2FO&component=Installation&component=Installer&component=Language&component=Low-level&component=Mac%20GUI%20%2F%20Mac%20specific&component=Misc&component=Models&component=S4methods&component=Startup&component=System-specific&component=Toolchain%20and%20libraries&component=Translations&component=Windows%20GUI%20%2F%20Window%20specific&component=Wishlist&f0=OP&f1=OP&f2=product&f3=component&f4=alias&f5=short_desc&f7=content&f8=CP&f9=CP&j1=OR&list_id=33244&o2=substring&o3=substring&o4=substring&o5=substring&o6=substring&o7=matches&product=R&product=Rtools&query_format=advanced&resolution=---&resolution=FIXED&resolution=INVALID&resolution=NOT%20REPRODUCIBLE&resolution=SPAM&resolution=WONTFIX&resolution=Works%20as%20documented&resolution=WISHLIST&resolution=DUPLICATE&resolution=WORKSFORME&resolution=CONTRIBUTED%20PACKAGE&resolution=MOVED&v2=CLOCK_REALTIME&v3=CLOCK_REALTIME&v4=CLOCK_REALTIME&v5=CLOCK_REALTIME&v6=CLOCK_REALTIME&v7=%22CLOCK_REALTIME%22)

I would suggest starting this as a discussion on r-devel first; at a minimum, it's out of scope here & gets its own issue.

**Closed** 2024-09-04 19:54 UTC
