### ISSUE TITLE
[Request] referring to columns by new names in .SDcols

### ISSUE THREAD

**Issue by franknarf1** [Rdatatable/data.table#1803] opened 2016-08-05 15:54 UTC
It would be nice to be able to rename `.SDcols` as you can do with `by=.(newname = oldname)`. For example, in aggregation, you might want the result to be named like `Sumx` instead of `x`. For example [in this SO answer](http://stackoverflow.com/a/38792895/), the table has to be `setnames`-ed afterwards.

```
DT = setDT(structure(list(desc = c("a", "a", "a", "b", "b", "b", "b", "b", 
"c", "c", "a", "a", "a", "b", "b", "b", "b", "b", "c", "c"), 
    variable = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L), class = "factor", .Label = c("1", 
    "2")), x = c(1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L, 1L, 
    2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L), y = c(10L, 9L, 8L, 
    7L, 6L, 5L, 4L, 3L, 2L, 1L, 10L, 9L, 8L, 7L, 6L, 5L, 4L, 
    3L, 2L, 1L)), .Names = c("desc", "variable", "x", "y"), row.names = c(NA, 
-20L), class = "data.frame"))

DT[, lapply(.SD, sum), by=desc, .SDcols=x:y]

#    desc  x  y <- want Sumx Sumy here
#1:    a 12 54
#2:    b 60 50
#3:    c 38  6
```

As a workaround, we could `DT[, lapply(c(Sum = .SD), sum), by=desc, .SDcols=x:y]`, but this doesn't quite work; prevents `gsum` from being used; and is warned about when verbose is on ("The result of j is a named list. It's very inefficient [...]").

Related to #642 about letting `.SDcols` take unquoted names. 

---

[A goofy example from SO](http://stackoverflow.com/questions/43258016/dynamically-setting-the-name-label-of-a-dynamically-selected-column-in-r-data-ta) to update if this is implemented:

```
library(data.table)
x <- data.table(a = 1:10, b = letters[1:10])

# current syntax for getting .(a, VaR = b)...
mysdcols = c(a = "a", Var = "b") 
x[a > 7, setnames(.SD, mysdcols, names(mysdcols)), .SDcols=mysdcols]

# OP wants something like
x[a > 7, .SD, .SDcols=c("a", VaR = "b")]
```

**Comment by jangorecki** [comment] 2016-08-05 16:45
The best option would be to accept named character vector in `.SDcols` so the names can be used as replacement for column names.

**Comment by franknarf1** [comment] 2017-03-28 17:37
Another example:

```
set.seed(1)
DT = data.table(id = rep(LETTERS[1:3], each = 3))[, `:=`(
  sid = rowid(id),
  v   = sample(0:2, .N, replace = TRUE)
)][]
DT
```

Now the goal is to compute `cumsum(v), by=id`, but instead using a non-equi join (for demonstration purposes):

```
DT[, vsum := 
  DT[.SD, on=.(id, sid <= sid), sum(v), by=.EACHI]$V1
, .SDcols = c("id", "sid")]
```

It would be nice if I could write `.SDcols = c("id", my_sid = "sid")` and `on=.(id, sid <= my_sid)` to better differentiate the cols in `on=`.

**Comment by MichaelChirico** [comment] 2020-04-30 07:40
Closing as duplicate of #3146

**Closed by MichaelChirico** 2020-04-30 07:40 UTC
Labels: feature request, programming
