### ISSUE TITLE
[R-Forge #2430] Potential RAM/cache inefficiency reported

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#601] opened 2014-06-08 13:16 UTC
Submitted by: Matt Dowle; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2430&group_id=240&atid=978)

It's still a little unclear but this might lead to an inefficiency somewhere in data.table :

http://stackoverflow.com/questions/13688840/what-caused-my-elapsed-time-much-longer-than-user-time

**Comment by jangorecki** [comment] 2019-01-29 10:40
Report is from 2012 and it does not provide reproducible example. Quite a lot of internals has been reworked since v1.8.6. It was already uncleared at the time when opened on R-forge. Closing as non reproducible.

**Closed by jangorecki** 2019-01-29 10:40 UTC
Labels: performance
