### ISSUE TITLE
test.data.table() error when optional package reshape is not installed

### ISSUE THREAD

**Issue by skanskan** [Rdatatable/data.table#2105] opened 2017-04-07 12:24 UTC
#Hello.

I've just used test.data.table() to ckeck my data.table  1.10.5 installation and got this errors:

> 
> Running test id 168     Don't know how to automatically pick scale for object of type ITime. Defaulting to continuous.
> Test 168 Error in seq.int(0, to0 - from, by) : 'to' cannot be NA, NaN or infinite
> Running test id 168.1     Test 168.1 Error in seq.int(0, to0 - from, by) : 'to' cannot be NA, NaN or infinite
> Running test id 486     Tests 487 and 488 not run. If required call library(reshape) first.
> Running test id 1383.2     Tests 1383.3 not run. If required call library(reshape) first.
> Error in eval(expr, envir, enclos) : 
>   2 errors out of 5737 (lastID=1759, endian==little, sizeof(long double)==16, sizeof(pointer)==8) in inst/tests/tests.Rraw on Fri Apr 07 14:17:57 2017. Search tests.Rraw for test numbers: 168, 168.1.

I have reshape2 installed instead of reshape, maybe the test should move to the newer packages.

**Comment by mattdowle** [comment] 2017-04-08 01:24
Ok will try.  It was a bit of a nightmare to test reshape and reshape2 interaction.  The tests detach both packages and then reattach them in a particular order so that one is above the other in the `search()` path.  Now that time has passed and we no longer import either, I'm not sure the best thing to do:  yes maybe we should just remove reshape from Suggests and its tests.

**Comment by MichaelChirico** [comment] 2017-04-08 01:27
the tests at least guarantee consistency with reshape2 operations, as long
as that's still a priority should probably keep the tests in.

**Comment by skanskan** [comment] 2017-04-08 01:36
What about the other errors?
Running test id 168 Don't know how to automatically pick scale for object of type ITime. Defaulting to continuous.
Test 168 Error in seq.int(0, to0 - from, by) : 'to' cannot be NA, NaN or infinite
Running test id 168.1 Test 168.1 Error in seq.int(0, to0 - from, by) : 'to' cannot be NA, NaN or infinite

**Comment by MichaelChirico** [comment] 2017-04-08 01:41
actually, only tests 168 and 168.1 are showing errors. the others are just
messages produced along the way

**Comment by skanskan** [comment] 2017-04-08 11:23
But are this errors caused by my R+data.table installation or settings?
Can they affect my daily operation?

**Comment by MichaelChirico** [comment] 2017-04-08 12:43
look at the file inst/tests/tests.Rraw and search for those test #s

**Comment by mattdowle** [comment] 2018-03-13 23:46
These test fails (168 and 168.1) were caused by a ggplot2 update, iirc.  If not, the problem has been fixed some time ago I think.   Is test.data.table() ok for you now @skanskan ?
I'm going to remove `reshape` Suggests as part of #2671.

**Comment by skanskan** [comment] 2018-03-14 00:00
My last run:

```
Running test id 167      Test 167 ran without errors but failed check that x equals y:
> x = names(print(ggplot(DT, aes(b, f)) + geom_point()))[c(1, 3)] 
First 6 of 2 (type 'character'): [1] "data"   "scales"
> y = c("data", "plot") 
First 6 of 2 (type 'character'): [1] "data" "plot"
1 string mismatch
Running test id 167.2      Test 167.2 ran without errors but failed check that x equals y:
> x = names(print(ggplot(DT) + geom_hex(aes(b, f)) + facet_wrap(~grp)))[c(1,      3)] 
First 6 of 2 (type 'character'): [1] "data"   "scales"
> y = c("data", "plot") 
First 6 of 2 (type 'character'): [1] "data" "plot"
1 string mismatch
Running test id 168      Don't know how to automatically pick scale for object of type ITime. Defaulting to continuous.
Don't know how to automatically pick scale for object of type ITime. Defaulting to continuous.
Running test id 486      Tests 487 and 488 not run. If required call library(reshape) first.
Running test id 896.4225      Tests 897-899 not run. If required call library(bit64) first.
Running test id 1372.2      Tests 1372.3+ not run. If required call library(GenomicRanges) first.
Running test id 1383.2      Tests 1383.3 not run. If required call library(reshape) first.
Tests 1383.4 not run. If required call library(caret) first.
Running test id 1626.68      Tests 1626.[69-76] not run. If required call library(bit64) first.
Running test id 1729.14      Tests 1730 & 1731 not run. If required call library(bit64) first.
Running test id 1750.34      Test 1750.[41-48] not run. If required call library(bit64) first.
Running test id 1751.2      Test 1752 not run. If required call library(nanotime) first.
Error in eval(exprs[i], envir) : 
  2 errors out of 7437 (lastID=1880.2, endian==little, sizeof(long double)==16, sizeof(pointer)==8) in inst/tests/tests.Rraw on Wed Mar 14 00:58:14 2018. Search tests.Rraw for test numbers: 167, 167.2.
```

**Comment by HughParsonage** [comment] 2018-03-14 00:18
@mattdowle the fix is still yet to be merged in #2545 I think.

**Comment by mattdowle** [comment] 2018-03-14 00:54
Ah yes. This error is a different more recent error, caused by a recent change in ggplot2. It's a bit of a silly test really.  PR #2671 removes ggplot2 from Suggest and these tests.  The fixed ggplot test thanks to Hugh needs going into the new (to be created) compatibility package, then.

**Comment by HughParsonage** [comment] 2018-03-14 01:09
Do you want me to modify PR #2545 at all? Or just leave till you get time?

**Comment by mattdowle** [comment] 2018-03-14 09:04
Nothing needed thanks. Yeah I'll get to #2545 when I'm wrapping up fread.  There's other fread tasks in that area so I'll try and do them at same time.

**Closed** 2018-03-15 20:09 UTC
