### ISSUE TITLE
Repro seg fault when filtering zero row data.table

### ISSUE THREAD

**Issue by jbcolvin0** [Rdatatable/data.table#2154] opened 2017-05-09 16:55 UTC
I have a reproducible seg fault with data.table when filtering on a zero row data.table. I have tried this with both the CRAN and github versions.

```
library(data.table)
DT=as.data.table(list(V1=NULL))
DT[V1==0] # seg fault.
```

Thanks.

**Comment by MichaelChirico** [comment] 2018-07-17 16:18
Just reproduced on current dev

**Comment by HughParsonage** [comment] 2018-08-11 01:53
Michael I can't reproduce a segfault on data.table dev or release on Mac, Linux, or Windows. I get an error, but that's expected. (Same with #2303.) Closing for now.

**Comment by st-pasha** [comment] 2018-08-11 01:58
This still reproduces too...
```
> library(data.table)
data.table 1.11.5 IN DEVELOPMENT built 2018-08-11 01:45:12 UTC; pasha  Latest news: r-datatable.com
> DT=as.data.table(list(V1=NULL))
> DT[V1==0] # seg fault.

 *** caught segfault ***
address 0x0, cause 'memory not mapped'
```

**Comment by jangorecki** [comment] 2019-01-29 04:01
On R 3.5.2 I am getting an error
```r
library(data.table)
data.table 1.12.1 IN DEVELOPMENT built 2019-01-29 02:22:08 UTC; travis  Latest news: r-datatable.com
> DT=as.data.table(list(V1=NULL))
> DT[V1==0]
Error in `[.data.table`(DT, V1 == 0) : 
  attempt to set an attribute on NULL
```
so it is already better than crash, but error is quite misleading anyway. Is crash still reproducible for anyone?

**Comment by st-pasha** [comment] 2019-01-29 06:42
Not for me (with R 3.5.1)

**Comment by MichaelChirico** [comment] 2019-01-29 07:00
No crash for me (macOS 10.13.6 / R 3.5.2)

**Comment by Gayyam** [comment] 2019-03-07 03:53
No crash for me. (Windows 10 / R 3.5.2) data.table 1.1.2.0

**Comment by MichaelChirico** [comment] 2019-09-08 14:11
Still not reproducing. Though suggests an improvement to `.checkTypos`:

```
DT[V1==0]
```

> Error in .checkTypos(e, names_x) : Object 'V1' not found amongst

**Closed by MichaelChirico** 2019-09-08 14:11 UTC
Labels: beginner-task
