### ISSUE TITLE
When will version 1.14.3 be released on CRAN?

### ISSUE THREAD

**Issue by vinhdizzo** [Rdatatable/data.table#5466] opened 2022-09-15 17:41 UTC
This isn't a bug/issue.  Was curious on the release date of the next version of `data.table` as I'd like to update one of my R packages to make use of the new `env` argument (`substitute2` function) that's currently available in the dev version.  Thank you.

**Comment by t-wojciech** [comment] 2022-09-16 15:58
This is a bit related: https://github.com/Rdatatable/data.table/issues/5385

**Comment by jangorecki** [comment] 2022-09-16 16:47
This one is even more related https://github.com/Rdatatable/data.table/milestone/20
Few issues there still doesn't have PR closing them, notable those related to DT().
As for dates, they are never known in advance, observing the milestone is probably best indicator about how close we are to release.

**Comment by vinhdizzo** [comment] 2022-09-19 20:06
Thanks for pointing me to these links.  It doesn't appear that version 1.14.3 is going to be released any time soon (e.g., there's an issue that's been open since August 2021).

Do you have any recommendations for releasing a package to CRAN that depends on the new `env` argument in `[.data.table`?  Should we specify `1.14.2` as the minimum version of `data.table` in the `DESCRIPTION` file, then ask the user to run `data.table::update_dev_pkg()` on their end to get to the dev version of `data.table`?  Is this band-aid solution ideal?

Thanks in advance for any insights you could provide.

**Comment by mattdowle** [comment] 2022-10-10 01:49
@vinhdizzo sorry to miss this at the time, and then it caused an impact to your package on CRAN when the patch 1.14.4 was just released. For completeness then, don't use a future version number but test for the functionality. I had in mind :
```R
    "env" %in% names(as.list(args(data.table:::"[.data.table")))
```
but since you need it to be in a package, then use of `:::` is disallowed I think.  In that case : 
```R
   try(DT[, env=])
```

**Closed by mattdowle** 2022-10-10 01:49 UTC

**Comment by vinhdizzo** [comment] 2022-10-10 17:33
For completeness, I [used](https://stackoverflow.com/a/63023801) the following code since `:::` is not allowed in a package on CRAN:

```{r}
"env" %in% names(as.list(args(utils::getFromNamespace("[.data.table", "data.table"))))
```

**Comment by mattdowle** [comment] 2022-10-11 19:31
To take this as an example for future reference ...
I'm thinking that using `try(DT[,env=])` would more elegantly test that feature of the API. More elegant because it tests the API directly. If you use `getFromNamespace()` you're really accessing the internals in the same way as `:::`. The fact that `getFromNamespace()` is allowed in packages currently, doesn't mean it will be in future. Whereas using `try()` will always work in future.

**Comment by MichaelChirico** [comment] 2022-10-11 21:28
> To take this as an example for future reference ... I'm thinking that using `try(DT[,env=])` would more elegantly test that feature of the API. More elegant because it tests the API directly. If you use `getFromNamespace()` you're really accessing the internals in the same way as `:::`. The fact that `getFromNamespace()` is allowed in packages currently, doesn't mean it will be in future. Whereas using `try()` will always work in future.

The problem is it becomes hard to distinguish if `try()` fails for some unanticipated reason (suppose there's a syntax error, or `env=` is indeed an argument but there's still an unresolved variable, etc). The associated error is not specifically classed (just `simpleError`), so you'd have to resort to `grep()`-ing on the `conditionMessage()`, which (1) is no longer elegant and (2) relies on both the base R message not changing and the user locale being `en`, or otherwise introducing even further inelegance to isolate those potential issues.

The `"env" %in% ...` approach is more robust, and easy to throw into a simple wrapper like `test_if_data.table_has_env_arg()` to hide the inelegance under the rug. It's also faster (well, `try()` is slow, `tryCatch()` is also slow but on the same order of microsecond magnitude, so it only really matters if the test is being done a lot, otherwise not noticeable).

Anyway, it's definitely most safe to only rely on CRAN-published behavior... extra motivation for us to get a version with `env=` published soon.

**Comment by mattdowle** [comment] 2022-10-12 02:17
Its funny this talk about elegance when env= is the feature with variable name repetition. I really don't like it but Jan has his reasons and users like it so that's good enough reason to proceed with it. We can disagree and still release it.
