### ISSUE TITLE
merge.data.table using character column crashing Rstudio with tables above 65536 rows

### ISSUE THREAD

**Issue by Stikus** [Rdatatable/data.table#5552] opened 2022-12-05 12:36 UTC
Hello, our production code become broken after we one of our dataframes become bigger than 65536 rows.
For about a year, we have a code that merge small `data.frame` to big `data.table` with `merge`. Due to `merge.data.table` syntax, first argument of merge decided merge manner, and it was `data.table`, resulting `merge.data.table`. I understand that it is not correct to mix types, but it was our oversight.

Last week, our "small" `data.frame` got bigger and Rstudio start to crash not only when merging with big `data.table`, but even with small ones. We switched to `merge.data.frame` and all start working again, but in takes 12+ hours for our code to run instead 1+ hour - that's why I'm asking for help.

After some debug I've found that before 65536 rows in data.frame all is good, and after it is not. We tested this example on several machines, and two of our main machines have error, but some others don't. I've posted session infos from broken and working machine FYI.

I've created an example that shows this behavior. As you can see - `merge.data.frame` working good (`a_test` and `b_test` are data.frames), `merge.data.table` with numeric column working good (`a1_test` and `b1_test` are data.tables), `merge.data.table` with character column fails.

![image](https://user-images.githubusercontent.com/41360525/205637644-118d75be-0ad7-4d97-917f-30dc09ef8133.png)

`#` [`Minimal reproducible example`](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)
```r
library(data.table)

a_test <- setNames(as.data.frame(cbind(1:10, 1:10, 11:20)), c('A', 'A_char',  'B'))
a_test$A_char <- as.character(a_test$A_char)
a1_test <- as.data.table(a_test)
b_test <- setNames(as.data.frame(cbind(1:65600, 1:65600, 21:65620)), c('A', 'A_char', 'C'))
b_test$A_char <- as.character(b_test$A_char)
b1_test <- as.data.table(b_test)
c_test <- merge(a_test, b_test, by = 'A')
c1_test <- merge(a1_test, b1_test, by = 'A')
c1_char_test <- merge(a1_test, b1_test, by = 'A_char')
```

`#` `Output of sessionInfo()`
```
> sessionInfo()
R version 4.2.2 Patched (2022-11-10 r83330)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.14.6

loaded via a namespace (and not attached):
[1] compiler_4.2.2 tools_4.2.2 
```

`#` `Output of sessionInfo() from machine where all is ok`
```
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.14.6

loaded via a namespace (and not attached):
[1] compiler_4.2.1 tools_4.2.1   
```

I've found somewhat similar issue #4733, that's why I've linked it.

I can produce any other debug information if you tell me how. Looking for help - we cannot afford 12+ hours of analysis in production.

**Comment by jangorecki** [comment] 2022-12-05 12:56
Use [ to merge, it will be more efficient. Ensure there are no duplicates in columns you are merging on. The symptoms you describe sounds like a duplicate value sneaked into a column you merge on and that results in many-to-many join.

**Comment by Stikus** [comment] 2022-12-05 13:05
@jangorecki As you can see in example this is ranges of numbers - no duplicates can sneak in. And if I use 65500 instead of 65600 in code all working:
![image](https://user-images.githubusercontent.com/41360525/205644211-d60804d9-fd34-4c5c-bef3-e2509e377ed7.png)

**Comment by ben-schwen** [comment] 2022-12-05 14:24
Does the problem only appear in Rstudio or also in a normal terminal? Seems like a representation error due to `2^16` = `65536` space.

I can't reproduce it on `R 4.2.2` with `Ubuntu 20.04.3 LTS`

**Comment by ben-schwen** [comment] 2022-12-05 15:06
@Stikus Could you try to reduce the number of used cores? E.g. halving them?

`setDTthreads(threads = 48)`. Then it might be related #5087. Does `merge` call `sort` internally?

**Comment by Stikus** [comment] 2022-12-05 15:21
48 threads does fix problem in Rstudio and К console too:
```r
library(data.table)
setDTthreads(threads = 48)

a_test <- setNames(as.data.frame(cbind(1:10, 1:10, 11:20)), c('A', 'A_char',  'B'))
a_test$A_char <- as.character(a_test$A_char)
a1_test <- as.data.table(a_test)
b_test <- setNames(as.data.frame(cbind(1:65600, 1:65600, 21:65620)), c('A', 'A_char', 'C'))
b_test$A_char <- as.character(b_test$A_char)
b1_test <- as.data.table(b_test)
c_test <- merge(a_test, b_test, by = 'A')
c1_test <- merge(a1_test, b1_test, by = 'A')
c1_char_test <- merge(a1_test, b1_test, by = 'A_char')
```

This example works. Thanks for help, I'll test on real data tomorrow. Should I limit it always to 48 or how can I count correct number?

**Comment by jangorecki** [comment] 2022-12-05 17:18
PR to fix this issue seems to be already merged so could be checked on master branch. Hard to say which version it will be.

**Comment by ben-schwen** [comment] 2022-12-06 22:02
Could you try to update to dev version version using `update.dev.pkg()` (or `update_dev_pkg()` depending on which `data.table` version you have installed locally) and try if the issue is fixed while using all cores?

**Comment by ben-schwen** [comment] 2022-12-07 11:22
In this case, you might want to try to install from github e.g. with `remotes` via `remotes::install_github("https://github.com/Rdatatable/data.table")` instead

**Comment by Stikus** [comment] 2022-12-07 11:38
```
> library(data.table)
> setDTthreads(threads = 72)
> 
> a_test <- setNames(as.data.frame(cbind(1:10, 1:10, 11:20)), c('A', 'A_char',  'B'))
> a_test$A_char <- as.character(a_test$A_char)
> a1_test <- as.data.table(a_test)
> b_test <- setNames(as.data.frame(cbind(1:65600, 1:65600, 21:65620)), c('A', 'A_char', 'C'))
> b_test$A_char <- as.character(b_test$A_char)
> b1_test <- as.data.table(b_test)
> c_test <- merge(a_test, b_test, by = 'A')
> c1_test <- merge(a1_test, b1_test, by = 'A')
> c1_char_test <- merge(a1_test, b1_test, by = 'A_char')
> library(data.table)
> setDTthreads(threads = 96)
> 
> a_test <- setNames(as.data.frame(cbind(1:10, 1:10, 11:20)), c('A', 'A_char',  'B'))
> a_test$A_char <- as.character(a_test$A_char)
> a1_test <- as.data.table(a_test)
> b_test <- setNames(as.data.frame(cbind(1:65600, 1:65600, 21:65620)), c('A', 'A_char', 'C'))
> b_test$A_char <- as.character(b_test$A_char)
> b1_test <- as.data.table(b_test)
> c_test <- merge(a_test, b_test, by = 'A')
> c1_test <- merge(a1_test, b1_test, by = 'A')
> c1_char_test <- merge(a1_test, b1_test, by = 'A_char')
```

Thanks, our ISP blocked gitlab.io for some reason. All working on GitHub version - I assume we can close issue now?

**Closed** 2022-12-07 20:20 UTC
