### ISSUE TITLE
Integer64 sums and calculations

### ISSUE THREAD

**Issue by johndrummond** [Rdatatable/data.table#1972] opened 2016-12-22 18:10 UTC
I'm getting incorrect values on data.table calculations with integer64. On a large data set I had a weighted mean less than a minimum value
Thanks for all the work - it's a great package.
A test example
> test1
    spread priceTime pTime intTime
 1:  0.014       205   205     205
 2:  0.016       197   197     197
 3:  0.016       207   207     207
 4:  0.012       201   201     201
 5:  0.014       200   200     200
 6:  0.016       258   258     258
 7:  0.012       172   172     172
 8:  0.012       196   196     196
 9:  0.016       635   635     635
10:  0.022       204   204     204
> str(test1)
Classes ‘data.table’ and 'data.frame':	10 obs. of  4 variables:
 $ spread   : num  0.014 0.016 0.016 0.012 0.014 ...
 $ priceTime:Class 'integer64'  num [1:10] 1.01e-321 9.73e-322 1.02e-321 9.93e-322 9.88e-322 ...
 $ pTime    : num  205 197 207 201 200 258 172 196 635 204
 $ intTime  : int  205 197 207 201 200 258 172 196 635 204
 - attr(*, ".internal.selfref")=<externalptr> 
> test1[,pTime:=as.numeric(priceTime)]
> test1[,intTime:=as.integer(priceTime)]
> str(test1[,.(meanspfloat=sum(spread * pTime)/sum(pTime),
+              meanspint64=sum(spread * priceTime)/sum(priceTime),
+              meanspint32=sum(spread * intTime)/sum(intTime))])
Classes ‘data.table’ and 'data.frame':	1 obs. of  3 variables:
 $ meanspfloat: num 0.0152
 $ meanspint64: num 0
 $ meanspint32: num 0.0152
 - attr(*, ".internal.selfref")=<externalptr> 

SessionInfo()
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] rvest_0.3.2        xml2_1.0.0         bit64_0.9-5        bit_1.1-12         stringdist_0.9.4.2 RODBC_1.3-14       readxl_0.1.1      
 [8] stringr_1.1.0      data.table_1.9.8   feather_0.3.1      dtplyr_0.0.1       lubridate_1.6.0    dplyr_0.5.0        purrr_0.2.2       
[15] readr_1.0.0        tidyr_0.6.0        tibble_1.2         ggplot2_2.2.0      tidyverse_1.0.0   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.8      magrittr_1.5     hms_0.3          munsell_0.4.3    colorspace_1.3-1 R6_2.2.0         httr_1.2.1      
 [8] plyr_1.8.4       tools_3.3.2      parallel_3.3.2   grid_3.3.2       gtable_0.2.0     DBI_0.5-1        lazyeval_0.2.0  
[15] assertthat_0.1   stringi_1.1.2    scales_0.4.1

**Comment by jangorecki** [comment] 2019-05-14 11:35
copy pastable
```r
library(data.table)
library(bit64)
fread("spread priceTime pTime intTime
0.014 205 205 205
0.016 197 197 197") -> d
d[, priceTime := as.integer64(priceTime)]
d[,pTime:=as.numeric(priceTime)]
d[,intTime:=as.integer(priceTime)]
d[, .(meanspfloat=sum(spread * pTime)/sum(pTime),
      meanspint64=sum(spread * priceTime)/sum(priceTime),
      meanspint32=sum(spread * intTime)/sum(intTime))]
#   meanspfloat meanspint64 meanspint32
#         <num>       <num>       <num>
#1:   0.0149801           0   0.0149801
```

**Comment by jangorecki** [comment] 2019-05-14 11:41
What is happening here is that `spread * priceTime` is dispatching to `*` numeric method, rather than `*` integer64. You can isolate the issue from data.table easily
```r
as.numeric(0.014) * as.integer64(205)
#integer64
#[1] 0
as.integer64(205) * as.numeric(0.014)
#integer64
#[1] 3
```
Not sure if we can do much about that. Closing for now as not caused by data.table. If there are any ideas I will be happy to re-open.

**Closed by jangorecki** 2019-05-14 11:41 UTC
Labels: bit64
