### ISSUE TITLE
Broke table by attempting self-crossjoin

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#3730] opened 2019-07-30 06:05 UTC
```
DT = data.table(a = 1:5, b = 1:5)
DT[ , DT, by = names(DT)]
```

>  Error in FUN(X[[i]], ...) : 
  Invalid column: it has dimensions. Can't format it. If it's the result of data.table(table()), use as.data.table(table()) instead. 

But it works on a `copy`:

```
DT[ , copy(DT), by = names(DT)]
#     a b a b
#  1: 1 1 1 1
#  2: 1 1 2 2
#  3: 1 1 3 3
#  4: 1 1 4 4
#  5: 1 1 5 5
#  6: 2 2 1 1
#  7: 2 2 2 2
#  8: 2 2 3 3
#  9: 2 2 4 4
# 10: 2 2 5 5
# 11: 3 3 1 1
# 12: 3 3 2 2
# 13: 3 3 3 3
# 14: 3 3 4 4
# 15: 3 3 5 5
# 16: 4 4 1 1
# 17: 4 4 2 2
# 18: 4 4 3 3
# 19: 4 4 4 4
# 20: 4 4 5 5
# 21: 5 5 1 1
# 22: 5 5 2 2
# 23: 5 5 3 3
# 24: 5 5 4 4
# 25: 5 5 5 5
#     a b a b
```

NB: on the actual example that triggered this, I got a different error:

>  Error in `[.data.table`(x, i, , ) : 
  Column 5 ['SPC'] is a data.frame or data.table; malformed data.table.

I can't tell why the different error but it appears the root cause is the same.

**Comment by franknarf1** [comment] 2019-07-30 16:10
Fwiw, even parentheses without copy will dodge the problem:

```
DT[ , (DT), by = names(DT)] # ok
```

while making a copy does not:

```
DT2 = copy(DT)
DT[ , DT2, by = names(DT)] # same error

L = as.list(DT)
DT[ , L, by = names(DT)] # wrong format, even though it is a list of columns
DT[ , (L), by = names(DT)] # ok
```

so I guess it is an NSE issue when there is a single symbol that evaluates to a table or list.

**Comment by jangorecki** [comment] 2019-07-30 16:17
`Invalid column: it has dimensions. Can't format it.` is from print, when you lookup created object with `str` you can see
```
Classes ‘data.table’ and 'data.frame':	10 obs. of  3 variables:
 $ a : int  1 1 2 2 3 3 4 4 5 5
 $ b : int  1 1 2 2 3 3 4 4 5 5
 $ DT:Classes ‘data.table’ and 'data.frame':	5 obs. of  10 variables:
  ..$ : int  1 2 3 4 5
  ..$ : int  1 2 3 4 5
```

**Comment by MichaelChirico** [comment] 2019-07-30 16:21
Thanks Jan & Frank. So it seems NSE thinks it's a `list` column (`is.list` is `TRUE` after all) and bashes everything into a single column. But then `print`/`format` look to see if `dim` is `NULL` & there's the issue.

**Comment by jangorecki** [comment] 2019-07-30 16:24
from `verbose=TRUE`
```
lapply optimization is on, j unchanged as '(DT)'
# vs
Optimization is on but left j unchanged (single plain symbol): 'DT'
```

**Comment by jangorecki** [comment] 2020-04-06 18:23
AFAIK it is a duplicate of #1473

**Closed by jangorecki** 2020-04-06 18:23 UTC
