### ISSUE TITLE
A mysterious tab `\t` in the vignette `datatable-reference-semantics.Rmd`

### ISSUE THREAD

**Issue by yihui** [Rdatatable/data.table#5735] opened 2023-11-09 20:32 UTC
Re-posted from https://github.com/Rdatatable/data.table/pull/5182/files#r1380402289

I discovered a really weird thing on line 95 in `vignettes/datatable-reference-semantics.Rmd`: https://github.com/Rdatatable/data.table/blob/4c633907a651f25a4e02c86e6bebb6f5c8c37fa8/vignettes/datatable-reference-semantics.Rmd#L95

@MichaelChirico has fixed the code fence two years ago, but if you download the source package from CRAN: https://cran.r-project.org/src/contrib/data.table_1.14.8.tar.gz you will find that the first two spaces on this line are actually a tab `\t`. I don't know what's going on. It will be great if the closing fence could match the opening fence strictly, as the mismatch will be disallowed in **knitr** in the near future: https://github.com/yihui/knitr/pull/2306 Thanks!

**Comment by MichaelChirico** [comment] 2023-11-09 20:38
@yihui I can't say for sure #5182 has made it to a CRAN release yet, can you check if the problem is fixed on current master?

that would be from the `R CMD build` output tar.gz at current HEAD.

If so, we should include this in the next patch release CC @jangorecki

**Comment by yihui** [comment] 2023-11-09 20:57
Yes, I have checked the master branch, and the leading white spaces are truly four spaces, not a tab.

**Comment by MichaelChirico** [comment] 2023-11-09 21:09
OK, I checked on the patch release branch (https://github.com/Rdatatable/data.table/tree/hotfix1.14.10) -- the `\t` was still there, so I think the root issue is that #5182 was never released to CRAN.

I applied the fix to the next patch release, which should hit CRAN "soon".

**Closed by MichaelChirico** 2023-11-09 21:09 UTC

**Comment by yihui** [comment] 2023-11-09 21:11
Perfect. Thank you very much!
